"""
Aureos AI — ASSET UNIVERSE
============================
Master catalog of 500+ tradeable assets organized by class.
Provides the foundation for the Data Infrastructure layer.
"""

# ═══════════════════════════════════════════════
# US STOCKS — Top 200+ by Market Cap
# ═══════════════════════════════════════════════
US_STOCKS = [
    {"symbol": "AAPL", "name": "Apple Inc.", "sector": "Technology"},
    {"symbol": "MSFT", "name": "Microsoft Corp.", "sector": "Technology"},
    {"symbol": "NVDA", "name": "NVIDIA Corp.", "sector": "Technology"},
    {"symbol": "GOOGL", "name": "Alphabet Inc.", "sector": "Technology"},
    {"symbol": "AMZN", "name": "Amazon.com", "sector": "Consumer Cyclical"},
    {"symbol": "META", "name": "Meta Platforms", "sector": "Technology"},
    {"symbol": "TSLA", "name": "Tesla Inc.", "sector": "Consumer Cyclical"},
    {"symbol": "BRK.B", "name": "Berkshire Hathaway B", "sector": "Financial"},
    {"symbol": "AVGO", "name": "Broadcom Inc.", "sector": "Technology"},
    {"symbol": "JPM", "name": "JPMorgan Chase", "sector": "Financial"},
    {"symbol": "LLY", "name": "Eli Lilly", "sector": "Healthcare"},
    {"symbol": "V", "name": "Visa Inc.", "sector": "Financial"},
    {"symbol": "UNH", "name": "UnitedHealth Group", "sector": "Healthcare"},
    {"symbol": "MA", "name": "Mastercard", "sector": "Financial"},
    {"symbol": "XOM", "name": "Exxon Mobil", "sector": "Energy"},
    {"symbol": "COST", "name": "Costco Wholesale", "sector": "Consumer Defensive"},
    {"symbol": "HD", "name": "Home Depot", "sector": "Consumer Cyclical"},
    {"symbol": "PG", "name": "Procter & Gamble", "sector": "Consumer Defensive"},
    {"symbol": "JNJ", "name": "Johnson & Johnson", "sector": "Healthcare"},
    {"symbol": "ABBV", "name": "AbbVie Inc.", "sector": "Healthcare"},
    {"symbol": "NFLX", "name": "Netflix Inc.", "sector": "Communication"},
    {"symbol": "CRM", "name": "Salesforce", "sector": "Technology"},
    {"symbol": "BAC", "name": "Bank of America", "sector": "Financial"},
    {"symbol": "AMD", "name": "Advanced Micro Devices", "sector": "Technology"},
    {"symbol": "ORCL", "name": "Oracle Corp.", "sector": "Technology"},
    {"symbol": "KO", "name": "Coca-Cola", "sector": "Consumer Defensive"},
    {"symbol": "MRK", "name": "Merck & Co.", "sector": "Healthcare"},
    {"symbol": "PEP", "name": "PepsiCo", "sector": "Consumer Defensive"},
    {"symbol": "CVX", "name": "Chevron Corp.", "sector": "Energy"},
    {"symbol": "TMO", "name": "Thermo Fisher Scientific", "sector": "Healthcare"},
    {"symbol": "WMT", "name": "Walmart Inc.", "sector": "Consumer Defensive"},
    {"symbol": "ADBE", "name": "Adobe Inc.", "sector": "Technology"},
    {"symbol": "ABT", "name": "Abbott Laboratories", "sector": "Healthcare"},
    {"symbol": "CSCO", "name": "Cisco Systems", "sector": "Technology"},
    {"symbol": "ACN", "name": "Accenture", "sector": "Technology"},
    {"symbol": "MCD", "name": "McDonald's", "sector": "Consumer Cyclical"},
    {"symbol": "IBM", "name": "IBM", "sector": "Technology"},
    {"symbol": "INTC", "name": "Intel Corp.", "sector": "Technology"},
    {"symbol": "PM", "name": "Philip Morris", "sector": "Consumer Defensive"},
    {"symbol": "DIS", "name": "Walt Disney", "sector": "Communication"},
    {"symbol": "DHR", "name": "Danaher Corp.", "sector": "Healthcare"},
    {"symbol": "VZ", "name": "Verizon", "sector": "Communication"},
    {"symbol": "TXN", "name": "Texas Instruments", "sector": "Technology"},
    {"symbol": "QCOM", "name": "Qualcomm", "sector": "Technology"},
    {"symbol": "INTU", "name": "Intuit Inc.", "sector": "Technology"},
    {"symbol": "CAT", "name": "Caterpillar", "sector": "Industrials"},
    {"symbol": "AMGN", "name": "Amgen Inc.", "sector": "Healthcare"},
    {"symbol": "NOW", "name": "ServiceNow", "sector": "Technology"},
    {"symbol": "GE", "name": "General Electric", "sector": "Industrials"},
    {"symbol": "AXP", "name": "American Express", "sector": "Financial"},
    {"symbol": "ISRG", "name": "Intuitive Surgical", "sector": "Healthcare"},
    {"symbol": "BKNG", "name": "Booking Holdings", "sector": "Consumer Cyclical"},
    {"symbol": "GS", "name": "Goldman Sachs", "sector": "Financial"},
    {"symbol": "SPGI", "name": "S&P Global", "sector": "Financial"},
    {"symbol": "BLK", "name": "BlackRock", "sector": "Financial"},
    {"symbol": "PFE", "name": "Pfizer Inc.", "sector": "Healthcare"},
    {"symbol": "T", "name": "AT&T", "sector": "Communication"},
    {"symbol": "RTX", "name": "RTX Corp.", "sector": "Industrials"},
    {"symbol": "HON", "name": "Honeywell", "sector": "Industrials"},
    {"symbol": "LMT", "name": "Lockheed Martin", "sector": "Industrials"},
    {"symbol": "UNP", "name": "Union Pacific", "sector": "Industrials"},
    {"symbol": "NEE", "name": "NextEra Energy", "sector": "Utilities"},
    {"symbol": "LOW", "name": "Lowe's", "sector": "Consumer Cyclical"},
    {"symbol": "SYK", "name": "Stryker Corp.", "sector": "Healthcare"},
    {"symbol": "ELV", "name": "Elevance Health", "sector": "Healthcare"},
    {"symbol": "MDT", "name": "Medtronic", "sector": "Healthcare"},
    {"symbol": "DE", "name": "Deere & Co.", "sector": "Industrials"},
    {"symbol": "BMY", "name": "Bristol-Myers Squibb", "sector": "Healthcare"},
    {"symbol": "AMAT", "name": "Applied Materials", "sector": "Technology"},
    {"symbol": "PLD", "name": "Prologis", "sector": "Real Estate"},
    {"symbol": "LRCX", "name": "Lam Research", "sector": "Technology"},
    {"symbol": "SCHW", "name": "Charles Schwab", "sector": "Financial"},
    {"symbol": "ADP", "name": "ADP", "sector": "Industrials"},
    {"symbol": "C", "name": "Citigroup", "sector": "Financial"},
    {"symbol": "GILD", "name": "Gilead Sciences", "sector": "Healthcare"},
    {"symbol": "CB", "name": "Chubb Limited", "sector": "Financial"},
    {"symbol": "MMC", "name": "Marsh & McLennan", "sector": "Financial"},
    {"symbol": "VRTX", "name": "Vertex Pharmaceuticals", "sector": "Healthcare"},
    {"symbol": "ETN", "name": "Eaton Corp.", "sector": "Industrials"},
    {"symbol": "FI", "name": "Fiserv Inc.", "sector": "Technology"},
    {"symbol": "SO", "name": "Southern Company", "sector": "Utilities"},
    {"symbol": "DUK", "name": "Duke Energy", "sector": "Utilities"},
    {"symbol": "MO", "name": "Altria Group", "sector": "Consumer Defensive"},
    {"symbol": "CI", "name": "Cigna Group", "sector": "Healthcare"},
    {"symbol": "BSX", "name": "Boston Scientific", "sector": "Healthcare"},
    {"symbol": "CME", "name": "CME Group", "sector": "Financial"},
    {"symbol": "ICE", "name": "Intercontinental Exchange", "sector": "Financial"},
    {"symbol": "SHW", "name": "Sherwin-Williams", "sector": "Materials"},
    {"symbol": "REGN", "name": "Regeneron", "sector": "Healthcare"},
    {"symbol": "ZTS", "name": "Zoetis Inc.", "sector": "Healthcare"},
    {"symbol": "CL", "name": "Colgate-Palmolive", "sector": "Consumer Defensive"},
    {"symbol": "WM", "name": "Waste Management", "sector": "Industrials"},
    {"symbol": "NOC", "name": "Northrop Grumman", "sector": "Industrials"},
    {"symbol": "KLAC", "name": "KLA Corp.", "sector": "Technology"},
    {"symbol": "SNPS", "name": "Synopsys", "sector": "Technology"},
    {"symbol": "CDNS", "name": "Cadence Design", "sector": "Technology"},
    {"symbol": "PANW", "name": "Palo Alto Networks", "sector": "Technology"},
    {"symbol": "MRVL", "name": "Marvell Technology", "sector": "Technology"},
    {"symbol": "PLTR", "name": "Palantir", "sector": "Technology"},
    {"symbol": "CRWD", "name": "CrowdStrike", "sector": "Technology"},
    {"symbol": "COIN", "name": "Coinbase Global", "sector": "Financial"},
    {"symbol": "SQ", "name": "Block Inc.", "sector": "Technology"},
    {"symbol": "SHOP", "name": "Shopify", "sector": "Technology"},
    {"symbol": "SNAP", "name": "Snap Inc.", "sector": "Communication"},
    {"symbol": "UBER", "name": "Uber Technologies", "sector": "Technology"},
    {"symbol": "ABNB", "name": "Airbnb", "sector": "Consumer Cyclical"},
    {"symbol": "RBLX", "name": "Roblox Corp.", "sector": "Communication"},
    {"symbol": "RIVN", "name": "Rivian Automotive", "sector": "Consumer Cyclical"},
    {"symbol": "LCID", "name": "Lucid Group", "sector": "Consumer Cyclical"},
    {"symbol": "NIO", "name": "NIO Inc.", "sector": "Consumer Cyclical"},
    {"symbol": "SOFI", "name": "SoFi Technologies", "sector": "Financial"},
    {"symbol": "DKNG", "name": "DraftKings", "sector": "Consumer Cyclical"},
    {"symbol": "ARM", "name": "ARM Holdings", "sector": "Technology"},
    {"symbol": "SMCI", "name": "Super Micro Computer", "sector": "Technology"},
    {"symbol": "MU", "name": "Micron Technology", "sector": "Technology"},
    {"symbol": "ON", "name": "ON Semiconductor", "sector": "Technology"},
    {"symbol": "MELI", "name": "MercadoLibre", "sector": "Consumer Cyclical"},
    {"symbol": "SPOT", "name": "Spotify", "sector": "Communication"},
    {"symbol": "PYPL", "name": "PayPal Holdings", "sector": "Financial"},
    {"symbol": "SE", "name": "Sea Limited", "sector": "Communication"},
    {"symbol": "NET", "name": "Cloudflare", "sector": "Technology"},
    {"symbol": "SNOW", "name": "Snowflake", "sector": "Technology"},
    {"symbol": "DDOG", "name": "Datadog", "sector": "Technology"},
    {"symbol": "ZS", "name": "Zscaler", "sector": "Technology"},
    {"symbol": "TTD", "name": "The Trade Desk", "sector": "Technology"},
    {"symbol": "TEAM", "name": "Atlassian", "sector": "Technology"},
    {"symbol": "WDAY", "name": "Workday", "sector": "Technology"},
    {"symbol": "FTNT", "name": "Fortinet", "sector": "Technology"},
    {"symbol": "DASH", "name": "DoorDash", "sector": "Technology"},
    {"symbol": "ROKU", "name": "Roku Inc.", "sector": "Communication"},
    {"symbol": "PINS", "name": "Pinterest", "sector": "Communication"},
    {"symbol": "TWLO", "name": "Twilio", "sector": "Technology"},
    {"symbol": "OKTA", "name": "Okta Inc.", "sector": "Technology"},
    {"symbol": "MSTR", "name": "MicroStrategy", "sector": "Technology"},
    {"symbol": "PATH", "name": "UiPath", "sector": "Technology"},
    {"symbol": "U", "name": "Unity Software", "sector": "Technology"},
    {"symbol": "AI", "name": "C3.ai", "sector": "Technology"},
    {"symbol": "HOOD", "name": "Robinhood Markets", "sector": "Financial"},
    {"symbol": "UPST", "name": "Upstart Holdings", "sector": "Financial"},
    {"symbol": "AFRM", "name": "Affirm Holdings", "sector": "Financial"},
    {"symbol": "BILL", "name": "BILL Holdings", "sector": "Technology"},
    {"symbol": "HUBS", "name": "HubSpot", "sector": "Technology"},
    {"symbol": "MNDY", "name": "Monday.com", "sector": "Technology"},
    {"symbol": "CFLT", "name": "Confluent", "sector": "Technology"},
    {"symbol": "MDB", "name": "MongoDB Inc.", "sector": "Technology"},
    {"symbol": "ESTC", "name": "Elastic N.V.", "sector": "Technology"},
    {"symbol": "GTLB", "name": "GitLab", "sector": "Technology"},
    {"symbol": "S", "name": "SentinelOne", "sector": "Technology"},
    {"symbol": "CYBR", "name": "CyberArk Software", "sector": "Technology"},
    {"symbol": "TMDX", "name": "TransMedics Group", "sector": "Healthcare"},
    {"symbol": "AXON", "name": "Axon Enterprise", "sector": "Industrials"},
    {"symbol": "CELH", "name": "Celsius Holdings", "sector": "Consumer Defensive"},
    {"symbol": "CAVA", "name": "CAVA Group", "sector": "Consumer Cyclical"},
    {"symbol": "LW", "name": "Lamb Weston", "sector": "Consumer Defensive"},
    {"symbol": "LULU", "name": "Lululemon", "sector": "Consumer Cyclical"},
    {"symbol": "NKE", "name": "Nike Inc.", "sector": "Consumer Cyclical"},
    {"symbol": "SBUX", "name": "Starbucks", "sector": "Consumer Cyclical"},
    {"symbol": "CMG", "name": "Chipotle", "sector": "Consumer Cyclical"},
    {"symbol": "YUM", "name": "Yum! Brands", "sector": "Consumer Cyclical"},
    {"symbol": "F", "name": "Ford Motor", "sector": "Consumer Cyclical"},
    {"symbol": "GM", "name": "General Motors", "sector": "Consumer Cyclical"},
    {"symbol": "TGT", "name": "Target Corp.", "sector": "Consumer Defensive"},
    {"symbol": "DLTR", "name": "Dollar Tree", "sector": "Consumer Defensive"},
    {"symbol": "DG", "name": "Dollar General", "sector": "Consumer Defensive"},
    {"symbol": "KR", "name": "Kroger", "sector": "Consumer Defensive"},
    {"symbol": "WBA", "name": "Walgreens Boots", "sector": "Healthcare"},
    {"symbol": "CVS", "name": "CVS Health", "sector": "Healthcare"},
    {"symbol": "BIIB", "name": "Biogen Inc.", "sector": "Healthcare"},
    {"symbol": "MRNA", "name": "Moderna", "sector": "Healthcare"},
    {"symbol": "ZM", "name": "Zoom Video", "sector": "Technology"},
    {"symbol": "DOCU", "name": "DocuSign", "sector": "Technology"},
    {"symbol": "VEEV", "name": "Veeva Systems", "sector": "Healthcare"},
    {"symbol": "SPLK", "name": "Splunk", "sector": "Technology"},
    {"symbol": "WDC", "name": "Western Digital", "sector": "Technology"},
    {"symbol": "STX", "name": "Seagate Technology", "sector": "Technology"},
    {"symbol": "HPQ", "name": "HP Inc.", "sector": "Technology"},
    {"symbol": "DELL", "name": "Dell Technologies", "sector": "Technology"},
    {"symbol": "FLEX", "name": "Flex Ltd.", "sector": "Technology"},
    {"symbol": "WFC", "name": "Wells Fargo", "sector": "Financial"},
    {"symbol": "MS", "name": "Morgan Stanley", "sector": "Financial"},
    {"symbol": "USB", "name": "U.S. Bancorp", "sector": "Financial"},
    {"symbol": "PNC", "name": "PNC Financial", "sector": "Financial"},
    {"symbol": "TFC", "name": "Truist Financial", "sector": "Financial"},
    {"symbol": "COF", "name": "Capital One", "sector": "Financial"},
    {"symbol": "DFS", "name": "Discover Financial", "sector": "Financial"},
    {"symbol": "SYF", "name": "Synchrony Financial", "sector": "Financial"},
    {"symbol": "AFL", "name": "Aflac", "sector": "Financial"},
    {"symbol": "MET", "name": "MetLife", "sector": "Financial"},
    {"symbol": "PRU", "name": "Prudential Financial", "sector": "Financial"},
    {"symbol": "FDX", "name": "FedEx", "sector": "Industrials"},
    {"symbol": "UPS", "name": "United Parcel Service", "sector": "Industrials"},
    {"symbol": "BA", "name": "Boeing", "sector": "Industrials"},
    {"symbol": "GD", "name": "General Dynamics", "sector": "Industrials"},
    {"symbol": "MMM", "name": "3M Company", "sector": "Industrials"},
    {"symbol": "EMR", "name": "Emerson Electric", "sector": "Industrials"},
    {"symbol": "ITW", "name": "Illinois Tool Works", "sector": "Industrials"},
    {"symbol": "PCAR", "name": "PACCAR", "sector": "Industrials"},
    {"symbol": "COP", "name": "ConocoPhillips", "sector": "Energy"},
    {"symbol": "SLB", "name": "Schlumberger", "sector": "Energy"},
    {"symbol": "EOG", "name": "EOG Resources", "sector": "Energy"},
    {"symbol": "PSX", "name": "Phillips 66", "sector": "Energy"},
    {"symbol": "MPC", "name": "Marathon Petroleum", "sector": "Energy"},
    {"symbol": "VLO", "name": "Valero Energy", "sector": "Energy"},
    {"symbol": "OXY", "name": "Occidental Petroleum", "sector": "Energy"},
    {"symbol": "DVN", "name": "Devon Energy", "sector": "Energy"},
    {"symbol": "FANG", "name": "Diamondback Energy", "sector": "Energy"},
    {"symbol": "HAL", "name": "Halliburton", "sector": "Energy"},
    {"symbol": "AEP", "name": "American Electric Power", "sector": "Utilities"},
    {"symbol": "D", "name": "Dominion Energy", "sector": "Utilities"},
    {"symbol": "SRE", "name": "Sempra", "sector": "Utilities"},
    {"symbol": "EXC", "name": "Exelon", "sector": "Utilities"},
    {"symbol": "AMT", "name": "American Tower", "sector": "Real Estate"},
    {"symbol": "CCI", "name": "Crown Castle", "sector": "Real Estate"},
    {"symbol": "O", "name": "Realty Income", "sector": "Real Estate"},
    {"symbol": "WELL", "name": "Welltower", "sector": "Real Estate"},
    {"symbol": "APD", "name": "Air Products", "sector": "Materials"},
    {"symbol": "LIN", "name": "Linde PLC", "sector": "Materials"},
    {"symbol": "ECL", "name": "Ecolab", "sector": "Materials"},
    {"symbol": "NEM", "name": "Newmont Corp.", "sector": "Materials"},
    {"symbol": "FCX", "name": "Freeport-McMoRan", "sector": "Materials"},
]

# ═══════════════════════════════════════════════
# INTERNATIONAL STOCKS
# ═══════════════════════════════════════════════
INTERNATIONAL_STOCKS = [
    {"symbol": "TSM", "name": "Taiwan Semiconductor", "sector": "Technology", "country": "Taiwan"},
    {"symbol": "BABA", "name": "Alibaba Group", "sector": "Consumer Cyclical", "country": "China"},
    {"symbol": "TCEHY", "name": "Tencent Holdings", "sector": "Communication", "country": "China"},
    {"symbol": "ASML", "name": "ASML Holding", "sector": "Technology", "country": "Netherlands"},
    {"symbol": "NVO", "name": "Novo Nordisk", "sector": "Healthcare", "country": "Denmark"},
    {"symbol": "SAP", "name": "SAP SE", "sector": "Technology", "country": "Germany"},
    {"symbol": "TM", "name": "Toyota Motor", "sector": "Consumer Cyclical", "country": "Japan"},
    {"symbol": "SONY", "name": "Sony Group", "sector": "Technology", "country": "Japan"},
    {"symbol": "UL", "name": "Unilever", "sector": "Consumer Defensive", "country": "UK"},
    {"symbol": "HSBC", "name": "HSBC Holdings", "sector": "Financial", "country": "UK"},
    {"symbol": "RIO", "name": "Rio Tinto", "sector": "Materials", "country": "Australia"},
    {"symbol": "BHP", "name": "BHP Group", "sector": "Materials", "country": "Australia"},
    {"symbol": "VALE", "name": "Vale S.A.", "sector": "Materials", "country": "Brazil"},
    {"symbol": "PBR", "name": "Petrobras", "sector": "Energy", "country": "Brazil"},
    {"symbol": "ITUB", "name": "Itau Unibanco", "sector": "Financial", "country": "Brazil"},
    {"symbol": "BBD", "name": "Bradesco", "sector": "Financial", "country": "Brazil"},
    {"symbol": "NU", "name": "Nu Holdings", "sector": "Financial", "country": "Brazil"},
    {"symbol": "MELI", "name": "MercadoLibre", "sector": "Consumer Cyclical", "country": "Argentina"},
    {"symbol": "SHOP", "name": "Shopify", "sector": "Technology", "country": "Canada"},
    {"symbol": "TD", "name": "Toronto-Dominion Bank", "sector": "Financial", "country": "Canada"},
    {"symbol": "ENB", "name": "Enbridge", "sector": "Energy", "country": "Canada"},
    {"symbol": "RELX", "name": "RELX PLC", "sector": "Industrials", "country": "UK"},
    {"symbol": "AZN", "name": "AstraZeneca", "sector": "Healthcare", "country": "UK"},
    {"symbol": "SHEL", "name": "Shell PLC", "sector": "Energy", "country": "UK"},
    {"symbol": "BP", "name": "BP PLC", "sector": "Energy", "country": "UK"},
    {"symbol": "SNY", "name": "Sanofi", "sector": "Healthcare", "country": "France"},
    {"symbol": "TTE", "name": "TotalEnergies", "sector": "Energy", "country": "France"},
    {"symbol": "BIDU", "name": "Baidu", "sector": "Communication", "country": "China"},
    {"symbol": "JD", "name": "JD.com", "sector": "Consumer Cyclical", "country": "China"},
    {"symbol": "PDD", "name": "PDD Holdings", "sector": "Consumer Cyclical", "country": "China"},
    {"symbol": "LI", "name": "Li Auto", "sector": "Consumer Cyclical", "country": "China"},
    {"symbol": "XPEV", "name": "XPeng Inc.", "sector": "Consumer Cyclical", "country": "China"},
    {"symbol": "BEKE", "name": "KE Holdings", "sector": "Real Estate", "country": "China"},
    {"symbol": "SE", "name": "Sea Limited", "sector": "Technology", "country": "Singapore"},
    {"symbol": "GRAB", "name": "Grab Holdings", "sector": "Technology", "country": "Singapore"},
    {"symbol": "SYM", "name": "Symbotic Inc.", "sector": "Industrials", "country": "US"},
    {"symbol": "SMFG", "name": "Sumitomo Mitsui", "sector": "Financial", "country": "Japan"},
    {"symbol": "MUFG", "name": "Mitsubishi UFJ", "sector": "Financial", "country": "Japan"},
    {"symbol": "NMR", "name": "Nomura Holdings", "sector": "Financial", "country": "Japan"},
    {"symbol": "KB", "name": "KB Financial Group", "sector": "Financial", "country": "South Korea"},
    {"symbol": "SHG", "name": "Shinhan Financial", "sector": "Financial", "country": "South Korea"},
    {"symbol": "INFY", "name": "Infosys", "sector": "Technology", "country": "India"},
    {"symbol": "WIT", "name": "Wipro", "sector": "Technology", "country": "India"},
    {"symbol": "HDB", "name": "HDFC Bank", "sector": "Financial", "country": "India"},
    {"symbol": "IBN", "name": "ICICI Bank", "sector": "Financial", "country": "India"},
    {"symbol": "BNTX", "name": "BioNTech", "sector": "Healthcare", "country": "Germany"},
    {"symbol": "DB", "name": "Deutsche Bank", "sector": "Financial", "country": "Germany"},
    {"symbol": "ING", "name": "ING Group", "sector": "Financial", "country": "Netherlands"},
    {"symbol": "ERIC", "name": "Ericsson", "sector": "Technology", "country": "Sweden"},
    {"symbol": "NOK", "name": "Nokia", "sector": "Technology", "country": "Finland"},
    {"symbol": "SAN", "name": "Banco Santander", "sector": "Financial", "country": "Spain"},
    {"symbol": "BBVA", "name": "BBVA", "sector": "Financial", "country": "Spain"},
    {"symbol": "UBS", "name": "UBS Group", "sector": "Financial", "country": "Switzerland"},
    {"symbol": "CS", "name": "Credit Suisse", "sector": "Financial", "country": "Switzerland"},
    {"symbol": "WBD", "name": "Warner Bros Discovery", "sector": "Communication", "country": "US"},
    {"symbol": "PARA", "name": "Paramount Global", "sector": "Communication", "country": "US"},
    {"symbol": "PTON", "name": "Peloton Interactive", "sector": "Consumer Cyclical", "country": "US"},
    {"symbol": "BYND", "name": "Beyond Meat", "sector": "Consumer Defensive", "country": "US"},
    {"symbol": "CHWY", "name": "Chewy Inc.", "sector": "Consumer Cyclical", "country": "US"},
    {"symbol": "RKLB", "name": "Rocket Lab", "sector": "Industrials", "country": "US"},
    {"symbol": "ASTS", "name": "AST SpaceMobile", "sector": "Communication", "country": "US"},
    {"symbol": "IONQ", "name": "IonQ Inc.", "sector": "Technology", "country": "US"},
    {"symbol": "RGTI", "name": "Rigetti Computing", "sector": "Technology", "country": "US"},
    {"symbol": "QBTS", "name": "D-Wave Quantum", "sector": "Technology", "country": "US"},
    {"symbol": "JOBY", "name": "Joby Aviation", "sector": "Industrials", "country": "US"},
    {"symbol": "LILM", "name": "Lilium N.V.", "sector": "Industrials", "country": "Germany"},
    {"symbol": "LUNR", "name": "Intuitive Machines", "sector": "Industrials", "country": "US"},
    {"symbol": "SPCE", "name": "Virgin Galactic", "sector": "Industrials", "country": "US"},
    {"symbol": "STEM", "name": "Stem Inc.", "sector": "Technology", "country": "US"},
]

# ═══════════════════════════════════════════════
# ETFs
# ═══════════════════════════════════════════════
ETFS = [
    {"symbol": "SPY", "name": "S&P 500 ETF", "category": "US Large Cap"},
    {"symbol": "QQQ", "name": "NASDAQ 100 ETF", "category": "US Tech"},
    {"symbol": "DIA", "name": "Dow Jones ETF", "category": "US Large Cap"},
    {"symbol": "IWM", "name": "Russell 2000 ETF", "category": "US Small Cap"},
    {"symbol": "VTI", "name": "Total Stock Market ETF", "category": "US Total"},
    {"symbol": "VOO", "name": "Vanguard S&P 500", "category": "US Large Cap"},
    {"symbol": "EEM", "name": "Emerging Markets ETF", "category": "Emerging"},
    {"symbol": "VWO", "name": "Vanguard Emerging Markets", "category": "Emerging"},
    {"symbol": "EFA", "name": "EAFE International ETF", "category": "International"},
    {"symbol": "GLD", "name": "Gold ETF", "category": "Commodity"},
    {"symbol": "SLV", "name": "Silver ETF", "category": "Commodity"},
    {"symbol": "USO", "name": "US Oil ETF", "category": "Commodity"},
    {"symbol": "TLT", "name": "20+ Year Treasury Bond", "category": "Bond"},
    {"symbol": "HYG", "name": "High Yield Corporate Bond", "category": "Bond"},
    {"symbol": "LQD", "name": "Investment Grade Corporate Bond", "category": "Bond"},
    {"symbol": "XLF", "name": "Financial Select SPDR", "category": "Sector"},
    {"symbol": "XLK", "name": "Technology Select SPDR", "category": "Sector"},
    {"symbol": "XLE", "name": "Energy Select SPDR", "category": "Sector"},
    {"symbol": "XLV", "name": "Health Care Select SPDR", "category": "Sector"},
    {"symbol": "XLI", "name": "Industrial Select SPDR", "category": "Sector"},
    {"symbol": "XLRE", "name": "Real Estate Select SPDR", "category": "Sector"},
    {"symbol": "XLP", "name": "Consumer Staples SPDR", "category": "Sector"},
    {"symbol": "XLU", "name": "Utilities Select SPDR", "category": "Sector"},
    {"symbol": "ARKK", "name": "ARK Innovation ETF", "category": "Innovation"},
    {"symbol": "SOXX", "name": "Semiconductor ETF", "category": "Sector"},
    {"symbol": "SMH", "name": "VanEck Semiconductor", "category": "Sector"},
    {"symbol": "XBI", "name": "Biotech ETF", "category": "Sector"},
    {"symbol": "KWEB", "name": "China Internet ETF", "category": "International"},
    {"symbol": "VNQ", "name": "Vanguard Real Estate", "category": "Real Estate"},
    {"symbol": "IBIT", "name": "iShares Bitcoin Trust", "category": "Crypto"},
    {"symbol": "FBTC", "name": "Fidelity Bitcoin ETF", "category": "Crypto"},
    {"symbol": "GBTC", "name": "Grayscale Bitcoin Trust", "category": "Crypto"},
    {"symbol": "ETHE", "name": "Grayscale Ethereum Trust", "category": "Crypto"},
    {"symbol": "BITO", "name": "ProShares Bitcoin Strategy", "category": "Crypto"},
    {"symbol": "SQQQ", "name": "ProShares UltraPro Short QQQ", "category": "Inverse"},
    {"symbol": "TQQQ", "name": "ProShares UltraPro QQQ", "category": "Leveraged"},
    {"symbol": "SPXS", "name": "Direxion Daily S&P 500 Bear 3X", "category": "Inverse"},
    {"symbol": "SPXL", "name": "Direxion Daily S&P 500 Bull 3X", "category": "Leveraged"},
    {"symbol": "VEA", "name": "Vanguard FTSE Developed", "category": "International"},
    {"symbol": "IEMG", "name": "iShares Core Emerging Markets", "category": "Emerging"},
    {"symbol": "BND", "name": "Vanguard Total Bond Market", "category": "Bond"},
    {"symbol": "AGG", "name": "iShares Core US Aggregate Bond", "category": "Bond"},
    {"symbol": "TIP", "name": "iShares TIPS Bond", "category": "Bond"},
    {"symbol": "DBC", "name": "Invesco DB Commodity Tracking", "category": "Commodity"},
    {"symbol": "UNG", "name": "United States Natural Gas", "category": "Commodity"},
    {"symbol": "COPX", "name": "Global X Copper Miners", "category": "Commodity"},
    {"symbol": "GDX", "name": "VanEck Gold Miners", "category": "Commodity"},
    {"symbol": "GDXJ", "name": "VanEck Junior Gold Miners", "category": "Commodity"},
    {"symbol": "XLC", "name": "Communication Services SPDR", "category": "Sector"},
    {"symbol": "XLB", "name": "Materials Select SPDR", "category": "Sector"},
    {"symbol": "XLY", "name": "Consumer Discretionary SPDR", "category": "Sector"},
    {"symbol": "HACK", "name": "ETFMG Prime Cyber Security", "category": "Sector"},
    {"symbol": "BOTZ", "name": "Global X Robotics & AI", "category": "Innovation"},
    {"symbol": "ROBO", "name": "Robo Global Robotics ETF", "category": "Innovation"},
]

# ═══════════════════════════════════════════════
# CRYPTO — Top 100+
# ═══════════════════════════════════════════════
CRYPTO = [
    {"symbol": "BTC", "name": "Bitcoin", "coingecko_id": "bitcoin"},
    {"symbol": "ETH", "name": "Ethereum", "coingecko_id": "ethereum"},
    {"symbol": "BNB", "name": "Binance Coin", "coingecko_id": "binancecoin"},
    {"symbol": "SOL", "name": "Solana", "coingecko_id": "solana"},
    {"symbol": "XRP", "name": "Ripple", "coingecko_id": "ripple"},
    {"symbol": "ADA", "name": "Cardano", "coingecko_id": "cardano"},
    {"symbol": "AVAX", "name": "Avalanche", "coingecko_id": "avalanche-2"},
    {"symbol": "DOGE", "name": "Dogecoin", "coingecko_id": "dogecoin"},
    {"symbol": "DOT", "name": "Polkadot", "coingecko_id": "polkadot"},
    {"symbol": "LINK", "name": "Chainlink", "coingecko_id": "chainlink"},
    {"symbol": "MATIC", "name": "Polygon", "coingecko_id": "matic-network"},
    {"symbol": "SHIB", "name": "Shiba Inu", "coingecko_id": "shiba-inu"},
    {"symbol": "UNI", "name": "Uniswap", "coingecko_id": "uniswap"},
    {"symbol": "ATOM", "name": "Cosmos", "coingecko_id": "cosmos"},
    {"symbol": "LTC", "name": "Litecoin", "coingecko_id": "litecoin"},
    {"symbol": "NEAR", "name": "NEAR Protocol", "coingecko_id": "near"},
    {"symbol": "APT", "name": "Aptos", "coingecko_id": "aptos"},
    {"symbol": "ARB", "name": "Arbitrum", "coingecko_id": "arbitrum"},
    {"symbol": "OP", "name": "Optimism", "coingecko_id": "optimism"},
    {"symbol": "SUI", "name": "Sui", "coingecko_id": "sui"},
    {"symbol": "FIL", "name": "Filecoin", "coingecko_id": "filecoin"},
    {"symbol": "AAVE", "name": "Aave", "coingecko_id": "aave"},
    {"symbol": "MKR", "name": "Maker", "coingecko_id": "maker"},
    {"symbol": "GRT", "name": "The Graph", "coingecko_id": "the-graph"},
    {"symbol": "IMX", "name": "Immutable X", "coingecko_id": "immutable-x"},
    {"symbol": "FTM", "name": "Fantom", "coingecko_id": "fantom"},
    {"symbol": "ALGO", "name": "Algorand", "coingecko_id": "algorand"},
    {"symbol": "SAND", "name": "The Sandbox", "coingecko_id": "the-sandbox"},
    {"symbol": "MANA", "name": "Decentraland", "coingecko_id": "decentraland"},
    {"symbol": "AXS", "name": "Axie Infinity", "coingecko_id": "axie-infinity"},
    {"symbol": "ENS", "name": "Ethereum Name Service", "coingecko_id": "ethereum-name-service"},
    {"symbol": "CRV", "name": "Curve DAO", "coingecko_id": "curve-dao-token"},
    {"symbol": "LDO", "name": "Lido DAO", "coingecko_id": "lido-dao"},
    {"symbol": "RNDR", "name": "Render Token", "coingecko_id": "render-token"},
    {"symbol": "INJ", "name": "Injective", "coingecko_id": "injective-protocol"},
    {"symbol": "TIA", "name": "Celestia", "coingecko_id": "celestia"},
    {"symbol": "SEI", "name": "Sei", "coingecko_id": "sei-network"},
    {"symbol": "PEPE", "name": "Pepe", "coingecko_id": "pepe"},
    {"symbol": "BONK", "name": "Bonk", "coingecko_id": "bonk"},
    {"symbol": "WIF", "name": "Dogwifhat", "coingecko_id": "dogwifcoin"},
    {"symbol": "JASMY", "name": "JasmyCoin", "coingecko_id": "jasmycoin"},
    {"symbol": "HBAR", "name": "Hedera", "coingecko_id": "hedera-hashgraph"},
    {"symbol": "XLM", "name": "Stellar", "coingecko_id": "stellar"},
    {"symbol": "ICP", "name": "Internet Computer", "coingecko_id": "internet-computer"},
    {"symbol": "VET", "name": "VeChain", "coingecko_id": "vechain"},
    {"symbol": "RUNE", "name": "THORChain", "coingecko_id": "thorchain"},
    {"symbol": "STX", "name": "Stacks", "coingecko_id": "blockstack"},
    {"symbol": "EGLD", "name": "MultiversX", "coingecko_id": "elrond-erd-2"},
    {"symbol": "FLOW", "name": "Flow", "coingecko_id": "flow"},
    {"symbol": "THETA", "name": "Theta Network", "coingecko_id": "theta-token"},
    {"symbol": "QNT", "name": "Quant", "coingecko_id": "quant-network"},
    {"symbol": "FET", "name": "Fetch.ai", "coingecko_id": "fetch-ai"},
    {"symbol": "AGIX", "name": "SingularityNET", "coingecko_id": "singularitynet"},
    {"symbol": "WLD", "name": "Worldcoin", "coingecko_id": "worldcoin-wld"},
    {"symbol": "JUP", "name": "Jupiter", "coingecko_id": "jupiter-exchange-solana"},
    {"symbol": "PYTH", "name": "Pyth Network", "coingecko_id": "pyth-network"},
    {"symbol": "TRX", "name": "TRON", "coingecko_id": "tron"},
    {"symbol": "TON", "name": "Toncoin", "coingecko_id": "the-open-network"},
    {"symbol": "ETC", "name": "Ethereum Classic", "coingecko_id": "ethereum-classic"},
    {"symbol": "BCH", "name": "Bitcoin Cash", "coingecko_id": "bitcoin-cash"},
    {"symbol": "DYDX", "name": "dYdX", "coingecko_id": "dydx"},
    {"symbol": "APE", "name": "ApeCoin", "coingecko_id": "apecoin"},
    {"symbol": "CRO", "name": "Cronos", "coingecko_id": "crypto-com-chain"},
    {"symbol": "COMP", "name": "Compound", "coingecko_id": "compound-governance-token"},
    {"symbol": "SNX", "name": "Synthetix", "coingecko_id": "havven"},
    {"symbol": "BAL", "name": "Balancer", "coingecko_id": "balancer"},
    {"symbol": "1INCH", "name": "1inch Network", "coingecko_id": "1inch"},
    {"symbol": "SUSHI", "name": "SushiSwap", "coingecko_id": "sushi"},
    {"symbol": "YFI", "name": "yearn.finance", "coingecko_id": "yearn-finance"},
    {"symbol": "ZRX", "name": "0x Protocol", "coingecko_id": "0x"},
    {"symbol": "BAT", "name": "Basic Attention Token", "coingecko_id": "basic-attention-token"},
    {"symbol": "ENJ", "name": "Enjin Coin", "coingecko_id": "enjincoin"},
    {"symbol": "CHZ", "name": "Chiliz", "coingecko_id": "chiliz"},
    {"symbol": "GALA", "name": "Gala", "coingecko_id": "gala"},
    {"symbol": "ROSE", "name": "Oasis Network", "coingecko_id": "oasis-network"},
    {"symbol": "ZIL", "name": "Zilliqa", "coingecko_id": "zilliqa"},
    {"symbol": "IOTA", "name": "IOTA", "coingecko_id": "iota"},
    {"symbol": "XTZ", "name": "Tezos", "coingecko_id": "tezos"},
    {"symbol": "EOS", "name": "EOS", "coingecko_id": "eos"},
    {"symbol": "NEO", "name": "Neo", "coingecko_id": "neo"},
    {"symbol": "KAVA", "name": "Kava", "coingecko_id": "kava"},
    {"symbol": "PENDLE", "name": "Pendle", "coingecko_id": "pendle"},
    {"symbol": "TRB", "name": "Tellor", "coingecko_id": "tellor"},
    {"symbol": "OCEAN", "name": "Ocean Protocol", "coingecko_id": "ocean-protocol"},
    {"symbol": "IOTX", "name": "IoTeX", "coingecko_id": "iotex"},
    {"symbol": "SKL", "name": "SKALE Network", "coingecko_id": "skale"},
    {"symbol": "CELO", "name": "Celo", "coingecko_id": "celo"},
    {"symbol": "ONE", "name": "Harmony", "coingecko_id": "harmony"},
    {"symbol": "KDA", "name": "Kadena", "coingecko_id": "kadena"},
    {"symbol": "OSMO", "name": "Osmosis", "coingecko_id": "osmosis"},
    {"symbol": "AXL", "name": "Axelar", "coingecko_id": "axelar"},
    {"symbol": "MINA", "name": "Mina Protocol", "coingecko_id": "mina-protocol"},
    {"symbol": "CFX", "name": "Conflux", "coingecko_id": "conflux-token"},
    {"symbol": "BLUR", "name": "Blur", "coingecko_id": "blur"},
    {"symbol": "MASK", "name": "Mask Network", "coingecko_id": "mask-network"},
    {"symbol": "GMX", "name": "GMX", "coingecko_id": "gmx"},
    {"symbol": "SSV", "name": "ssv.network", "coingecko_id": "ssv-network"},
    {"symbol": "RDNT", "name": "Radiant Capital", "coingecko_id": "radiant-capital"},
    {"symbol": "KAS", "name": "Kaspa", "coingecko_id": "kaspa"},
]

# ═══════════════════════════════════════════════
# FOREX PAIRS
# ═══════════════════════════════════════════════
FOREX = [
    {"symbol": "EUR/USD", "name": "Euro / US Dollar"},
    {"symbol": "GBP/USD", "name": "British Pound / US Dollar"},
    {"symbol": "USD/JPY", "name": "US Dollar / Japanese Yen"},
    {"symbol": "AUD/USD", "name": "Australian Dollar / US Dollar"},
    {"symbol": "USD/CAD", "name": "US Dollar / Canadian Dollar"},
    {"symbol": "USD/CHF", "name": "US Dollar / Swiss Franc"},
    {"symbol": "NZD/USD", "name": "New Zealand Dollar / US Dollar"},
    {"symbol": "EUR/GBP", "name": "Euro / British Pound"},
    {"symbol": "EUR/JPY", "name": "Euro / Japanese Yen"},
    {"symbol": "GBP/JPY", "name": "British Pound / Japanese Yen"},
    {"symbol": "AUD/JPY", "name": "Australian Dollar / Japanese Yen"},
    {"symbol": "EUR/AUD", "name": "Euro / Australian Dollar"},
    {"symbol": "USD/BRL", "name": "US Dollar / Brazilian Real"},
    {"symbol": "USD/MXN", "name": "US Dollar / Mexican Peso"},
    {"symbol": "USD/ZAR", "name": "US Dollar / South African Rand"},
    {"symbol": "USD/TRY", "name": "US Dollar / Turkish Lira"},
    {"symbol": "USD/INR", "name": "US Dollar / Indian Rupee"},
    {"symbol": "USD/CNY", "name": "US Dollar / Chinese Yuan"},
    {"symbol": "USD/SGD", "name": "US Dollar / Singapore Dollar"},
    {"symbol": "USD/HKD", "name": "US Dollar / Hong Kong Dollar"},
    {"symbol": "EUR/CHF", "name": "Euro / Swiss Franc"},
    {"symbol": "GBP/AUD", "name": "British Pound / Australian Dollar"},
    {"symbol": "AUD/NZD", "name": "Australian Dollar / New Zealand Dollar"},
    {"symbol": "USD/NOK", "name": "US Dollar / Norwegian Krone"},
    {"symbol": "USD/SEK", "name": "US Dollar / Swedish Krona"},
]

# ═══════════════════════════════════════════════
# COMMODITIES
# ═══════════════════════════════════════════════
COMMODITIES = [
    {"symbol": "XAU/USD", "name": "Gold", "unit": "per troy ounce"},
    {"symbol": "XAG/USD", "name": "Silver", "unit": "per troy ounce"},
    {"symbol": "XPT/USD", "name": "Platinum", "unit": "per troy ounce"},
    {"symbol": "XPD/USD", "name": "Palladium", "unit": "per troy ounce"},
    {"symbol": "CL", "name": "Crude Oil WTI", "unit": "per barrel"},
    {"symbol": "BZ", "name": "Brent Crude Oil", "unit": "per barrel"},
    {"symbol": "NG", "name": "Natural Gas", "unit": "per MMBtu"},
    {"symbol": "HG", "name": "Copper", "unit": "per pound"},
    {"symbol": "ZC", "name": "Corn", "unit": "per bushel"},
    {"symbol": "ZW", "name": "Wheat", "unit": "per bushel"},
    {"symbol": "ZS", "name": "Soybeans", "unit": "per bushel"},
    {"symbol": "KC", "name": "Coffee", "unit": "per pound"},
    {"symbol": "CT", "name": "Cotton", "unit": "per pound"},
    {"symbol": "SB", "name": "Sugar", "unit": "per pound"},
    {"symbol": "CC", "name": "Cocoa", "unit": "per metric ton"},
]

# ═══════════════════════════════════════════════
# INDICES
# ═══════════════════════════════════════════════
INDICES = [
    {"symbol": "SPX", "name": "S&P 500"},
    {"symbol": "NDX", "name": "NASDAQ 100"},
    {"symbol": "DJI", "name": "Dow Jones Industrial"},
    {"symbol": "RUT", "name": "Russell 2000"},
    {"symbol": "VIX", "name": "CBOE Volatility Index"},
    {"symbol": "FTSE", "name": "FTSE 100 (London)"},
    {"symbol": "DAX", "name": "DAX 40 (Frankfurt)"},
    {"symbol": "CAC", "name": "CAC 40 (Paris)"},
    {"symbol": "NIKKEI", "name": "Nikkei 225 (Tokyo)"},
    {"symbol": "HSI", "name": "Hang Seng (Hong Kong)"},
    {"symbol": "SSEC", "name": "Shanghai Composite"},
    {"symbol": "KOSPI", "name": "KOSPI (Seoul)"},
    {"symbol": "ASX200", "name": "S&P/ASX 200 (Sydney)"},
    {"symbol": "IBOV", "name": "Bovespa (Sao Paulo)"},
    {"symbol": "SENSEX", "name": "BSE SENSEX (Mumbai)"},
    {"symbol": "TSX", "name": "TSX Composite (Toronto)"},
    {"symbol": "STOXX50", "name": "Euro Stoxx 50"},
    {"symbol": "TWII", "name": "TAIEX (Taipei)"},
]


def get_full_universe():
    """Returns the complete asset universe with counts."""
    all_assets = []
    for a in US_STOCKS:
        all_assets.append({**a, "type": "stock", "market": "US"})
    for a in INTERNATIONAL_STOCKS:
        all_assets.append({**a, "type": "stock", "market": "International"})
    for a in ETFS:
        all_assets.append({**a, "type": "etf", "market": "US"})
    for a in CRYPTO:
        all_assets.append({**a, "type": "crypto", "market": "Global"})
    for a in FOREX:
        all_assets.append({**a, "type": "forex", "market": "Global"})
    for a in COMMODITIES:
        all_assets.append({**a, "type": "commodity", "market": "Global"})
    for a in INDICES:
        all_assets.append({**a, "type": "index", "market": "Global"})

    return {
        "assets": all_assets,
        "counts": {
            "us_stocks": len(US_STOCKS),
            "international_stocks": len(INTERNATIONAL_STOCKS),
            "etfs": len(ETFS),
            "crypto": len(CRYPTO),
            "forex": len(FOREX),
            "commodities": len(COMMODITIES),
            "indices": len(INDICES),
            "total": len(all_assets),
        }
    }


def search_universe(query: str, asset_type: str = None, limit: int = 30):
    """Search the asset universe by symbol or name."""
    q = query.upper()
    universe = get_full_universe()["assets"]
    results = []
    for a in universe:
        if asset_type and a.get("type") != asset_type:
            continue
        if q in a.get("symbol", "").upper() or q in a.get("name", "").upper():
            results.append(a)
    return results[:limit]
