"""
JARVIS PDF Report Generator
=============================
Generates professional PDF executive reports.
"""

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import Response
from pydantic import BaseModel
from typing import Dict, Optional
from datetime import datetime, timezone
import logging
import io

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/export", tags=["export"])


class PDFRequest(BaseModel):
    analysis_data: Dict
    include_candles: bool = False


@router.post("/pdf")
async def export_pdf(req: PDFRequest):
    """Generate a professional PDF executive report."""
    try:
        from fpdf import FPDF

        data = req.analysis_data
        report = data.get("report", {})
        steps = data.get("steps", {})
        tech = steps.get("technical_analysis", {})
        struct = steps.get("market_structure", {})
        mc = steps.get("monte_carlo", {})
        risk = steps.get("risk_model", {})
        regime = steps.get("regime_detection", {})
        manip = steps.get("manipulation_detection", {})
        signal = report.get("signal_summary", {})

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=20)

        # --- Cover Page ---
        pdf.add_page()
        pdf.set_fill_color(13, 13, 13)
        pdf.rect(0, 0, 210, 297, 'F')

        pdf.set_text_color(207, 174, 70)
        pdf.set_font("Helvetica", "B", 32)
        pdf.cell(0, 50, "", ln=True)
        pdf.cell(0, 15, "AUREOS AI", ln=True, align="C")

        pdf.set_font("Helvetica", "", 12)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 10, "JARVIS Intelligence Engine", ln=True, align="C")
        pdf.cell(0, 20, "", ln=True)

        pdf.set_font("Helvetica", "B", 24)
        pdf.set_text_color(242, 242, 242)
        pdf.cell(0, 12, "Executive Analysis Report", ln=True, align="C")
        pdf.cell(0, 10, "", ln=True)

        pdf.set_font("Helvetica", "B", 20)
        pdf.set_text_color(207, 174, 70)
        symbol = data.get("symbol", "N/A")
        name = data.get("name", symbol)
        pdf.cell(0, 12, f"{name} ({symbol.upper()})", ln=True, align="C")

        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 10, f"Generated: {datetime.now(timezone.utc).strftime('%B %d, %Y at %H:%M UTC')}", ln=True, align="C")
        pdf.cell(0, 6, f"Asset Type: {data.get('asset_type', 'N/A').upper()} | Timeframe: {data.get('timeframe', '4H')}", ln=True, align="C")

        pdf.cell(0, 30, "", ln=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 6, "Property of Aureos Corporation. All rights reserved.", ln=True, align="C")
        pdf.cell(0, 6, "This report is generated by JARVIS and is for informational purposes only.", ln=True, align="C")

        # --- Signal Summary Page ---
        pdf.add_page()
        pdf.set_fill_color(255, 255, 255)
        _section_header(pdf, "SIGNAL SUMMARY")

        direction = signal.get("direction", "HOLD")
        confidence = signal.get("confidence", 0)
        strength = signal.get("strength", "weak")

        pdf.set_font("Helvetica", "B", 28)
        color = (0, 230, 118) if direction == "BUY" else (255, 82, 82) if direction == "SELL" else (150, 150, 150)
        pdf.set_text_color(*color)
        pdf.cell(0, 15, f"{direction}", ln=True, align="C")

        pdf.set_font("Helvetica", "", 14)
        pdf.set_text_color(80, 80, 80)
        pdf.cell(0, 10, f"Confidence: {confidence}% | Strength: {strength.upper()}", ln=True, align="C")
        pdf.cell(0, 10, "", ln=True)

        # Probabilities
        _section_header(pdf, "SCENARIO PROBABILITIES")
        scenarios = report.get("signal_summary", {})
        _kv_row(pdf, "Bullish Probability", f"{scenarios.get('bullish_probability', 0)}%")
        _kv_row(pdf, "Bearish Probability", f"{scenarios.get('bearish_probability', 0)}%")
        _kv_row(pdf, "Sideways Probability", f"{scenarios.get('sideways_probability', 0)}%")
        pdf.cell(0, 8, "", ln=True)

        # Price
        _section_header(pdf, "MARKET DATA")
        price = data.get("price", 0)
        _kv_row(pdf, "Current Price", f"${price:,.2f}" if price < 100000 else f"${price:,.0f}")
        md = steps.get("market_data", {})
        _kv_row(pdf, "Change", f"{md.get('change_percent', 0):.2f}%")
        _kv_row(pdf, "Volume", f"{md.get('volume', 0):,.0f}")
        _kv_row(pdf, "Data Source", md.get("source", "N/A"))
        _kv_row(pdf, "Candles Analyzed", str(md.get("candle_count", 0)))
        pdf.cell(0, 8, "", ln=True)

        # --- Technical Analysis Page ---
        pdf.add_page()
        _section_header(pdf, "TECHNICAL ANALYSIS")
        _kv_row(pdf, "RSI (14)", f"{tech.get('rsi', 50)} ({tech.get('rsi_signal', 'neutral')})")
        macd = tech.get("macd", {})
        _kv_row(pdf, "MACD Crossover", macd.get("crossover", "neutral"))
        _kv_row(pdf, "Trend", tech.get("trend", "sideways"))
        mas = tech.get("moving_averages", {})
        _kv_row(pdf, "SMA 20", f"{mas.get('sma_20', 0):,.4f}")
        _kv_row(pdf, "SMA 50", f"{mas.get('sma_50', 0):,.4f}")
        _kv_row(pdf, "Price vs SMA20", mas.get("price_vs_sma20", "N/A"))
        _kv_row(pdf, "Golden Cross", "Yes" if mas.get("golden_cross") else "No")
        bb = tech.get("bollinger_bands", {})
        _kv_row(pdf, "Bollinger Position", bb.get("position", "middle"))
        _kv_row(pdf, "ATR", f"{tech.get('atr', 0):.4f} ({tech.get('atr_percent', 0)}%)")
        _kv_row(pdf, "Volume Trend", tech.get("volume_trend", "stable"))
        pdf.cell(0, 8, "", ln=True)

        # Market Structure
        _section_header(pdf, "MARKET STRUCTURE")
        _kv_row(pdf, "Bias", struct.get("bias", "neutral"))
        _kv_row(pdf, "Pattern", struct.get("pattern", "N/A"))
        breakout = struct.get("breakout", {})
        if breakout.get("detected"):
            _kv_row(pdf, "Breakout", f"{breakout.get('type', 'N/A')}")
        pdf.cell(0, 8, "", ln=True)

        # Monte Carlo
        _section_header(pdf, "MONTE CARLO SIMULATION")
        _kv_row(pdf, "Win Probability", f"{mc.get('win_probability', 50)}%")
        _kv_row(pdf, "Expected Return", f"{mc.get('expected_return_pct', 0)}%")
        _kv_row(pdf, "Max Upside (95th)", f"{mc.get('max_upside_pct', 0)}%")
        _kv_row(pdf, "Max Drawdown (5th)", f"{mc.get('max_drawdown_pct', 0)}%")
        _kv_row(pdf, "Simulations", str(mc.get("simulations", 5000)))
        pdf.cell(0, 8, "", ln=True)

        # --- Risk & Regime Page ---
        pdf.add_page()
        _section_header(pdf, "RISK ANALYSIS")
        _kv_row(pdf, "Risk Score", f"{risk.get('risk_score', 50)}/100")
        _kv_row(pdf, "Risk Level", risk.get("risk_level", "moderate").upper())
        _kv_row(pdf, "VaR (95%)", f"{risk.get('var_95', 0):.2f}%")
        _kv_row(pdf, "Max Drawdown", f"{risk.get('max_drawdown', 0):.2f}%")
        _kv_row(pdf, "Recommended Size", f"{risk.get('recommended_position_size', 2)}%")
        sl = risk.get("stop_loss", {})
        if sl:
            _kv_row(pdf, "Stop Loss (Tight)", f"${sl.get('tight', 0):,.2f}")
            _kv_row(pdf, "Stop Loss (Normal)", f"${sl.get('normal', 0):,.2f}")
        pdf.cell(0, 8, "", ln=True)

        _section_header(pdf, "MARKET REGIME")
        _kv_row(pdf, "Trend Regime", regime.get("trend_regime", "N/A"))
        _kv_row(pdf, "Volatility Regime", regime.get("volatility_regime", "N/A"))
        mp = regime.get("market_phase", {})
        _kv_row(pdf, "Market Phase", mp.get("phase", "unknown"))
        _kv_row(pdf, "Phase Description", mp.get("description", "N/A"))
        pdf.cell(0, 8, "", ln=True)

        _section_header(pdf, "MANIPULATION DETECTION")
        _kv_row(pdf, "Manipulation Score", f"{manip.get('manipulation_score', 0)}/100")
        _kv_row(pdf, "Risk Level", manip.get("risk_level", "N/A"))
        _kv_row(pdf, "Events Detected", str(manip.get("total_events_detected", 0)))
        warnings = manip.get("warnings", [])
        for w in warnings[:3]:
            _kv_row(pdf, "Warning", w)

        # --- Disclaimer ---
        pdf.cell(0, 20, "", ln=True)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.multi_cell(0, 4, "DISCLAIMER: This report is generated by JARVIS AI engine for informational purposes only. It does not constitute financial advice. Past performance does not guarantee future results. Trading involves substantial risk of loss. Aureos Corporation is not responsible for any trading decisions made based on this report.")

        # Output
        pdf_bytes = pdf.output()
        filename = f"Aureos_Report_{symbol.upper()}_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf"

        return Response(
            content=bytes(pdf_bytes),
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename={filename}"},
        )

    except Exception as e:
        logger.error(f"PDF export error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


def _section_header(pdf, title):
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(207, 174, 70)
    pdf.cell(0, 10, title, ln=True)
    pdf.set_draw_color(207, 174, 70)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.cell(0, 4, "", ln=True)


def _kv_row(pdf, key, value):
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(70, 7, key, ln=False)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 7, str(value), ln=True)
