import React, { createContext, useContext, useState, useCallback } from 'react';

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be inside LanguageProvider');
  return ctx;
};

export const LANGUAGES = [
  { code: 'pt', label: 'Portugues', flag: 'BR' },
  { code: 'en', label: 'English', flag: 'US' },
  { code: 'es', label: 'Espanol', flag: 'ES' },
  { code: 'fr', label: 'Francais', flag: 'FR' },
  { code: 'de', label: 'Deutsch', flag: 'DE' },
  { code: 'zh', label: 'Chinese', flag: 'CN' },
  { code: 'ja', label: 'Japanese', flag: 'JP' },
  { code: 'ko', label: 'Korean', flag: 'KR' },
  { code: 'ar', label: 'Arabic', flag: 'SA' },
];

const translations = {
  pt: {
    'nav.intelligence': 'Inteligencia',
    'nav.analysis': 'Analise',
    'nav.trading': 'Trading',
    'nav.unfair_advantage': 'Vantagem Injusta',
    'nav.system': 'Sistema',
    'nav.command_center': 'Centro de Comando',
    'nav.jarvis_hub': 'JARVIS Hub',
    'nav.intel_terminal': 'Terminal Intel',
    'nav.intel_mode': 'Modo Intel',
    'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica',
    'nav.deep_analysis': 'Analise Profunda',
    'nav.market_scanner': 'Scanner de Mercado',
    'nav.signal_timeline': 'Timeline de Sinais',
    'nav.capital_flow': 'Fluxo de Capital',
    'nav.market_dna': 'DNA do Mercado',
    'nav.sentiment': 'Sentimento',
    'nav.weekly_digest': 'Resumo Semanal',
    'nav.my_portfolio': 'Meu Portfolio',
    'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading',
    'nav.trade_simulator': 'Simulador de Trade',
    'nav.decision_replay': 'Replay de Decisao',
    'nav.trader_dna': 'DNA do Trader',
    'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Intel Global',
    'nav.opp_scanner': 'Scanner de Opp.',
    'nav.top_traders': 'Top Traders',
    'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.share_cards': 'Share Cards',
    'nav.evolution': 'Evolution',
    'nav.strategy_creator': 'Create Strategy',
    'nav.aureos_score': 'Aureos Score',
    'nav.aureos_tokens': 'Aureos Tokens',
    'nav.track_record': 'Track Record',
    'nav.settings': 'Configuracoes',
    'nav.alpha_radar': 'Alpha Radar',
    'nav.market_narrative': 'Narrativa',
    'nav.copy_trading': 'Copy Trading',
    'nav.liquidity_map': 'Mapa Liquidez',
    'nav.second_brain': 'Second Brain',
    'nav.daily_missions': 'Missoes Diarias',
    'nav.correlation': 'Correlacao',
    'nav.econ_calendar': 'Calendario Econ.',
    'nav.trade_journal': 'Diario de Trades',
    'nav.quiz': 'Quiz',
    'nav.referral': 'Indicacao',
    'nav.ecosystem': 'Ecossistema',
    'nav.decision_engine': 'Motor de Decisao',
    'nav.trust_dashboard': 'Transparencia',
    'dashboard.greeting_morning': 'Bom dia',
    'dashboard.greeting_afternoon': 'Boa tarde',
    'dashboard.greeting_evening': 'Boa noite',
    'dashboard.market_pulse': 'PULSO DO MERCADO',
    'dashboard.my_portfolio': 'MEU PORTFOLIO',
    'dashboard.intelligence': 'INTELIGENCIA DO DIA',
    'dashboard.global_markets': 'MERCADOS GLOBAIS',
    'common.refresh': 'Atualizar',
    'common.loading': 'Carregando...',
    'common.subscribe': 'Assinar',
    'common.view_all': 'Ver Tudo',
    'common.narrate': 'Narrar com JARVIS',
    'common.narrating': 'Narrando...',
    'common.search': 'Buscar ativos, comandos ou pergunte ao JARVIS...',
    'alpha.title': 'Alpha',
    'alpha.subtitle': 'Radar',
    'alpha.description': 'Onde esta a vantagem agora? Top oportunidades globais com score + probabilidade.',
    'alpha.scan': 'Escanear Alpha',
    'alpha.scanning': 'Escaneando...',
    'narrative.title': 'Narrativa do',
    'narrative.subtitle': 'Mercado',
    'narrative.description': 'JARVIS narra a historia do mercado em tempo real.',
    'narrative.generate': 'Gerar Narrativa',
    'narrative.generating': 'Gerando...',
    'copy.title': 'Copy Trading', 'copy.subtitle': 'Inteligente', 'copy.desc': 'Traders filtrados por IA. Apenas traders consistentes e de baixo risco. JARVIS adapta ao seu DNA.',
    'copy.ai_rating': 'Rating IA', 'copy.win_rate': 'Taxa Vitoria', 'copy.pnl': 'P&L', 'copy.risk': 'Risco', 'copy.btn': 'Copiar',
    'liquidity.title': 'Mapa de', 'liquidity.subtitle': 'Liquidez', 'liquidity.desc': 'Para onde o dinheiro esta fluindo?',
    'liquidity.capital_flows': 'Fluxos de Capital', 'liquidity.sector_flows': 'Fluxos por Setor', 'liquidity.zones': 'Zonas de Liquidez',
    'brain.title': 'Aureos', 'brain.subtitle': 'Second Brain', 'brain.desc': 'JARVIS lembra de tudo. Sua memoria completa de trading.',
    'brain.total_decisions': 'Total Decisoes', 'brain.win_rate': 'Taxa Vitoria', 'brain.total_pnl': 'P&L Total', 'brain.score': 'Aureos Score',
    'brain.patterns': 'Padroes Detectados', 'brain.insights': 'Insights do JARVIS', 'brain.evolution': 'Evolucao Mensal', 'brain.dna_profile': 'Perfil DNA',
    'brain.no_insights': 'Execute mais trades para o JARVIS aprender seus padroes.',
    'brain.best_day': 'Melhor Dia', 'brain.worst_day': 'Pior Dia', 'brain.best_asset': 'Melhor Ativo', 'brain.worst_asset': 'Pior Ativo', 'brain.asset_perf': 'Performance por Ativo',
    'missions.title': 'Missoes', 'missions.subtitle': 'Diarias', 'missions.desc': 'Complete missoes para ganhar Aureos Tokens',
    'missions.total_reward': 'Recompensa Total', 'missions.completed': 'completadas', 'missions.complete_btn': 'Completar',
    'journal.title': 'Diario de', 'journal.subtitle': 'Trades IA', 'journal.desc': 'JARVIS analisa cada trade com nota + insight',
    'journal.empty': 'Nenhum trade fechado. Seu diario sera construido automaticamente.',
    'corr.title': 'Matriz de', 'corr.subtitle': 'Correlacao', 'corr.desc': 'Correlacoes em tempo real entre os principais ativos',
    'calendar.title': 'Calendario', 'calendar.subtitle': 'Economico', 'calendar.desc': 'Eventos com analise de impacto por JARVIS',
    'calendar.ai_impact': 'Analise de Impacto JARVIS', 'calendar.previous': 'Anterior', 'calendar.forecast': 'Previsao',
    'quiz.title': 'Quiz de', 'quiz.subtitle': 'Trading', 'quiz.desc': 'Teste seu conhecimento. Ganhe 1 AT por resposta correta.',
    'quiz.submit': 'Enviar Quiz', 'quiz.new': 'Novo Quiz', 'quiz.earned': 'AT ganhos', 'quiz.correct': 'corretas',
    'referral.title': 'Programa de', 'referral.subtitle': 'Indicacao', 'referral.desc': 'Convide amigos.',
    'referral.code': 'Seu Codigo de Indicacao', 'referral.referrals': 'Indicacoes', 'referral.tokens_earned': 'Tokens Ganhos',
    'referral.how': 'Como funciona', 'referral.step1': 'Compartilhe seu codigo com amigos', 'referral.step2': 'Eles se cadastram com seu codigo',
    'referral.twitter': 'Compartilhar no Twitter', 'referral.whatsapp': 'Compartilhar no WhatsApp',
    'decision.title': 'Motor de', 'decision.subtitle': 'Decisao', 'decision.desc': 'BUY / SELL / HOLD para qualquer ativo. Analise multi-fator com probabilidade e gestao de risco.',
    'decision.search_placeholder': 'Pesquisar qualquer ativo (BTC, AAPL, EUR/USD...)',
    'decision.analysis_complete': 'Analise completa:', 'decision.error': 'Erro ao analisar ativo',
    'decision.confidence': 'confianca', 'decision.probability': 'Probabilidade', 'decision.entry': 'Entrada',
    'decision.target': 'Alvo', 'decision.stop_loss': 'Stop Loss', 'decision.risk_reward': 'Risco/Retorno',
    'decision.why': 'Por Que Este Trade?', 'decision.market_structure': 'Estrutura', 'decision.liquidity': 'Liquidez',
    'decision.volatility': 'Volatilidade', 'decision.sentiment': 'Sentimento', 'decision.quant_signals': 'Sinais Quantitativos',
    'decision.momentum': 'Momento', 'decision.reasoning': 'Raciocinio da IA', 'decision.factor_scores': 'Scores por Fator',
    'decision.total_score': 'Score Total', 'decision.top_opp': 'Top Oportunidades',
    'trust.title': 'Performance', 'trust.subtitle': 'Publica', 'trust.desc': 'Transparencia total. Cada trade, cada sinal, verificavel.',
    'trust.total_trades': 'Total Trades', 'trust.win_rate': 'Taxa Vitoria', 'trust.total_pnl': 'P&L Total',
    'trust.max_drawdown': 'Max Drawdown', 'trust.risk_reward': 'Risco/Retorno', 'trust.sharpe': 'Sharpe',
    'trust.users': 'Usuarios', 'trust.strategies': 'Estrategias', 'trust.assets_covered': 'Ativos',
    'trust.signal_accuracy': 'Acuracia Sinais', 'trust.total_signals': 'Total Sinais',
    'trust.monthly_perf': 'Performance Mensal', 'trust.track_record': 'Track Record Verificado',
    'trust.current_streak': 'Sequencia Atual', 'trust.accuracy_by_class': 'Acuracia por Classe',
    'trust.top_strategies': 'Top Estrategias', 'trust.no_data': 'Sem dados', 'trust.no_signals': 'Nenhum sinal registrado ainda.',
    'fusion.title': 'JARVIS GLOBAL FUSION',
    'fusion.subtitle': 'Cruzamento de Dados Mundiais — Notícias × Preços × Geopolítica → Sinais',
    'fusion.live': 'AO VIVO',
    'fusion.last_updated': 'Atualizado há {s}s',
    'fusion.refresh': 'Atualizar',
    'fusion.events_captured': 'Eventos Capturados',
    'fusion.assets_analyzed': 'Ativos Analisados',
    'fusion.active_signals': 'Sinais Ativos',
    'fusion.macro_regime': 'Regime Macro',
    'fusion.executive_summary': 'RESUMO EXECUTIVO JARVIS',
    'fusion.cross_asset_signals': 'SINAIS CROSS-ASSET',
    'fusion.asset_impact': 'MAPA DE IMPACTO DE ATIVOS',
    'fusion.correlation': 'CORRELAÇÃO CROSS-ASSET EM TEMPO REAL',
    'fusion.market_temp_hot': 'QUENTE',
    'fusion.market_temp_warm': 'MORNO',
    'fusion.market_temp_cool': 'FRIO',
    'fusion.signal_buy': 'COMPRAR',
    'fusion.signal_sell': 'VENDER',
    'fusion.signal_hold': 'MANTER',
    'fusion.signal_watch': 'OBSERVAR',
    'fusion.confidence': 'Confiança',
    'fusion.trade_ideas': 'Ideias de Trade',
    'fusion.impact_high': 'ALTO',
    'fusion.impact_medium': 'MÉDIO',
    'fusion.impact_low': 'BAIXO',
    'fusion.bias_bullish': 'ALTISTA',
    'fusion.bias_bearish': 'BAIXISTA',
    'fusion.bias_neutral': 'NEUTRO',
    'fusion.key_drivers': 'Fatores-Chave',
    'fusion.risk_level': 'Risco',
    'fusion.expand': 'Expandir',
    'fusion.collapse': 'Recolher',
    'fusion.no_events': 'Nenhum evento capturado ainda',
    'fusion.loading': 'Sincronizando dados globais...',
    'fusion.error_retry': 'Tentar Novamente',
    'fusion.analyze_event': 'Analisar Evento',
    'fusion.analyze_placeholder': 'Cole qualquer manchete para analisar o impacto no mercado...',
    'fusion.regime_risk_on': 'RISCO ATIVO',
    'fusion.regime_risk_off': 'RISCO OFF',
    'fusion.regime_stagflation': 'ESTAGFLAÇÃO',
    'fusion.regime_goldilocks': 'GOLDILOCKS',
    'fusion.regime_crisis': 'CRISE',
    'fusion.filter_all': 'TODOS',
    'fusion.filter_geo': 'GEOPOLÍTICO',
    'fusion.filter_macro': 'MACRO',
    'fusion.filter_crypto': 'CRYPTO',
    'fusion.filter_equity': 'AÇÕES',
    'fusion.filter_commodity': 'COMMODITY',
    'fusion.filter_forex': 'FOREX',
    'fusion.source': 'Fonte',
    'fusion.affected': 'Afetados',
    'fusion.divergence': 'DIVERGÊNCIA',
    'fusion.corr_high_pos': 'Alta correlação positiva',
    'fusion.corr_high_neg': 'Alta correlação inversa',
    'fusion.corr_low': 'Baixa correlação',
    'labs.title': 'AUREOS LABS',
    'labs.subtitle': 'Features em desenvolvimento ativo. Cada uma será lançada conforme atingirmos os marcos de qualidade.',
    'labs.pipeline': 'features no pipeline',
    'labs.q2': 'Q2 2026',
    'labs.q3': 'Q3 2026',
    'labs.q4': 'Q4 2026',
    'labs.footer': 'Cada feature do Labs já possui backend funcional — estamos refinando UX antes do lançamento público.',
    'labs.tagline': '30+ features · 1 core product · 0 compromissos com qualidade',
    'jarvis.live': 'AO VIVO',
    'jarvis.updated': 'Atualizado há {m} min',
    'jarvis.refresh': 'Atualizar',
    'jarvis.listen': 'Ouvir',
    'jarvis.stop': 'Parar',
    'jarvis.read_more': 'Ler mais',
    'jarvis.read_less': 'Ler menos',
    'jarvis.geopolitical_events': 'EVENTOS GEOPOLÍTICOS',
    'jarvis.predictions': 'PREVISÕES IA',
    'jarvis.confidence': 'confiança',
    'jarvis.loading': 'JARVIS está analisando eventos globais...',
    'jarvis.error': 'Não foi possível conectar ao JARVIS',
    'jarvis.retry': 'Tentar Novamente',
    'jarvis.impact_high': 'ALTO IMPACTO',
    'jarvis.impact_medium': 'MÉDIO IMPACTO',
    'jarvis.impact_low': 'BAIXO IMPACTO',
    'heatmap.title': 'Matriz de Correlação',
    'heatmap.tooltip_pair': '{a} / {b}',
    'heatmap.divergence_warning': 'DIVERGÊNCIA DE REGIME',
    'heatmap.legend_negative': 'Inversa Forte',
    'heatmap.legend_neutral': 'Sem Correlação',
    'heatmap.legend_positive': 'Positiva Forte',
    'nav.global_fusion': 'Global Fusion',
    'nav.my_signals': 'Meus Sinais',
    'nav.analyze_asset': 'Analisar Ativo',
    'nav.labs': 'Labs',
  },
  en: {
    'nav.intelligence': 'Intelligence',
    'nav.analysis': 'Analysis',
    'nav.trading': 'Trading',
    'nav.unfair_advantage': 'Unfair Advantage',
    'nav.system': 'System',
    'nav.command_center': 'Command Center',
    'nav.jarvis_hub': 'JARVIS Hub',
    'nav.intel_terminal': 'Intel Terminal',
    'nav.intel_mode': 'Intel Mode',
    'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica',
    'nav.deep_analysis': 'Deep Analysis',
    'nav.market_scanner': 'Market Scanner',
    'nav.signal_timeline': 'Signal Timeline',
    'nav.capital_flow': 'Capital Flow',
    'nav.market_dna': 'Market DNA',
    'nav.sentiment': 'Sentiment',
    'nav.weekly_digest': 'Weekly Digest',
    'nav.my_portfolio': 'My Portfolio',
    'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading',
    'nav.trade_simulator': 'Trade Simulator',
    'nav.decision_replay': 'Decision Replay',
    'nav.trader_dna': 'Trader DNA',
    'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Global Intel',
    'nav.opp_scanner': 'Opp Scanner',
    'nav.top_traders': 'Top Traders',
    'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.share_cards': 'Share Cards',
    'nav.evolution': 'Evolution',
    'nav.strategy_creator': 'Create Strategy',
    'nav.aureos_score': 'Aureos Score',
    'nav.aureos_tokens': 'Aureos Tokens',
    'nav.track_record': 'Track Record',
    'nav.settings': 'Settings',
    'nav.alpha_radar': 'Alpha Radar',
    'nav.market_narrative': 'Narrative',
    'nav.copy_trading': 'Copy Trading',
    'nav.liquidity_map': 'Liquidity Map',
    'nav.second_brain': 'Second Brain',
    'nav.daily_missions': 'Daily Missions',
    'nav.correlation': 'Correlation',
    'nav.econ_calendar': 'Economic Calendar',
    'nav.trade_journal': 'Trade Journal',
    'nav.quiz': 'Quiz',
    'nav.referral': 'Referral',
    'nav.ecosystem': 'Ecosystem',
    'nav.decision_engine': 'Decision Engine',
    'nav.trust_dashboard': 'Transparency',
    'dashboard.greeting_morning': 'Good morning',
    'dashboard.greeting_afternoon': 'Good afternoon',
    'dashboard.greeting_evening': 'Good evening',
    'dashboard.market_pulse': 'MARKET PULSE',
    'dashboard.my_portfolio': 'MY PORTFOLIO',
    'dashboard.intelligence': 'INTELLIGENCE OF THE DAY',
    'dashboard.global_markets': 'GLOBAL MARKETS',
    'common.refresh': 'Refresh',
    'common.loading': 'Loading...',
    'common.subscribe': 'Subscribe',
    'common.view_all': 'View All',
    'common.narrate': 'Narrate with JARVIS',
    'common.narrating': 'Narrating...',
    'common.search': 'Search assets, commands, or ask JARVIS...',
    'alpha.title': 'Alpha',
    'alpha.subtitle': 'Radar',
    'alpha.description': 'Where is the edge right now? Top global opportunities with score + probability.',
    'alpha.scan': 'Scan for Alpha',
    'alpha.scanning': 'Scanning...',
    'narrative.title': 'Market',
    'narrative.subtitle': 'Narrative',
    'narrative.description': 'JARVIS narrates the market story in real time.',
    'narrative.generate': 'Generate Narrative',
    'narrative.generating': 'Generating...',
    'copy.title': 'Copy Trading', 'copy.subtitle': 'Intelligent', 'copy.desc': 'AI-filtered traders. Only consistent, low-risk, high-score traders. JARVIS adapts to your DNA.',
    'copy.ai_rating': 'AI Rating', 'copy.win_rate': 'Win Rate', 'copy.pnl': 'P&L', 'copy.risk': 'Risk', 'copy.btn': 'Copy',
    'liquidity.title': 'Liquidity', 'liquidity.subtitle': 'Intelligence', 'liquidity.desc': 'Where is the money flowing?',
    'liquidity.capital_flows': 'Capital Flows', 'liquidity.sector_flows': 'Sector Flows', 'liquidity.zones': 'Liquidity Zones',
    'brain.title': 'Aureos', 'brain.subtitle': 'Second Brain', 'brain.desc': 'JARVIS remembers everything. Your complete trading memory.',
    'brain.total_decisions': 'Total Decisions', 'brain.win_rate': 'Win Rate', 'brain.total_pnl': 'Total P&L', 'brain.score': 'Aureos Score',
    'brain.patterns': 'Patterns Detected', 'brain.insights': 'JARVIS Insights', 'brain.evolution': 'Monthly Evolution', 'brain.dna_profile': 'DNA Profile',
    'brain.no_insights': 'Execute more trades so JARVIS can learn your patterns.',
    'brain.best_day': 'Best Day', 'brain.worst_day': 'Worst Day', 'brain.best_asset': 'Best Asset', 'brain.worst_asset': 'Worst Asset', 'brain.asset_perf': 'Asset Performance',
    'missions.title': 'Daily', 'missions.subtitle': 'Missions', 'missions.desc': 'Complete missions to earn Aureos Tokens',
    'missions.total_reward': 'Total Reward', 'missions.completed': 'completed', 'missions.complete_btn': 'Complete',
    'journal.title': 'AI Trade', 'journal.subtitle': 'Journal', 'journal.desc': 'JARVIS auto-analyzes every trade with grade + insight',
    'journal.empty': 'No closed trades yet. Your journal will build automatically.',
    'corr.title': 'Correlation', 'corr.subtitle': 'Matrix', 'corr.desc': 'Real-time correlations between major assets',
    'calendar.title': 'Economic', 'calendar.subtitle': 'Calendar', 'calendar.desc': 'Key events with AI impact analysis by JARVIS',
    'calendar.ai_impact': 'JARVIS AI Impact Analysis', 'calendar.previous': 'Previous', 'calendar.forecast': 'Forecast',
    'quiz.title': 'Trading', 'quiz.subtitle': 'Quiz', 'quiz.desc': 'Test your knowledge. Earn 1 AT per correct answer.',
    'quiz.submit': 'Submit Quiz', 'quiz.new': 'New Quiz', 'quiz.earned': 'AT earned', 'quiz.correct': 'correct',
    'referral.title': 'Referral', 'referral.subtitle': 'Program', 'referral.desc': 'Invite friends.',
    'referral.code': 'Your Referral Code', 'referral.referrals': 'Referrals', 'referral.tokens_earned': 'Tokens Earned',
    'referral.how': 'How it works', 'referral.step1': 'Share your unique code with friends', 'referral.step2': 'They sign up using your code',
    'referral.twitter': 'Share on Twitter', 'referral.whatsapp': 'Share on WhatsApp',
    'decision.title': 'Decision', 'decision.subtitle': 'Engine', 'decision.desc': 'BUY / SELL / HOLD for any asset. Multi-factor analysis with probability and risk management.',
    'decision.search_placeholder': 'Search any asset (BTC, AAPL, EUR/USD...)',
    'decision.analysis_complete': 'Analysis complete:', 'decision.error': 'Error analyzing asset',
    'decision.confidence': 'confidence', 'decision.probability': 'Probability', 'decision.entry': 'Entry',
    'decision.target': 'Target', 'decision.stop_loss': 'Stop Loss', 'decision.risk_reward': 'Risk/Reward',
    'decision.why': 'Why This Trade?', 'decision.market_structure': 'Structure', 'decision.liquidity': 'Liquidity',
    'decision.volatility': 'Volatility', 'decision.sentiment': 'Sentiment', 'decision.quant_signals': 'Quant Signals',
    'decision.momentum': 'Momentum', 'decision.reasoning': 'AI Reasoning', 'decision.factor_scores': 'Factor Scores',
    'decision.total_score': 'Total Score', 'decision.top_opp': 'Top Opportunities',
    'trust.title': 'Public', 'trust.subtitle': 'Performance', 'trust.desc': 'Total transparency. Every trade, every signal, verifiable.',
    'trust.total_trades': 'Total Trades', 'trust.win_rate': 'Win Rate', 'trust.total_pnl': 'Total P&L',
    'trust.max_drawdown': 'Max Drawdown', 'trust.risk_reward': 'Risk/Reward', 'trust.sharpe': 'Sharpe',
    'trust.users': 'Users', 'trust.strategies': 'Strategies', 'trust.assets_covered': 'Assets',
    'trust.signal_accuracy': 'Signal Accuracy', 'trust.total_signals': 'Total Signals',
    'trust.monthly_perf': 'Monthly Performance', 'trust.track_record': 'Verified Track Record',
    'trust.current_streak': 'Current Streak', 'trust.accuracy_by_class': 'Accuracy by Class',
    'trust.top_strategies': 'Top Strategies', 'trust.no_data': 'No data', 'trust.no_signals': 'No signals recorded yet.',
    'fusion.title': 'JARVIS GLOBAL FUSION',
    'fusion.subtitle': 'World Data Crossfeed — News × Prices × Geopolitics → Signals',
    'fusion.live': 'LIVE',
    'fusion.last_updated': 'Updated {s}s ago',
    'fusion.refresh': 'Refresh',
    'fusion.events_captured': 'Events Captured',
    'fusion.assets_analyzed': 'Assets Analyzed',
    'fusion.active_signals': 'Active Signals',
    'fusion.macro_regime': 'Macro Regime',
    'fusion.executive_summary': 'JARVIS EXECUTIVE SUMMARY',
    'fusion.cross_asset_signals': 'CROSS-ASSET SIGNALS',
    'fusion.asset_impact': 'ASSET IMPACT MAP',
    'fusion.correlation': 'REAL-TIME CROSS-ASSET CORRELATION',
    'fusion.market_temp_hot': 'HOT',
    'fusion.market_temp_warm': 'WARM',
    'fusion.market_temp_cool': 'COOL',
    'fusion.signal_buy': 'BUY',
    'fusion.signal_sell': 'SELL',
    'fusion.signal_hold': 'HOLD',
    'fusion.signal_watch': 'WATCH',
    'fusion.confidence': 'Confidence',
    'fusion.trade_ideas': 'Trade Ideas',
    'fusion.impact_high': 'HIGH',
    'fusion.impact_medium': 'MEDIUM',
    'fusion.impact_low': 'LOW',
    'fusion.bias_bullish': 'BULLISH',
    'fusion.bias_bearish': 'BEARISH',
    'fusion.bias_neutral': 'NEUTRAL',
    'fusion.key_drivers': 'Key Drivers',
    'fusion.risk_level': 'Risk',
    'fusion.expand': 'Expand',
    'fusion.collapse': 'Collapse',
    'fusion.no_events': 'No events captured yet',
    'fusion.loading': 'Synchronizing global data...',
    'fusion.error_retry': 'Retry',
    'fusion.analyze_event': 'Analyze Event',
    'fusion.analyze_placeholder': 'Paste any news headline to analyze market impact...',
    'fusion.regime_risk_on': 'RISK-ON',
    'fusion.regime_risk_off': 'RISK-OFF',
    'fusion.regime_stagflation': 'STAGFLATION',
    'fusion.regime_goldilocks': 'GOLDILOCKS',
    'fusion.regime_crisis': 'CRISIS',
    'fusion.filter_all': 'ALL',
    'fusion.filter_geo': 'GEOPOLITICAL',
    'fusion.filter_macro': 'MACRO',
    'fusion.filter_crypto': 'CRYPTO',
    'fusion.filter_equity': 'EQUITY',
    'fusion.filter_commodity': 'COMMODITY',
    'fusion.filter_forex': 'FOREX',
    'fusion.source': 'Source',
    'fusion.affected': 'Affected',
    'fusion.divergence': 'DIVERGENCE',
    'fusion.corr_high_pos': 'High positive correlation',
    'fusion.corr_high_neg': 'High inverse correlation',
    'fusion.corr_low': 'Low correlation',
    'labs.title': 'AUREOS LABS',
    'labs.subtitle': 'Features in active development. Each launches when quality standards are met.',
    'labs.pipeline': 'features in pipeline',
    'labs.q2': 'Q2 2026',
    'labs.q3': 'Q3 2026',
    'labs.q4': 'Q4 2026',
    'labs.footer': 'Every Labs feature already has a working backend — refining UX before public launch.',
    'labs.tagline': '30+ features · 1 core product · 0 quality compromises',
    'jarvis.live': 'LIVE',
    'jarvis.updated': 'Updated {m} min ago',
    'jarvis.refresh': 'Refresh',
    'jarvis.listen': 'Listen',
    'jarvis.stop': 'Stop',
    'jarvis.read_more': 'Read more',
    'jarvis.read_less': 'Read less',
    'jarvis.geopolitical_events': 'GEOPOLITICAL EVENTS',
    'jarvis.predictions': 'AI PREDICTIONS',
    'jarvis.confidence': 'confidence',
    'jarvis.loading': 'JARVIS is analyzing global events...',
    'jarvis.error': 'Unable to connect to JARVIS',
    'jarvis.retry': 'Retry',
    'jarvis.impact_high': 'HIGH IMPACT',
    'jarvis.impact_medium': 'MEDIUM IMPACT',
    'jarvis.impact_low': 'LOW IMPACT',
    'heatmap.title': 'Correlation Matrix',
    'heatmap.tooltip_pair': '{a} / {b}',
    'heatmap.divergence_warning': 'REGIME DIVERGENCE',
    'heatmap.legend_negative': 'Strong Inverse',
    'heatmap.legend_neutral': 'No Correlation',
    'heatmap.legend_positive': 'Strong Positive',
    'nav.global_fusion': 'Global Fusion',
    'nav.my_signals': 'My Signals',
    'nav.analyze_asset': 'Analyze Asset',
    'nav.labs': 'Labs',
  },
  es: {
    'nav.intelligence': 'Inteligencia',
    'nav.analysis': 'Analisis',
    'nav.trading': 'Trading',
    'nav.unfair_advantage': 'Ventaja Injusta',
    'nav.system': 'Sistema',
    'nav.command_center': 'Centro de Comando',
    'nav.jarvis_hub': 'JARVIS Hub',
    'nav.intel_terminal': 'Terminal Intel',
    'nav.intel_mode': 'Modo Intel',
    'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica',
    'nav.deep_analysis': 'Analisis Profundo',
    'nav.market_scanner': 'Escaner de Mercado',
    'nav.signal_timeline': 'Linea de Senales',
    'nav.capital_flow': 'Flujo de Capital',
    'nav.market_dna': 'ADN del Mercado',
    'nav.sentiment': 'Sentimiento',
    'nav.weekly_digest': 'Resumen Semanal',
    'nav.my_portfolio': 'Mi Portafolio',
    'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading',
    'nav.trade_simulator': 'Simulador de Trade',
    'nav.decision_replay': 'Replay de Decision',
    'nav.trader_dna': 'ADN del Trader',
    'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Intel Global',
    'nav.opp_scanner': 'Escaner de Opp.',
    'nav.top_traders': 'Top Traders',
    'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.share_cards': 'Share Cards',
    'nav.evolution': 'Evolution',
    'nav.strategy_creator': 'Create Strategy',
    'nav.aureos_score': 'Aureos Score',
    'nav.aureos_tokens': 'Aureos Tokens',
    'nav.track_record': 'Track Record',
    'nav.settings': 'Ajustes',
    'nav.alpha_radar': 'Alpha Radar',
    'nav.market_narrative': 'Narrativa',
    'dashboard.greeting_morning': 'Buenos dias',
    'dashboard.greeting_afternoon': 'Buenas tardes',
    'dashboard.greeting_evening': 'Buenas noches',
    'dashboard.market_pulse': 'PULSO DEL MERCADO',
    'dashboard.my_portfolio': 'MI PORTAFOLIO',
    'dashboard.intelligence': 'INTELIGENCIA DEL DIA',
    'dashboard.global_markets': 'MERCADOS GLOBALES',
    'common.refresh': 'Actualizar',
    'common.loading': 'Cargando...',
    'common.subscribe': 'Suscribirse',
    'common.view_all': 'Ver Todo',
    'common.narrate': 'Narrar con JARVIS',
    'common.narrating': 'Narrando...',
    'common.search': 'Buscar activos, comandos o preguntar a JARVIS...',
    'alpha.title': 'Alpha',
    'alpha.subtitle': 'Radar',
    'alpha.description': 'Donde esta la ventaja ahora? Top oportunidades globales con score + probabilidad.',
    'alpha.scan': 'Escanear Alpha',
    'alpha.scanning': 'Escaneando...',
    'narrative.title': 'Narrativa del',
    'narrative.subtitle': 'Mercado',
    'narrative.description': 'JARVIS narra la historia del mercado en tiempo real.',
    'narrative.generate': 'Generar Narrativa',
    'narrative.generating': 'Generando...',
    'copy.title': 'Copy Trading', 'copy.subtitle': 'Inteligente', 'copy.desc': 'Traders filtrados por IA. Solo traders consistentes y de bajo riesgo. JARVIS se adapta a tu ADN.',
    'copy.ai_rating': 'Rating IA', 'copy.win_rate': 'Tasa Victoria', 'copy.pnl': 'P&L', 'copy.risk': 'Riesgo', 'copy.btn': 'Copiar',
    'liquidity.title': 'Mapa de', 'liquidity.subtitle': 'Liquidez', 'liquidity.desc': 'A donde fluye el dinero?',
    'liquidity.capital_flows': 'Flujos de Capital', 'liquidity.sector_flows': 'Flujos por Sector', 'liquidity.zones': 'Zonas de Liquidez',
    'brain.title': 'Aureos', 'brain.subtitle': 'Second Brain', 'brain.desc': 'JARVIS recuerda todo. Tu memoria completa de trading.',
    'brain.total_decisions': 'Total Decisiones', 'brain.win_rate': 'Tasa Victoria', 'brain.total_pnl': 'P&L Total', 'brain.score': 'Aureos Score',
    'brain.patterns': 'Patrones Detectados', 'brain.insights': 'Insights de JARVIS', 'brain.evolution': 'Evolucion Mensual', 'brain.dna_profile': 'Perfil ADN',
    'brain.no_insights': 'Ejecuta mas trades para que JARVIS aprenda tus patrones.',
    'brain.best_day': 'Mejor Dia', 'brain.worst_day': 'Peor Dia', 'brain.best_asset': 'Mejor Activo', 'brain.worst_asset': 'Peor Activo', 'brain.asset_perf': 'Rendimiento por Activo',
    'missions.title': 'Misiones', 'missions.subtitle': 'Diarias', 'missions.desc': 'Completa misiones para ganar Aureos Tokens',
    'missions.total_reward': 'Recompensa Total', 'missions.completed': 'completadas', 'missions.complete_btn': 'Completar',
    'journal.title': 'Diario de', 'journal.subtitle': 'Trades IA', 'journal.desc': 'JARVIS analiza cada trade con nota + insight',
    'journal.empty': 'Sin trades cerrados aun. Tu diario se construira automaticamente.',
    'corr.title': 'Matriz de', 'corr.subtitle': 'Correlacion', 'corr.desc': 'Correlaciones en tiempo real entre los principales activos',
    'calendar.title': 'Calendario', 'calendar.subtitle': 'Economico', 'calendar.desc': 'Eventos con analisis de impacto por JARVIS',
    'calendar.ai_impact': 'Analisis de Impacto JARVIS', 'calendar.previous': 'Anterior', 'calendar.forecast': 'Pronostico',
    'quiz.title': 'Quiz de', 'quiz.subtitle': 'Trading', 'quiz.desc': 'Pon a prueba tu conocimiento. Gana 1 AT por respuesta correcta.',
    'quiz.submit': 'Enviar Quiz', 'quiz.new': 'Nuevo Quiz', 'quiz.earned': 'AT ganados', 'quiz.correct': 'correctas',
    'referral.title': 'Programa de', 'referral.subtitle': 'Referidos', 'referral.desc': 'Invita amigos.',
    'referral.code': 'Tu Codigo de Referido', 'referral.referrals': 'Referidos', 'referral.tokens_earned': 'Tokens Ganados',
    'referral.how': 'Como funciona', 'referral.step1': 'Comparte tu codigo con amigos', 'referral.step2': 'Se registran con tu codigo',
    'referral.twitter': 'Compartir en Twitter', 'referral.whatsapp': 'Compartir en WhatsApp',
    'decision.title': 'Motor de', 'decision.subtitle': 'Decision', 'decision.desc': 'BUY / SELL / HOLD para cualquier activo. Analisis multi-factor con probabilidad y gestion de riesgo.',
    'decision.search_placeholder': 'Buscar cualquier activo (BTC, AAPL, EUR/USD...)',
    'decision.analysis_complete': 'Analisis completo:', 'decision.error': 'Error al analizar activo',
    'decision.confidence': 'confianza', 'decision.probability': 'Probabilidad', 'decision.entry': 'Entrada',
    'decision.target': 'Objetivo', 'decision.stop_loss': 'Stop Loss', 'decision.risk_reward': 'Riesgo/Retorno',
    'decision.why': 'Por Que Este Trade?', 'decision.market_structure': 'Estructura', 'decision.liquidity': 'Liquidez',
    'decision.volatility': 'Volatilidad', 'decision.sentiment': 'Sentimiento', 'decision.quant_signals': 'Senales Cuantitativas',
    'decision.momentum': 'Momento', 'decision.reasoning': 'Razonamiento IA', 'decision.factor_scores': 'Scores por Factor',
    'decision.total_score': 'Score Total', 'decision.top_opp': 'Top Oportunidades',
    'trust.title': 'Performance', 'trust.subtitle': 'Publica', 'trust.desc': 'Transparencia total. Cada trade, cada senal, verificable.',
    'trust.total_trades': 'Total Trades', 'trust.win_rate': 'Tasa Victoria', 'trust.total_pnl': 'P&L Total',
    'trust.max_drawdown': 'Max Drawdown', 'trust.risk_reward': 'Riesgo/Retorno', 'trust.sharpe': 'Sharpe',
    'trust.users': 'Usuarios', 'trust.strategies': 'Estrategias', 'trust.assets_covered': 'Activos',
    'trust.signal_accuracy': 'Precision Senales', 'trust.total_signals': 'Total Senales',
    'trust.monthly_perf': 'Performance Mensual', 'trust.track_record': 'Track Record Verificado',
    'trust.current_streak': 'Racha Actual', 'trust.accuracy_by_class': 'Precision por Clase',
    'trust.top_strategies': 'Top Estrategias', 'trust.no_data': 'Sin datos', 'trust.no_signals': 'Sin senales registradas aun.',
    'fusion.title': 'JARVIS GLOBAL FUSION',
    'fusion.subtitle': 'Cruce de Datos Mundiales — Noticias × Precios × Geopolítica → Señales',
    'fusion.live': 'EN VIVO',
    'fusion.last_updated': 'Actualizado hace {s}s',
    'fusion.refresh': 'Actualizar',
    'fusion.events_captured': 'Eventos Capturados',
    'fusion.assets_analyzed': 'Activos Analizados',
    'fusion.active_signals': 'Señales Activas',
    'fusion.macro_regime': 'Régimen Macro',
    'fusion.executive_summary': 'RESUMEN EJECUTIVO JARVIS',
    'fusion.cross_asset_signals': 'SEÑALES MULTI-ACTIVO',
    'fusion.asset_impact': 'MAPA DE IMPACTO DE ACTIVOS',
    'fusion.correlation': 'CORRELACIÓN MULTI-ACTIVO EN TIEMPO REAL',
    'fusion.market_temp_hot': 'CALIENTE',
    'fusion.market_temp_warm': 'CÁLIDO',
    'fusion.market_temp_cool': 'FRÍO',
    'fusion.signal_buy': 'COMPRAR',
    'fusion.signal_sell': 'VENDER',
    'fusion.signal_hold': 'MANTENER',
    'fusion.signal_watch': 'VIGILAR',
    'fusion.confidence': 'Confianza',
    'fusion.trade_ideas': 'Ideas de Trading',
    'fusion.impact_high': 'ALTO',
    'fusion.impact_medium': 'MEDIO',
    'fusion.impact_low': 'BAJO',
    'fusion.bias_bullish': 'ALCISTA',
    'fusion.bias_bearish': 'BAJISTA',
    'fusion.bias_neutral': 'NEUTRAL',
    'fusion.key_drivers': 'Factores Clave',
    'fusion.risk_level': 'Riesgo',
    'fusion.expand': 'Expandir',
    'fusion.collapse': 'Contraer',
    'fusion.no_events': 'No hay eventos capturados aún',
    'fusion.loading': 'Sincronizando datos globales...',
    'fusion.error_retry': 'Reintentar',
    'fusion.analyze_event': 'Analizar Evento',
    'fusion.analyze_placeholder': 'Pega cualquier titular para analizar el impacto en el mercado...',
    'fusion.regime_risk_on': 'RIESGO ACTIVO',
    'fusion.regime_risk_off': 'RIESGO OFF',
    'fusion.regime_stagflation': 'ESTANFLACIÓN',
    'fusion.regime_goldilocks': 'GOLDILOCKS',
    'fusion.regime_crisis': 'CRISIS',
    'fusion.filter_all': 'TODOS',
    'fusion.filter_geo': 'GEOPOLÍTICO',
    'fusion.filter_macro': 'MACRO',
    'fusion.filter_crypto': 'CRYPTO',
    'fusion.filter_equity': 'ACCIONES',
    'fusion.filter_commodity': 'COMMODITY',
    'fusion.filter_forex': 'FOREX',
    'fusion.source': 'Fuente',
    'fusion.affected': 'Afectados',
    'fusion.divergence': 'DIVERGENCIA',
    'fusion.corr_high_pos': 'Alta correlación positiva',
    'fusion.corr_high_neg': 'Alta correlación inversa',
    'fusion.corr_low': 'Baja correlación',
    'labs.title': 'AUREOS LABS',
    'labs.subtitle': 'Funciones en desarrollo activo. Cada una se lanza cuando se cumplen los estándares de calidad.',
    'labs.pipeline': 'funciones en desarrollo',
    'labs.q2': 'Q2 2026',
    'labs.q3': 'Q3 2026',
    'labs.q4': 'Q4 2026',
    'labs.footer': 'Cada función de Labs ya tiene un backend funcional — refinando UX antes del lanzamiento público.',
    'labs.tagline': '30+ funciones · 1 producto central · 0 compromisos de calidad',
    'jarvis.live': 'EN VIVO',
    'jarvis.updated': 'Actualizado hace {m} min',
    'jarvis.refresh': 'Actualizar',
    'jarvis.listen': 'Escuchar',
    'jarvis.stop': 'Detener',
    'jarvis.read_more': 'Leer más',
    'jarvis.read_less': 'Leer menos',
    'jarvis.geopolitical_events': 'EVENTOS GEOPOLÍTICOS',
    'jarvis.predictions': 'PREDICCIONES IA',
    'jarvis.confidence': 'confianza',
    'jarvis.loading': 'JARVIS está analizando eventos globales...',
    'jarvis.error': 'No se puede conectar a JARVIS',
    'jarvis.retry': 'Reintentar',
    'jarvis.impact_high': 'ALTO IMPACTO',
    'jarvis.impact_medium': 'IMPACTO MEDIO',
    'jarvis.impact_low': 'BAJO IMPACTO',
    'heatmap.title': 'Matriz de Correlación',
    'heatmap.tooltip_pair': '{a} / {b}',
    'heatmap.divergence_warning': 'DIVERGENCIA DE RÉGIMEN',
    'heatmap.legend_negative': 'Inversa Fuerte',
    'heatmap.legend_neutral': 'Sin Correlación',
    'heatmap.legend_positive': 'Positiva Fuerte',
    'nav.global_fusion': 'Fusión Global',
    'nav.my_signals': 'Mis Señales',
    'nav.analyze_asset': 'Analizar Activo',
    'nav.labs': 'Labs',
  },
  fr: {
    'nav.intelligence': 'Intelligence', 'nav.analysis': 'Analyse', 'nav.trading': 'Trading', 'nav.unfair_advantage': 'Avantage Injuste', 'nav.system': 'Systeme',
    'nav.command_center': 'Centre de Commande', 'nav.jarvis_hub': 'JARVIS Hub', 'nav.intel_terminal': 'Terminal Intel', 'nav.intel_mode': 'Mode Intel', 'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica', 'nav.deep_analysis': 'Analyse Profonde', 'nav.market_scanner': 'Scanner Marche', 'nav.signal_timeline': 'Chronologie Signaux', 'nav.capital_flow': 'Flux Capital',
    'nav.market_dna': 'ADN Marche', 'nav.sentiment': 'Sentiment', 'nav.weekly_digest': 'Resume Hebdo', 'nav.my_portfolio': 'Mon Portfolio', 'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading', 'nav.trade_simulator': 'Simulateur Trade', 'nav.decision_replay': 'Replay Decision', 'nav.trader_dna': 'ADN Trader', 'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Intel Global', 'nav.opp_scanner': 'Scanner Opp.', 'nav.top_traders': 'Top Traders', 'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score', 'nav.aureos_tokens': 'Aureos Tokens', 'nav.track_record': 'Track Record', 'nav.settings': 'Parametres', 'nav.alpha_radar': 'Alpha Radar', 'nav.market_narrative': 'Narratif',
    'dashboard.greeting_morning': 'Bonjour', 'dashboard.greeting_afternoon': 'Bon apres-midi', 'dashboard.greeting_evening': 'Bonsoir',
    'dashboard.market_pulse': 'POULS DU MARCHE', 'dashboard.my_portfolio': 'MON PORTFOLIO', 'dashboard.intelligence': 'INTELLIGENCE DU JOUR', 'dashboard.global_markets': 'MARCHES MONDIAUX',
    'common.refresh': 'Rafraichir', 'common.loading': 'Chargement...', 'common.subscribe': 'Souscrire', 'common.view_all': 'Voir Tout', 'common.narrate': 'Narrer avec JARVIS', 'common.narrating': 'Narration...',
    'common.search': 'Rechercher actifs, commandes ou demander a JARVIS...',
    'alpha.title': 'Alpha', 'alpha.subtitle': 'Radar', 'alpha.description': 'Ou est lavantage maintenant?', 'alpha.scan': 'Scanner Alpha', 'alpha.scanning': 'Scan en cours...',
    'narrative.title': 'Narratif du', 'narrative.subtitle': 'Marche', 'narrative.description': 'JARVIS raconte lhistoire du marche en temps reel.', 'narrative.generate': 'Generer Narratif', 'narrative.generating': 'Generation...',
    'fusion.title': 'JARVIS GLOBAL FUSION',
    'fusion.subtitle': 'Croisement de Données Mondiales — Actualités × Prix × Géopolitique → Signaux',
    'fusion.live': 'EN DIRECT',
    'fusion.last_updated': 'Mis à jour il y a {s}s',
    'fusion.refresh': 'Actualiser',
    'fusion.events_captured': 'Événements Capturés',
    'fusion.assets_analyzed': 'Actifs Analysés',
    'fusion.active_signals': 'Signaux Actifs',
    'fusion.macro_regime': 'Régime Macro',
    'fusion.executive_summary': 'RÉSUMÉ EXÉCUTIF JARVIS',
    'fusion.cross_asset_signals': 'SIGNAUX MULTI-ACTIFS',
    'fusion.asset_impact': 'CARTE D\'IMPACT DES ACTIFS',
    'fusion.correlation': 'CORRÉLATION MULTI-ACTIFS EN TEMPS RÉEL',
    'fusion.market_temp_hot': 'CHAUD',
    'fusion.market_temp_warm': 'TIÈDE',
    'fusion.market_temp_cool': 'FROID',
    'fusion.signal_buy': 'ACHETER',
    'fusion.signal_sell': 'VENDRE',
    'fusion.signal_hold': 'CONSERVER',
    'fusion.signal_watch': 'SURVEILLER',
    'fusion.confidence': 'Confiance',
    'fusion.trade_ideas': 'Idées de Trading',
    'fusion.impact_high': 'ÉLEVÉ',
    'fusion.impact_medium': 'MOYEN',
    'fusion.impact_low': 'FAIBLE',
    'fusion.bias_bullish': 'HAUSSIER',
    'fusion.bias_bearish': 'BAISSIER',
    'fusion.bias_neutral': 'NEUTRE',
    'fusion.key_drivers': 'Facteurs Clés',
    'fusion.risk_level': 'Risque',
    'fusion.expand': 'Développer',
    'fusion.collapse': 'Réduire',
    'fusion.no_events': 'Aucun événement capturé',
    'fusion.loading': 'Synchronisation des données mondiales...',
    'fusion.error_retry': 'Réessayer',
    'fusion.analyze_event': 'Analyser l\'Événement',
    'fusion.analyze_placeholder': 'Collez un titre d\'actualité pour analyser l\'impact sur le marché...',
    'fusion.regime_risk_on': 'RISQUE ACTIF',
    'fusion.regime_risk_off': 'RISQUE OFF',
    'fusion.regime_stagflation': 'STAGFLATION',
    'fusion.regime_goldilocks': 'GOLDILOCKS',
    'fusion.regime_crisis': 'CRISE',
    'fusion.filter_all': 'TOUS',
    'fusion.filter_geo': 'GÉOPOLITIQUE',
    'fusion.filter_macro': 'MACRO',
    'fusion.filter_crypto': 'CRYPTO',
    'fusion.filter_equity': 'ACTIONS',
    'fusion.filter_commodity': 'MATIÈRES PREMIÈRES',
    'fusion.filter_forex': 'FOREX',
    'fusion.source': 'Source',
    'fusion.affected': 'Affectés',
    'fusion.divergence': 'DIVERGENCE',
    'fusion.corr_high_pos': 'Forte corrélation positive',
    'fusion.corr_high_neg': 'Forte corrélation inverse',
    'fusion.corr_low': 'Faible corrélation',
    'labs.title': 'AUREOS LABS',
    'labs.subtitle': 'Fonctionnalités en développement actif. Chacune est lancée quand les standards de qualité sont atteints.',
    'labs.pipeline': 'fonctionnalités en développement',
    'labs.q2': 'Q2 2026',
    'labs.q3': 'Q3 2026',
    'labs.q4': 'Q4 2026',
    'labs.footer': 'Chaque fonctionnalité Labs a déjà un backend fonctionnel — on affine l\'UX avant le lancement public.',
    'labs.tagline': '30+ fonctionnalités · 1 produit central · 0 compromis qualité',
    'jarvis.live': 'EN DIRECT',
    'jarvis.updated': 'Mis à jour il y a {m} min',
    'jarvis.refresh': 'Actualiser',
    'jarvis.listen': 'Écouter',
    'jarvis.stop': 'Arrêter',
    'jarvis.read_more': 'Lire la suite',
    'jarvis.read_less': 'Lire moins',
    'jarvis.geopolitical_events': 'ÉVÉNEMENTS GÉOPOLITIQUES',
    'jarvis.predictions': 'PRÉDICTIONS IA',
    'jarvis.confidence': 'confiance',
    'jarvis.loading': 'JARVIS analyse les événements mondiaux...',
    'jarvis.error': 'Impossible de se connecter à JARVIS',
    'jarvis.retry': 'Réessayer',
    'jarvis.impact_high': 'IMPACT ÉLEVÉ',
    'jarvis.impact_medium': 'IMPACT MOYEN',
    'jarvis.impact_low': 'FAIBLE IMPACT',
    'heatmap.title': 'Matrice de Corrélation',
    'heatmap.tooltip_pair': '{a} / {b}',
    'heatmap.divergence_warning': 'DIVERGENCE DE RÉGIME',
    'heatmap.legend_negative': 'Inverse Fort',
    'heatmap.legend_neutral': 'Aucune Corrélation',
    'heatmap.legend_positive': 'Positif Fort',
    'nav.global_fusion': 'Fusion Mondiale',
    'nav.my_signals': 'Mes Signaux',
    'nav.analyze_asset': 'Analyser un Actif',
    'nav.labs': 'Labs',
  },
  de: {
    'nav.intelligence': 'Intelligenz', 'nav.analysis': 'Analyse', 'nav.trading': 'Trading', 'nav.unfair_advantage': 'Unfairer Vorteil', 'nav.system': 'System',
    'nav.command_center': 'Kommandozentrale', 'nav.jarvis_hub': 'JARVIS Hub', 'nav.intel_terminal': 'Intel Terminal', 'nav.intel_mode': 'Intel Modus', 'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica', 'nav.deep_analysis': 'Tiefenanalyse', 'nav.market_scanner': 'Marktscanner', 'nav.signal_timeline': 'Signal-Zeitleiste', 'nav.capital_flow': 'Kapitalfluss',
    'nav.market_dna': 'Markt-DNA', 'nav.sentiment': 'Stimmung', 'nav.weekly_digest': 'Wochenubersicht', 'nav.my_portfolio': 'Mein Portfolio', 'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading', 'nav.trade_simulator': 'Trade-Simulator', 'nav.decision_replay': 'Entscheidungs-Replay', 'nav.trader_dna': 'Trader-DNA', 'nav.marketplace': 'Marktplatz',
    'nav.global_intel': 'Globale Intel', 'nav.opp_scanner': 'Opp-Scanner', 'nav.top_traders': 'Top Trader', 'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score', 'nav.aureos_tokens': 'Aureos Tokens', 'nav.track_record': 'Track Record', 'nav.settings': 'Einstellungen', 'nav.alpha_radar': 'Alpha Radar', 'nav.market_narrative': 'Narrativ',
    'dashboard.greeting_morning': 'Guten Morgen', 'dashboard.greeting_afternoon': 'Guten Tag', 'dashboard.greeting_evening': 'Guten Abend',
    'dashboard.market_pulse': 'MARKTPULS', 'dashboard.my_portfolio': 'MEIN PORTFOLIO', 'dashboard.intelligence': 'INTELLIGENZ DES TAGES', 'dashboard.global_markets': 'GLOBALE MARKTE',
    'common.refresh': 'Aktualisieren', 'common.loading': 'Laden...', 'common.subscribe': 'Abonnieren', 'common.view_all': 'Alle ansehen', 'common.narrate': 'Mit JARVIS erzahlen', 'common.narrating': 'Erzahlen...',
    'common.search': 'Assets, Befehle suchen oder JARVIS fragen...',
    'alpha.title': 'Alpha', 'alpha.subtitle': 'Radar', 'alpha.description': 'Wo liegt der Vorteil jetzt?', 'alpha.scan': 'Alpha scannen', 'alpha.scanning': 'Scannen...',
    'narrative.title': 'Markt', 'narrative.subtitle': 'Narrativ', 'narrative.description': 'JARVIS erzahlt die Marktgeschichte in Echtzeit.', 'narrative.generate': 'Narrativ generieren', 'narrative.generating': 'Generieren...',
    'fusion.title': 'JARVIS GLOBAL FUSION',
    'fusion.subtitle': 'Weltdaten-Crossfeed — Nachrichten × Preise × Geopolitik → Signale',
    'fusion.live': 'LIVE',
    'fusion.last_updated': 'Vor {s}s aktualisiert',
    'fusion.refresh': 'Aktualisieren',
    'fusion.events_captured': 'Erfasste Ereignisse',
    'fusion.assets_analyzed': 'Analysierte Assets',
    'fusion.active_signals': 'Aktive Signale',
    'fusion.macro_regime': 'Makro-Regime',
    'fusion.executive_summary': 'JARVIS ZUSAMMENFASSUNG',
    'fusion.cross_asset_signals': 'CROSS-ASSET-SIGNALE',
    'fusion.asset_impact': 'ASSET-AUSWIRKUNGSKARTE',
    'fusion.correlation': 'ECHTZEIT CROSS-ASSET KORRELATION',
    'fusion.market_temp_hot': 'HEISS',
    'fusion.market_temp_warm': 'WARM',
    'fusion.market_temp_cool': 'KÜHL',
    'fusion.signal_buy': 'KAUFEN',
    'fusion.signal_sell': 'VERKAUFEN',
    'fusion.signal_hold': 'HALTEN',
    'fusion.signal_watch': 'BEOBACHTEN',
    'fusion.confidence': 'Konfidenz',
    'fusion.trade_ideas': 'Trade-Ideen',
    'fusion.impact_high': 'HOCH',
    'fusion.impact_medium': 'MITTEL',
    'fusion.impact_low': 'NIEDRIG',
    'fusion.bias_bullish': 'BULLISH',
    'fusion.bias_bearish': 'BEARISH',
    'fusion.bias_neutral': 'NEUTRAL',
    'fusion.key_drivers': 'Schlüsselfaktoren',
    'fusion.risk_level': 'Risiko',
    'fusion.expand': 'Erweitern',
    'fusion.collapse': 'Einklappen',
    'fusion.no_events': 'Noch keine Ereignisse erfasst',
    'fusion.loading': 'Globale Daten werden synchronisiert...',
    'fusion.error_retry': 'Wiederholen',
    'fusion.analyze_event': 'Ereignis analysieren',
    'fusion.analyze_placeholder': 'Schlagzeile einfügen, um Marktauswirkungen zu analysieren...',
    'fusion.regime_risk_on': 'RISIKO EIN',
    'fusion.regime_risk_off': 'RISIKO AUS',
    'fusion.regime_stagflation': 'STAGFLATION',
    'fusion.regime_goldilocks': 'GOLDILOCKS',
    'fusion.regime_crisis': 'KRISE',
    'fusion.filter_all': 'ALLE',
    'fusion.filter_geo': 'GEOPOLITISCH',
    'fusion.filter_macro': 'MAKRO',
    'fusion.filter_crypto': 'KRYPTO',
    'fusion.filter_equity': 'AKTIEN',
    'fusion.filter_commodity': 'ROHSTOFFE',
    'fusion.filter_forex': 'FOREX',
    'fusion.source': 'Quelle',
    'fusion.affected': 'Betroffen',
    'fusion.divergence': 'DIVERGENZ',
    'fusion.corr_high_pos': 'Starke positive Korrelation',
    'fusion.corr_high_neg': 'Starke inverse Korrelation',
    'fusion.corr_low': 'Schwache Korrelation',
    'labs.title': 'AUREOS LABS',
    'labs.subtitle': 'Funktionen in aktiver Entwicklung. Jede wird gestartet, wenn Qualitätsstandards erfüllt sind.',
    'labs.pipeline': 'Funktionen in der Pipeline',
    'labs.q2': 'Q2 2026',
    'labs.q3': 'Q3 2026',
    'labs.q4': 'Q4 2026',
    'labs.footer': 'Jede Labs-Funktion hat bereits ein funktionierendes Backend — UX wird vor der Veröffentlichung verfeinert.',
    'labs.tagline': '30+ Funktionen · 1 Kernprodukt · 0 Qualitätskompromisse',
    'jarvis.live': 'LIVE',
    'jarvis.updated': 'Vor {m} min aktualisiert',
    'jarvis.refresh': 'Aktualisieren',
    'jarvis.listen': 'Anhören',
    'jarvis.stop': 'Stoppen',
    'jarvis.read_more': 'Mehr lesen',
    'jarvis.read_less': 'Weniger lesen',
    'jarvis.geopolitical_events': 'GEOPOLITISCHE EREIGNISSE',
    'jarvis.predictions': 'KI-VORHERSAGEN',
    'jarvis.confidence': 'Konfidenz',
    'jarvis.loading': 'JARVIS analysiert globale Ereignisse...',
    'jarvis.error': 'Verbindung zu JARVIS nicht möglich',
    'jarvis.retry': 'Wiederholen',
    'jarvis.impact_high': 'HOHE AUSWIRKUNG',
    'jarvis.impact_medium': 'MITTLERE AUSWIRKUNG',
    'jarvis.impact_low': 'GERINGE AUSWIRKUNG',
    'heatmap.title': 'Korrelationsmatrix',
    'heatmap.tooltip_pair': '{a} / {b}',
    'heatmap.divergence_warning': 'REGIME-DIVERGENZ',
    'heatmap.legend_negative': 'Stark invers',
    'heatmap.legend_neutral': 'Keine Korrelation',
    'heatmap.legend_positive': 'Stark positiv',
    'nav.global_fusion': 'Globale Fusion',
    'nav.my_signals': 'Meine Signale',
    'nav.analyze_asset': 'Asset analysieren',
    'nav.labs': 'Labs',
  },
  zh: {
    'nav.intelligence': 'Intelligence', 'nav.analysis': 'Analysis', 'nav.trading': 'Trading', 'nav.unfair_advantage': 'Unfair Advantage', 'nav.system': 'System',
    'nav.command_center': 'Command Center', 'nav.jarvis_hub': 'JARVIS Hub', 'nav.intel_terminal': 'Intel Terminal', 'nav.intel_mode': 'Intel Mode', 'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica', 'nav.deep_analysis': 'Deep Analysis', 'nav.market_scanner': 'Market Scanner', 'nav.signal_timeline': 'Signal Timeline', 'nav.capital_flow': 'Capital Flow',
    'nav.market_dna': 'Market DNA', 'nav.sentiment': 'Sentiment', 'nav.weekly_digest': 'Weekly Digest', 'nav.my_portfolio': 'My Portfolio', 'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading', 'nav.trade_simulator': 'Trade Simulator', 'nav.decision_replay': 'Decision Replay', 'nav.trader_dna': 'Trader DNA', 'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Global Intel', 'nav.opp_scanner': 'Opp Scanner', 'nav.top_traders': 'Top Traders', 'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score', 'nav.aureos_tokens': 'Aureos Tokens', 'nav.track_record': 'Track Record', 'nav.settings': 'Settings', 'nav.alpha_radar': 'Alpha Radar', 'nav.market_narrative': 'Narrative',
    'dashboard.greeting_morning': 'Good morning', 'dashboard.greeting_afternoon': 'Good afternoon', 'dashboard.greeting_evening': 'Good evening',
    'dashboard.market_pulse': 'MARKET PULSE', 'dashboard.my_portfolio': 'MY PORTFOLIO', 'dashboard.intelligence': 'INTELLIGENCE', 'dashboard.global_markets': 'GLOBAL MARKETS',
    'common.refresh': 'Refresh', 'common.loading': 'Loading...', 'common.subscribe': 'Subscribe', 'common.view_all': 'View All', 'common.narrate': 'Narrate with JARVIS', 'common.narrating': 'Narrating...',
    'common.search': 'Search assets, commands, or ask JARVIS...',
    'alpha.title': 'Alpha', 'alpha.subtitle': 'Radar', 'alpha.description': 'Where is the edge right now?', 'alpha.scan': 'Scan Alpha', 'alpha.scanning': 'Scanning...',
    'narrative.title': 'Market', 'narrative.subtitle': 'Narrative', 'narrative.description': 'JARVIS narrates the market story.', 'narrative.generate': 'Generate', 'narrative.generating': 'Generating...',
    'fusion.title': 'JARVIS 全球融合',
    'fusion.subtitle': '全球数据交叉 — 新闻 × 价格 × 地缘政治 → 信号',
    'fusion.live': '实时',
    'fusion.last_updated': '{s}秒前更新',
    'fusion.refresh': '刷新',
    'fusion.events_captured': '捕获事件',
    'fusion.assets_analyzed': '分析资产',
    'fusion.active_signals': '活跃信号',
    'fusion.macro_regime': '宏观环境',
    'fusion.executive_summary': 'JARVIS 执行摘要',
    'fusion.cross_asset_signals': '跨资产信号',
    'fusion.asset_impact': '资产影响地图',
    'fusion.correlation': '实时跨资产相关性',
    'fusion.market_temp_hot': '热',
    'fusion.market_temp_warm': '暖',
    'fusion.market_temp_cool': '冷',
    'fusion.signal_buy': '买入',
    'fusion.signal_sell': '卖出',
    'fusion.signal_hold': '持有',
    'fusion.signal_watch': '观察',
    'fusion.confidence': '置信度',
    'fusion.trade_ideas': '交易建议',
    'fusion.impact_high': '高',
    'fusion.impact_medium': '中',
    'fusion.impact_low': '低',
    'fusion.bias_bullish': '看涨',
    'fusion.bias_bearish': '看跌',
    'fusion.bias_neutral': '中性',
    'fusion.key_drivers': '关键驱动因素',
    'fusion.risk_level': '风险',
    'fusion.expand': '展开',
    'fusion.collapse': '收起',
    'fusion.no_events': '暂无捕获事件',
    'fusion.loading': '正在同步全球数据...',
    'fusion.error_retry': '重试',
    'fusion.analyze_event': '分析事件',
    'fusion.analyze_placeholder': '粘贴任何新闻标题以分析市场影响...',
    'fusion.regime_risk_on': '风险偏好',
    'fusion.regime_risk_off': '避险',
    'fusion.regime_stagflation': '滞胀',
    'fusion.regime_goldilocks': '金发女孩',
    'fusion.regime_crisis': '危机',
    'fusion.filter_all': '全部',
    'fusion.filter_geo': '地缘政治',
    'fusion.filter_macro': '宏观',
    'fusion.filter_crypto': '加密',
    'fusion.filter_equity': '股票',
    'fusion.filter_commodity': '大宗商品',
    'fusion.filter_forex': '外汇',
    'fusion.source': '来源',
    'fusion.affected': '受影响',
    'fusion.divergence': '背离',
    'fusion.corr_high_pos': '强正相关',
    'fusion.corr_high_neg': '强负相关',
    'fusion.corr_low': '弱相关',
    'labs.title': 'AUREOS LABS',
    'labs.subtitle': '积极开发中的功能，每项在达到质量标准后发布。',
    'labs.pipeline': '功能开发中',
    'labs.q2': 'Q2 2026',
    'labs.q3': 'Q3 2026',
    'labs.q4': 'Q4 2026',
    'labs.footer': '每项 Labs 功能都已有可运行的后端——正在完善用户体验后再公开发布。',
    'labs.tagline': '30+ 功能 · 1 核心产品 · 0 质量妥协',
    'jarvis.live': '实时',
    'jarvis.updated': '{m}分钟前更新',
    'jarvis.refresh': '刷新',
    'jarvis.listen': '收听',
    'jarvis.stop': '停止',
    'jarvis.read_more': '阅读更多',
    'jarvis.read_less': '收起',
    'jarvis.geopolitical_events': '地缘政治事件',
    'jarvis.predictions': 'AI 预测',
    'jarvis.confidence': '置信度',
    'jarvis.loading': 'JARVIS 正在分析全球事件...',
    'jarvis.error': '无法连接到 JARVIS',
    'jarvis.retry': '重试',
    'jarvis.impact_high': '高影响',
    'jarvis.impact_medium': '中影响',
    'jarvis.impact_low': '低影响',
    'heatmap.title': '相关性矩阵',
    'heatmap.tooltip_pair': '{a} / {b}',
    'heatmap.divergence_warning': '制度背离',
    'heatmap.legend_negative': '强负相关',
    'heatmap.legend_neutral': '无相关',
    'heatmap.legend_positive': '强正相关',
    'nav.global_fusion': '全球融合',
    'nav.my_signals': '我的信号',
    'nav.analyze_asset': '分析资产',
    'nav.labs': '实验室',
  },
  ja: {
    'nav.intelligence': 'Intelligence', 'nav.analysis': 'Analysis', 'nav.trading': 'Trading', 'nav.unfair_advantage': 'Unfair Advantage', 'nav.system': 'System',
    'nav.command_center': 'Command Center', 'nav.jarvis_hub': 'JARVIS Hub', 'nav.intel_terminal': 'Intel Terminal', 'nav.intel_mode': 'Intel Mode', 'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica', 'nav.deep_analysis': 'Deep Analysis', 'nav.market_scanner': 'Market Scanner', 'nav.signal_timeline': 'Signal Timeline', 'nav.capital_flow': 'Capital Flow',
    'nav.market_dna': 'Market DNA', 'nav.sentiment': 'Sentiment', 'nav.weekly_digest': 'Weekly Digest', 'nav.my_portfolio': 'My Portfolio', 'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading', 'nav.trade_simulator': 'Trade Simulator', 'nav.decision_replay': 'Decision Replay', 'nav.trader_dna': 'Trader DNA', 'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Global Intel', 'nav.opp_scanner': 'Opp Scanner', 'nav.top_traders': 'Top Traders', 'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score', 'nav.aureos_tokens': 'Aureos Tokens', 'nav.track_record': 'Track Record', 'nav.settings': 'Settings', 'nav.alpha_radar': 'Alpha Radar', 'nav.market_narrative': 'Narrative',
    'dashboard.greeting_morning': 'Good morning', 'dashboard.greeting_afternoon': 'Good afternoon', 'dashboard.greeting_evening': 'Good evening',
    'dashboard.market_pulse': 'MARKET PULSE', 'dashboard.my_portfolio': 'MY PORTFOLIO', 'dashboard.intelligence': 'INTELLIGENCE', 'dashboard.global_markets': 'GLOBAL MARKETS',
    'common.refresh': 'Refresh', 'common.loading': 'Loading...', 'common.subscribe': 'Subscribe', 'common.view_all': 'View All', 'common.narrate': 'Narrate with JARVIS', 'common.narrating': 'Narrating...',
    'common.search': 'Search assets, commands, or ask JARVIS...',
    'alpha.title': 'Alpha', 'alpha.subtitle': 'Radar', 'alpha.description': 'Where is the edge right now?', 'alpha.scan': 'Scan Alpha', 'alpha.scanning': 'Scanning...',
    'narrative.title': 'Market', 'narrative.subtitle': 'Narrative', 'narrative.description': 'JARVIS narrates the market story.', 'narrative.generate': 'Generate', 'narrative.generating': 'Generating...',
    'fusion.title': 'JARVIS グローバルフュージョン',
    'fusion.subtitle': '世界データクロスフィード — ニュース × 価格 × 地政学 → シグナル',
    'fusion.live': 'ライブ',
    'fusion.last_updated': '{s}秒前に更新',
    'fusion.refresh': '更新',
    'fusion.events_captured': 'キャプチャされたイベント',
    'fusion.assets_analyzed': '分析された資産',
    'fusion.active_signals': 'アクティブシグナル',
    'fusion.macro_regime': 'マクロレジーム',
    'fusion.executive_summary': 'JARVIS エグゼクティブサマリー',
    'fusion.cross_asset_signals': 'クロスアセットシグナル',
    'fusion.asset_impact': '資産インパクトマップ',
    'fusion.correlation': 'リアルタイムクロスアセット相関',
    'fusion.market_temp_hot': '過熱',
    'fusion.market_temp_warm': '温暖',
    'fusion.market_temp_cool': '冷静',
    'fusion.signal_buy': '買い',
    'fusion.signal_sell': '売り',
    'fusion.signal_hold': '保持',
    'fusion.signal_watch': '注視',
    'fusion.confidence': '信頼度',
    'fusion.trade_ideas': 'トレードアイデア',
    'fusion.impact_high': '高',
    'fusion.impact_medium': '中',
    'fusion.impact_low': '低',
    'fusion.bias_bullish': '強気',
    'fusion.bias_bearish': '弱気',
    'fusion.bias_neutral': '中立',
    'fusion.key_drivers': '主要要因',
    'fusion.risk_level': 'リスク',
    'fusion.expand': '展開',
    'fusion.collapse': '閉じる',
    'fusion.no_events': 'イベントはまだキャプチャされていません',
    'fusion.loading': 'グローバルデータを同期中...',
    'fusion.error_retry': '再試行',
    'fusion.analyze_event': 'イベントを分析',
    'fusion.analyze_placeholder': 'ニュース見出しを貼り付けて市場への影響を分析...',
    'fusion.regime_risk_on': 'リスクオン',
    'fusion.regime_risk_off': 'リスクオフ',
    'fusion.regime_stagflation': 'スタグフレーション',
    'fusion.regime_goldilocks': 'ゴルディロックス',
    'fusion.regime_crisis': 'クライシス',
    'fusion.filter_all': 'すべて',
    'fusion.filter_geo': '地政学',
    'fusion.filter_macro': 'マクロ',
    'fusion.filter_crypto': 'クリプト',
    'fusion.filter_equity': '株式',
    'fusion.filter_commodity': 'コモディティ',
    'fusion.filter_forex': '為替',
    'fusion.source': '情報源',
    'fusion.affected': '影響資産',
    'fusion.divergence': '乖離',
    'fusion.corr_high_pos': '強い正相関',
    'fusion.corr_high_neg': '強い逆相関',
    'fusion.corr_low': '弱い相関',
    'labs.title': 'AUREOS LABS',
    'labs.subtitle': '積極的に開発中の機能。品質基準を満たした時点で順次公開。',
    'labs.pipeline': '機能開発中',
    'labs.q2': 'Q2 2026',
    'labs.q3': 'Q3 2026',
    'labs.q4': 'Q4 2026',
    'labs.footer': 'すべてのLabs機能は既にバックエンドが稼働中 — 公開前にUXを改善中。',
    'labs.tagline': '30以上の機能 · 1つのコアプロダクト · 0の品質妥協',
    'jarvis.live': 'ライブ',
    'jarvis.updated': '{m}分前に更新',
    'jarvis.refresh': '更新',
    'jarvis.listen': '聴く',
    'jarvis.stop': '停止',
    'jarvis.read_more': 'もっと読む',
    'jarvis.read_less': '折りたたむ',
    'jarvis.geopolitical_events': '地政学的イベント',
    'jarvis.predictions': 'AI予測',
    'jarvis.confidence': '信頼度',
    'jarvis.loading': 'JARVISがグローバルイベントを分析中...',
    'jarvis.error': 'JARVISに接続できません',
    'jarvis.retry': '再試行',
    'jarvis.impact_high': '高インパクト',
    'jarvis.impact_medium': '中インパクト',
    'jarvis.impact_low': '低インパクト',
    'heatmap.title': '相関マトリックス',
    'heatmap.tooltip_pair': '{a} / {b}',
    'heatmap.divergence_warning': 'レジーム乖離',
    'heatmap.legend_negative': '強い逆相関',
    'heatmap.legend_neutral': '相関なし',
    'heatmap.legend_positive': '強い正相関',
    'nav.global_fusion': 'グローバルフュージョン',
    'nav.my_signals': 'マイシグナル',
    'nav.analyze_asset': '資産を分析',
    'nav.labs': 'ラボ',
  },
  ko: {
    'nav.intelligence': 'Intelligence', 'nav.analysis': 'Analysis', 'nav.trading': 'Trading', 'nav.unfair_advantage': 'Unfair Advantage', 'nav.system': 'System',
    'nav.command_center': 'Command Center', 'nav.jarvis_hub': 'JARVIS Hub', 'nav.intel_terminal': 'Intel Terminal', 'nav.intel_mode': 'Intel Mode', 'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica', 'nav.deep_analysis': 'Deep Analysis', 'nav.market_scanner': 'Market Scanner', 'nav.signal_timeline': 'Signal Timeline', 'nav.capital_flow': 'Capital Flow',
    'nav.market_dna': 'Market DNA', 'nav.sentiment': 'Sentiment', 'nav.weekly_digest': 'Weekly Digest', 'nav.my_portfolio': 'My Portfolio', 'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading', 'nav.trade_simulator': 'Trade Simulator', 'nav.decision_replay': 'Decision Replay', 'nav.trader_dna': 'Trader DNA', 'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Global Intel', 'nav.opp_scanner': 'Opp Scanner', 'nav.top_traders': 'Top Traders', 'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score', 'nav.aureos_tokens': 'Aureos Tokens', 'nav.track_record': 'Track Record', 'nav.settings': 'Settings', 'nav.alpha_radar': 'Alpha Radar', 'nav.market_narrative': 'Narrative',
    'dashboard.greeting_morning': 'Good morning', 'dashboard.greeting_afternoon': 'Good afternoon', 'dashboard.greeting_evening': 'Good evening',
    'dashboard.market_pulse': 'MARKET PULSE', 'dashboard.my_portfolio': 'MY PORTFOLIO', 'dashboard.intelligence': 'INTELLIGENCE', 'dashboard.global_markets': 'GLOBAL MARKETS',
    'common.refresh': 'Refresh', 'common.loading': 'Loading...', 'common.subscribe': 'Subscribe', 'common.view_all': 'View All', 'common.narrate': 'Narrate with JARVIS', 'common.narrating': 'Narrating...',
    'common.search': 'Search assets, commands, or ask JARVIS...',
    'alpha.title': 'Alpha', 'alpha.subtitle': 'Radar', 'alpha.description': 'Where is the edge right now?', 'alpha.scan': 'Scan Alpha', 'alpha.scanning': 'Scanning...',
    'narrative.title': 'Market', 'narrative.subtitle': 'Narrative', 'narrative.description': 'JARVIS narrates the market story.', 'narrative.generate': 'Generate', 'narrative.generating': 'Generating...',
    'fusion.title': 'JARVIS 글로벌 퓨전',
    'fusion.subtitle': '세계 데이터 크로스피드 — 뉴스 × 가격 × 지정학 → 신호',
    'fusion.live': '실시간',
    'fusion.last_updated': '{s}초 전 업데이트',
    'fusion.refresh': '새로고침',
    'fusion.events_captured': '캡처된 이벤트',
    'fusion.assets_analyzed': '분석된 자산',
    'fusion.active_signals': '활성 신호',
    'fusion.macro_regime': '매크로 레짐',
    'fusion.executive_summary': 'JARVIS 요약 보고서',
    'fusion.cross_asset_signals': '크로스 에셋 신호',
    'fusion.asset_impact': '자산 영향 지도',
    'fusion.correlation': '실시간 크로스 에셋 상관관계',
    'fusion.market_temp_hot': '과열',
    'fusion.market_temp_warm': '온화',
    'fusion.market_temp_cool': '냉각',
    'fusion.signal_buy': '매수',
    'fusion.signal_sell': '매도',
    'fusion.signal_hold': '보유',
    'fusion.signal_watch': '관찰',
    'fusion.confidence': '신뢰도',
    'fusion.trade_ideas': '트레이드 아이디어',
    'fusion.impact_high': '높음',
    'fusion.impact_medium': '중간',
    'fusion.impact_low': '낮음',
    'fusion.bias_bullish': '강세',
    'fusion.bias_bearish': '약세',
    'fusion.bias_neutral': '중립',
    'fusion.key_drivers': '핵심 요인',
    'fusion.risk_level': '위험',
    'fusion.expand': '펼치기',
    'fusion.collapse': '접기',
    'fusion.no_events': '아직 캡처된 이벤트 없음',
    'fusion.loading': '글로벌 데이터 동기화 중...',
    'fusion.error_retry': '재시도',
    'fusion.analyze_event': '이벤트 분석',
    'fusion.analyze_placeholder': '뉴스 헤드라인을 붙여넣어 시장 영향을 분석하세요...',
    'fusion.regime_risk_on': '위험 선호',
    'fusion.regime_risk_off': '위험 회피',
    'fusion.regime_stagflation': '스태그플레이션',
    'fusion.regime_goldilocks': '골디락스',
    'fusion.regime_crisis': '위기',
    'fusion.filter_all': '전체',
    'fusion.filter_geo': '지정학',
    'fusion.filter_macro': '매크로',
    'fusion.filter_crypto': '크립토',
    'fusion.filter_equity': '주식',
    'fusion.filter_commodity': '원자재',
    'fusion.filter_forex': '외환',
    'fusion.source': '출처',
    'fusion.affected': '영향 자산',
    'fusion.divergence': '이탈',
    'fusion.corr_high_pos': '강한 양의 상관관계',
    'fusion.corr_high_neg': '강한 음의 상관관계',
    'fusion.corr_low': '약한 상관관계',
    'labs.title': 'AUREOS LABS',
    'labs.subtitle': '활발히 개발 중인 기능. 품질 기준 충족 시 출시.',
    'labs.pipeline': '개발 중인 기능',
    'labs.q2': 'Q2 2026',
    'labs.q3': 'Q3 2026',
    'labs.q4': 'Q4 2026',
    'labs.footer': '모든 Labs 기능은 이미 작동하는 백엔드가 있습니다 — 공개 출시 전 UX를 개선 중입니다.',
    'labs.tagline': '30+ 기능 · 1 핵심 제품 · 0 품질 타협',
    'jarvis.live': '실시간',
    'jarvis.updated': '{m}분 전 업데이트',
    'jarvis.refresh': '새로고침',
    'jarvis.listen': '듣기',
    'jarvis.stop': '정지',
    'jarvis.read_more': '더 읽기',
    'jarvis.read_less': '접기',
    'jarvis.geopolitical_events': '지정학적 이벤트',
    'jarvis.predictions': 'AI 예측',
    'jarvis.confidence': '신뢰도',
    'jarvis.loading': 'JARVIS가 글로벌 이벤트를 분석 중...',
    'jarvis.error': 'JARVIS에 연결할 수 없습니다',
    'jarvis.retry': '재시도',
    'jarvis.impact_high': '높은 영향',
    'jarvis.impact_medium': '중간 영향',
    'jarvis.impact_low': '낮은 영향',
    'heatmap.title': '상관관계 행렬',
    'heatmap.tooltip_pair': '{a} / {b}',
    'heatmap.divergence_warning': '레짐 이탈',
    'heatmap.legend_negative': '강한 역상관',
    'heatmap.legend_neutral': '상관 없음',
    'heatmap.legend_positive': '강한 양상관',
    'nav.global_fusion': '글로벌 퓨전',
    'nav.my_signals': '내 신호',
    'nav.analyze_asset': '자산 분석',
    'nav.labs': '랩스',
  },
  ar: {
    'nav.intelligence': 'Intelligence', 'nav.analysis': 'Analysis', 'nav.trading': 'Trading', 'nav.unfair_advantage': 'Unfair Advantage', 'nav.system': 'System',
    'nav.command_center': 'Command Center', 'nav.jarvis_hub': 'JARVIS Hub', 'nav.intel_terminal': 'Intel Terminal', 'nav.intel_mode': 'Intel Mode', 'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica', 'nav.deep_analysis': 'Deep Analysis', 'nav.market_scanner': 'Market Scanner', 'nav.signal_timeline': 'Signal Timeline', 'nav.capital_flow': 'Capital Flow',
    'nav.market_dna': 'Market DNA', 'nav.sentiment': 'Sentiment', 'nav.weekly_digest': 'Weekly Digest', 'nav.my_portfolio': 'My Portfolio', 'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading', 'nav.trade_simulator': 'Trade Simulator', 'nav.decision_replay': 'Decision Replay', 'nav.trader_dna': 'Trader DNA', 'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Global Intel', 'nav.opp_scanner': 'Opp Scanner', 'nav.top_traders': 'Top Traders', 'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score', 'nav.aureos_tokens': 'Aureos Tokens', 'nav.track_record': 'Track Record', 'nav.settings': 'Settings', 'nav.alpha_radar': 'Alpha Radar', 'nav.market_narrative': 'Narrative',
    'dashboard.greeting_morning': 'Good morning', 'dashboard.greeting_afternoon': 'Good afternoon', 'dashboard.greeting_evening': 'Good evening',
    'dashboard.market_pulse': 'MARKET PULSE', 'dashboard.my_portfolio': 'MY PORTFOLIO', 'dashboard.intelligence': 'INTELLIGENCE', 'dashboard.global_markets': 'GLOBAL MARKETS',
    'common.refresh': 'Refresh', 'common.loading': 'Loading...', 'common.subscribe': 'Subscribe', 'common.view_all': 'View All', 'common.narrate': 'Narrate with JARVIS', 'common.narrating': 'Narrating...',
    'common.search': 'Search assets, commands, or ask JARVIS...',
    'alpha.title': 'Alpha', 'alpha.subtitle': 'Radar', 'alpha.description': 'Where is the edge right now?', 'alpha.scan': 'Scan Alpha', 'alpha.scanning': 'Scanning...',
    'narrative.title': 'Market', 'narrative.subtitle': 'Narrative', 'narrative.description': 'JARVIS narrates the market story.', 'narrative.generate': 'Generate', 'narrative.generating': 'Generating...',
    'fusion.title': 'JARVIS الاندماج العالمي',
    'fusion.subtitle': 'تقاطع البيانات العالمية — أخبار × أسعار × جيوسياسية → إشارات',
    'fusion.live': 'مباشر',
    'fusion.last_updated': 'تم التحديث منذ {s} ثانية',
    'fusion.refresh': 'تحديث',
    'fusion.events_captured': 'الأحداث المُلتقطة',
    'fusion.assets_analyzed': 'الأصول المحللة',
    'fusion.active_signals': 'الإشارات النشطة',
    'fusion.macro_regime': 'النظام الكلي',
    'fusion.executive_summary': 'الملخص التنفيذي لـ JARVIS',
    'fusion.cross_asset_signals': 'إشارات متعددة الأصول',
    'fusion.asset_impact': 'خريطة تأثير الأصول',
    'fusion.correlation': 'الارتباط العابر للأصول في الوقت الفعلي',
    'fusion.market_temp_hot': 'ساخن',
    'fusion.market_temp_warm': 'دافئ',
    'fusion.market_temp_cool': 'بارد',
    'fusion.signal_buy': 'شراء',
    'fusion.signal_sell': 'بيع',
    'fusion.signal_hold': 'احتفاظ',
    'fusion.signal_watch': 'مراقبة',
    'fusion.confidence': 'الثقة',
    'fusion.trade_ideas': 'أفكار التداول',
    'fusion.impact_high': 'مرتفع',
    'fusion.impact_medium': 'متوسط',
    'fusion.impact_low': 'منخفض',
    'fusion.bias_bullish': 'صعودي',
    'fusion.bias_bearish': 'هبوطي',
    'fusion.bias_neutral': 'محايد',
    'fusion.key_drivers': 'العوامل الرئيسية',
    'fusion.risk_level': 'المخاطرة',
    'fusion.expand': 'توسيع',
    'fusion.collapse': 'طي',
    'fusion.no_events': 'لم يتم التقاط أي أحداث بعد',
    'fusion.loading': 'جارٍ مزامنة البيانات العالمية...',
    'fusion.error_retry': 'إعادة المحاولة',
    'fusion.analyze_event': 'تحليل الحدث',
    'fusion.analyze_placeholder': 'الصق أي عنوان إخباري لتحليل تأثيره على السوق...',
    'fusion.regime_risk_on': 'تحمل المخاطر',
    'fusion.regime_risk_off': 'تجنب المخاطر',
    'fusion.regime_stagflation': 'ركود تضخمي',
    'fusion.regime_goldilocks': 'توازن مثالي',
    'fusion.regime_crisis': 'أزمة',
    'fusion.filter_all': 'الكل',
    'fusion.filter_geo': 'جيوسياسي',
    'fusion.filter_macro': 'كلي',
    'fusion.filter_crypto': 'تشفير',
    'fusion.filter_equity': 'أسهم',
    'fusion.filter_commodity': 'سلع',
    'fusion.filter_forex': 'عملات',
    'fusion.source': 'المصدر',
    'fusion.affected': 'المتأثرون',
    'fusion.divergence': 'تباين',
    'fusion.corr_high_pos': 'ارتباط إيجابي قوي',
    'fusion.corr_high_neg': 'ارتباط عكسي قوي',
    'fusion.corr_low': 'ارتباط ضعيف',
    'labs.title': 'AUREOS LABS',
    'labs.subtitle': 'ميزات قيد التطوير النشط. كل ميزة تُطلق عند استيفاء معايير الجودة.',
    'labs.pipeline': 'ميزات في خط الإنتاج',
    'labs.q2': 'Q2 2026',
    'labs.q3': 'Q3 2026',
    'labs.q4': 'Q4 2026',
    'labs.footer': 'كل ميزة Labs لديها بالفعل نظام خلفي يعمل — نحن نُحسّن تجربة المستخدم قبل الإطلاق العام.',
    'labs.tagline': '30+ ميزة · منتج أساسي واحد · 0 تنازل عن الجودة',
    'jarvis.live': 'مباشر',
    'jarvis.updated': 'تم التحديث منذ {m} دقيقة',
    'jarvis.refresh': 'تحديث',
    'jarvis.listen': 'استماع',
    'jarvis.stop': 'إيقاف',
    'jarvis.read_more': 'اقرأ المزيد',
    'jarvis.read_less': 'اقرأ أقل',
    'jarvis.geopolitical_events': 'الأحداث الجيوسياسية',
    'jarvis.predictions': 'توقعات الذكاء الاصطناعي',
    'jarvis.confidence': 'الثقة',
    'jarvis.loading': 'JARVIS يحلل الأحداث العالمية...',
    'jarvis.error': 'تعذر الاتصال بـ JARVIS',
    'jarvis.retry': 'إعادة المحاولة',
    'jarvis.impact_high': 'تأثير مرتفع',
    'jarvis.impact_medium': 'تأثير متوسط',
    'jarvis.impact_low': 'تأثير منخفض',
    'heatmap.title': 'مصفوفة الارتباط',
    'heatmap.tooltip_pair': '{a} / {b}',
    'heatmap.divergence_warning': 'تباين النظام',
    'heatmap.legend_negative': 'عكسي قوي',
    'heatmap.legend_neutral': 'لا ارتباط',
    'heatmap.legend_positive': 'إيجابي قوي',
    'nav.global_fusion': 'الاندماج العالمي',
    'nav.my_signals': 'إشاراتي',
    'nav.analyze_asset': 'تحليل الأصل',
    'nav.labs': 'المختبرات',
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('aureos_lang') || 'pt');

  const changeLang = useCallback((code) => {
    setLang(code);
    localStorage.setItem('aureos_lang', code);
  }, []);

  const t = useCallback((key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  }, [lang]);

  const langName = LANGUAGES.find(l => l.code === lang)?.label || 'English';

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t, langName, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};
