import React, { createContext, useContext, useState, useCallback } from 'react';

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be inside LanguageProvider');
  return ctx;
};

export const LANGUAGES = [
  { code: 'pt', label: 'Portugues', flag: 'BR' },
  { code: 'en', label: 'English', flag: 'US' },
  { code: 'es', label: 'Espanol', flag: 'ES' },
  { code: 'fr', label: 'Francais', flag: 'FR' },
  { code: 'de', label: 'Deutsch', flag: 'DE' },
  { code: 'zh', label: 'Chinese', flag: 'CN' },
  { code: 'ja', label: 'Japanese', flag: 'JP' },
  { code: 'ko', label: 'Korean', flag: 'KR' },
  { code: 'ar', label: 'Arabic', flag: 'SA' },
];

const translations = {
  pt: {
    'nav.intelligence': 'Inteligencia',
    'nav.analysis': 'Analise',
    'nav.trading': 'Trading',
    'nav.unfair_advantage': 'Vantagem Injusta',
    'nav.system': 'Sistema',
    'nav.command_center': 'Centro de Comando',
    'nav.jarvis_hub': 'JARVIS Hub',
    'nav.intel_terminal': 'Terminal Intel',
    'nav.intel_mode': 'Modo Intel',
    'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica',
    'nav.deep_analysis': 'Analise Profunda',
    'nav.market_scanner': 'Scanner de Mercado',
    'nav.signal_timeline': 'Timeline de Sinais',
    'nav.capital_flow': 'Fluxo de Capital',
    'nav.market_dna': 'DNA do Mercado',
    'nav.sentiment': 'Sentimento',
    'nav.weekly_digest': 'Resumo Semanal',
    'nav.my_portfolio': 'Meu Portfolio',
    'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading',
    'nav.trade_simulator': 'Simulador de Trade',
    'nav.decision_replay': 'Replay de Decisao',
    'nav.trader_dna': 'DNA do Trader',
    'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Intel Global',
    'nav.opp_scanner': 'Scanner de Opp.',
    'nav.top_traders': 'Top Traders',
    'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.share_cards': 'Share Cards',
    'nav.evolution': 'Evolution',
    'nav.strategy_creator': 'Create Strategy',
    'nav.aureos_score': 'Aureos Score',
    'nav.aureos_tokens': 'Aureos Tokens',
    'nav.track_record': 'Track Record',
    'nav.settings': 'Configuracoes',
    'nav.alpha_radar': 'Alpha Radar',
    'nav.market_narrative': 'Narrativa',
    'nav.copy_trading': 'Copy Trading',
    'nav.liquidity_map': 'Mapa Liquidez',
    'nav.second_brain': 'Second Brain',
    'nav.daily_missions': 'Missoes Diarias',
    'nav.correlation': 'Correlacao',
    'nav.econ_calendar': 'Calendario Econ.',
    'nav.trade_journal': 'Diario de Trades',
    'nav.quiz': 'Quiz',
    'nav.referral': 'Indicacao',
    'nav.ecosystem': 'Ecossistema',
    'dashboard.greeting_morning': 'Bom dia',
    'dashboard.greeting_afternoon': 'Boa tarde',
    'dashboard.greeting_evening': 'Boa noite',
    'dashboard.market_pulse': 'PULSO DO MERCADO',
    'dashboard.my_portfolio': 'MEU PORTFOLIO',
    'dashboard.intelligence': 'INTELIGENCIA DO DIA',
    'dashboard.global_markets': 'MERCADOS GLOBAIS',
    'common.refresh': 'Atualizar',
    'common.loading': 'Carregando...',
    'common.subscribe': 'Assinar',
    'common.view_all': 'Ver Tudo',
    'common.narrate': 'Narrar com JARVIS',
    'common.narrating': 'Narrando...',
    'common.search': 'Buscar ativos, comandos ou pergunte ao JARVIS...',
    'alpha.title': 'Alpha',
    'alpha.subtitle': 'Radar',
    'alpha.description': 'Onde esta a vantagem agora? Top oportunidades globais com score + probabilidade.',
    'alpha.scan': 'Escanear Alpha',
    'alpha.scanning': 'Escaneando...',
    'narrative.title': 'Narrativa do',
    'narrative.subtitle': 'Mercado',
    'narrative.description': 'JARVIS narra a historia do mercado em tempo real.',
    'narrative.generate': 'Gerar Narrativa',
    'narrative.generating': 'Gerando...',
    'copy.title': 'Copy Trading', 'copy.subtitle': 'Inteligente', 'copy.desc': 'Traders filtrados por IA. Apenas traders consistentes e de baixo risco. JARVIS adapta ao seu DNA.',
    'copy.ai_rating': 'Rating IA', 'copy.win_rate': 'Taxa Vitoria', 'copy.pnl': 'P&L', 'copy.risk': 'Risco', 'copy.btn': 'Copiar',
    'liquidity.title': 'Mapa de', 'liquidity.subtitle': 'Liquidez', 'liquidity.desc': 'Para onde o dinheiro esta fluindo?',
    'liquidity.capital_flows': 'Fluxos de Capital', 'liquidity.sector_flows': 'Fluxos por Setor', 'liquidity.zones': 'Zonas de Liquidez',
    'brain.title': 'Aureos', 'brain.subtitle': 'Second Brain', 'brain.desc': 'JARVIS lembra de tudo. Sua memoria completa de trading.',
    'brain.total_decisions': 'Total Decisoes', 'brain.win_rate': 'Taxa Vitoria', 'brain.total_pnl': 'P&L Total', 'brain.score': 'Aureos Score',
    'brain.patterns': 'Padroes Detectados', 'brain.insights': 'Insights do JARVIS', 'brain.evolution': 'Evolucao Mensal', 'brain.dna_profile': 'Perfil DNA',
    'brain.no_insights': 'Execute mais trades para o JARVIS aprender seus padroes.',
    'brain.best_day': 'Melhor Dia', 'brain.worst_day': 'Pior Dia', 'brain.best_asset': 'Melhor Ativo', 'brain.worst_asset': 'Pior Ativo', 'brain.asset_perf': 'Performance por Ativo',
    'missions.title': 'Missoes', 'missions.subtitle': 'Diarias', 'missions.desc': 'Complete missoes para ganhar Aureos Tokens',
    'missions.total_reward': 'Recompensa Total', 'missions.completed': 'completadas', 'missions.complete_btn': 'Completar',
    'journal.title': 'Diario de', 'journal.subtitle': 'Trades IA', 'journal.desc': 'JARVIS analisa cada trade com nota + insight',
    'journal.empty': 'Nenhum trade fechado. Seu diario sera construido automaticamente.',
    'corr.title': 'Matriz de', 'corr.subtitle': 'Correlacao', 'corr.desc': 'Correlacoes em tempo real entre os principais ativos',
    'calendar.title': 'Calendario', 'calendar.subtitle': 'Economico', 'calendar.desc': 'Eventos com analise de impacto por JARVIS',
    'calendar.ai_impact': 'Analise de Impacto JARVIS', 'calendar.previous': 'Anterior', 'calendar.forecast': 'Previsao',
    'quiz.title': 'Quiz de', 'quiz.subtitle': 'Trading', 'quiz.desc': 'Teste seu conhecimento. Ganhe 1 AT por resposta correta.',
    'quiz.submit': 'Enviar Quiz', 'quiz.new': 'Novo Quiz', 'quiz.earned': 'AT ganhos', 'quiz.correct': 'corretas',
    'referral.title': 'Programa de', 'referral.subtitle': 'Indicacao', 'referral.desc': 'Convide amigos.',
    'referral.code': 'Seu Codigo de Indicacao', 'referral.referrals': 'Indicacoes', 'referral.tokens_earned': 'Tokens Ganhos',
    'referral.how': 'Como funciona', 'referral.step1': 'Compartilhe seu codigo com amigos', 'referral.step2': 'Eles se cadastram com seu codigo',
    'referral.twitter': 'Compartilhar no Twitter', 'referral.whatsapp': 'Compartilhar no WhatsApp',
  },
  en: {
    'nav.intelligence': 'Intelligence',
    'nav.analysis': 'Analysis',
    'nav.trading': 'Trading',
    'nav.unfair_advantage': 'Unfair Advantage',
    'nav.system': 'System',
    'nav.command_center': 'Command Center',
    'nav.jarvis_hub': 'JARVIS Hub',
    'nav.intel_terminal': 'Intel Terminal',
    'nav.intel_mode': 'Intel Mode',
    'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica',
    'nav.deep_analysis': 'Deep Analysis',
    'nav.market_scanner': 'Market Scanner',
    'nav.signal_timeline': 'Signal Timeline',
    'nav.capital_flow': 'Capital Flow',
    'nav.market_dna': 'Market DNA',
    'nav.sentiment': 'Sentiment',
    'nav.weekly_digest': 'Weekly Digest',
    'nav.my_portfolio': 'My Portfolio',
    'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading',
    'nav.trade_simulator': 'Trade Simulator',
    'nav.decision_replay': 'Decision Replay',
    'nav.trader_dna': 'Trader DNA',
    'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Global Intel',
    'nav.opp_scanner': 'Opp Scanner',
    'nav.top_traders': 'Top Traders',
    'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.share_cards': 'Share Cards',
    'nav.evolution': 'Evolution',
    'nav.strategy_creator': 'Create Strategy',
    'nav.aureos_score': 'Aureos Score',
    'nav.aureos_tokens': 'Aureos Tokens',
    'nav.track_record': 'Track Record',
    'nav.settings': 'Settings',
    'nav.alpha_radar': 'Alpha Radar',
    'nav.market_narrative': 'Narrative',
    'dashboard.greeting_morning': 'Good morning',
    'dashboard.greeting_afternoon': 'Good afternoon',
    'dashboard.greeting_evening': 'Good evening',
    'dashboard.market_pulse': 'MARKET PULSE',
    'dashboard.my_portfolio': 'MY PORTFOLIO',
    'dashboard.intelligence': 'INTELLIGENCE OF THE DAY',
    'dashboard.global_markets': 'GLOBAL MARKETS',
    'common.refresh': 'Refresh',
    'common.loading': 'Loading...',
    'common.subscribe': 'Subscribe',
    'common.view_all': 'View All',
    'common.narrate': 'Narrate with JARVIS',
    'common.narrating': 'Narrating...',
    'common.search': 'Search assets, commands, or ask JARVIS...',
    'alpha.title': 'Alpha',
    'alpha.subtitle': 'Radar',
    'alpha.description': 'Where is the edge right now? Top global opportunities with score + probability.',
    'alpha.scan': 'Scan for Alpha',
    'alpha.scanning': 'Scanning...',
    'narrative.title': 'Market',
    'narrative.subtitle': 'Narrative',
    'narrative.description': 'JARVIS narrates the market story in real time.',
    'narrative.generate': 'Generate Narrative',
    'narrative.generating': 'Generating...',
    'copy.title': 'Copy Trading', 'copy.subtitle': 'Intelligent', 'copy.desc': 'AI-filtered traders. Only consistent, low-risk, high-score traders. JARVIS adapts to your DNA.',
    'copy.ai_rating': 'AI Rating', 'copy.win_rate': 'Win Rate', 'copy.pnl': 'P&L', 'copy.risk': 'Risk', 'copy.btn': 'Copy',
    'liquidity.title': 'Liquidity', 'liquidity.subtitle': 'Intelligence', 'liquidity.desc': 'Where is the money flowing?',
    'liquidity.capital_flows': 'Capital Flows', 'liquidity.sector_flows': 'Sector Flows', 'liquidity.zones': 'Liquidity Zones',
    'brain.title': 'Aureos', 'brain.subtitle': 'Second Brain', 'brain.desc': 'JARVIS remembers everything. Your complete trading memory.',
    'brain.total_decisions': 'Total Decisions', 'brain.win_rate': 'Win Rate', 'brain.total_pnl': 'Total P&L', 'brain.score': 'Aureos Score',
    'brain.patterns': 'Patterns Detected', 'brain.insights': 'JARVIS Insights', 'brain.evolution': 'Monthly Evolution', 'brain.dna_profile': 'DNA Profile',
    'brain.no_insights': 'Execute more trades so JARVIS can learn your patterns.',
    'brain.best_day': 'Best Day', 'brain.worst_day': 'Worst Day', 'brain.best_asset': 'Best Asset', 'brain.worst_asset': 'Worst Asset', 'brain.asset_perf': 'Asset Performance',
    'missions.title': 'Daily', 'missions.subtitle': 'Missions', 'missions.desc': 'Complete missions to earn Aureos Tokens',
    'missions.total_reward': 'Total Reward', 'missions.completed': 'completed', 'missions.complete_btn': 'Complete',
    'journal.title': 'AI Trade', 'journal.subtitle': 'Journal', 'journal.desc': 'JARVIS auto-analyzes every trade with grade + insight',
    'journal.empty': 'No closed trades yet. Your journal will build automatically.',
    'corr.title': 'Correlation', 'corr.subtitle': 'Matrix', 'corr.desc': 'Real-time correlations between major assets',
    'calendar.title': 'Economic', 'calendar.subtitle': 'Calendar', 'calendar.desc': 'Key events with AI impact analysis by JARVIS',
    'calendar.ai_impact': 'JARVIS AI Impact Analysis', 'calendar.previous': 'Previous', 'calendar.forecast': 'Forecast',
    'quiz.title': 'Trading', 'quiz.subtitle': 'Quiz', 'quiz.desc': 'Test your knowledge. Earn 1 AT per correct answer.',
    'quiz.submit': 'Submit Quiz', 'quiz.new': 'New Quiz', 'quiz.earned': 'AT earned', 'quiz.correct': 'correct',
    'referral.title': 'Referral', 'referral.subtitle': 'Program', 'referral.desc': 'Invite friends.',
    'referral.code': 'Your Referral Code', 'referral.referrals': 'Referrals', 'referral.tokens_earned': 'Tokens Earned',
    'referral.how': 'How it works', 'referral.step1': 'Share your unique code with friends', 'referral.step2': 'They sign up using your code',
    'referral.twitter': 'Share on Twitter', 'referral.whatsapp': 'Share on WhatsApp',
  },
  es: {
    'nav.intelligence': 'Inteligencia',
    'nav.analysis': 'Analisis',
    'nav.trading': 'Trading',
    'nav.unfair_advantage': 'Ventaja Injusta',
    'nav.system': 'Sistema',
    'nav.command_center': 'Centro de Comando',
    'nav.jarvis_hub': 'JARVIS Hub',
    'nav.intel_terminal': 'Terminal Intel',
    'nav.intel_mode': 'Modo Intel',
    'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica',
    'nav.deep_analysis': 'Analisis Profundo',
    'nav.market_scanner': 'Escaner de Mercado',
    'nav.signal_timeline': 'Linea de Senales',
    'nav.capital_flow': 'Flujo de Capital',
    'nav.market_dna': 'ADN del Mercado',
    'nav.sentiment': 'Sentimiento',
    'nav.weekly_digest': 'Resumen Semanal',
    'nav.my_portfolio': 'Mi Portafolio',
    'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading',
    'nav.trade_simulator': 'Simulador de Trade',
    'nav.decision_replay': 'Replay de Decision',
    'nav.trader_dna': 'ADN del Trader',
    'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Intel Global',
    'nav.opp_scanner': 'Escaner de Opp.',
    'nav.top_traders': 'Top Traders',
    'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.share_cards': 'Share Cards',
    'nav.evolution': 'Evolution',
    'nav.strategy_creator': 'Create Strategy',
    'nav.aureos_score': 'Aureos Score',
    'nav.aureos_tokens': 'Aureos Tokens',
    'nav.track_record': 'Track Record',
    'nav.settings': 'Ajustes',
    'nav.alpha_radar': 'Alpha Radar',
    'nav.market_narrative': 'Narrativa',
    'dashboard.greeting_morning': 'Buenos dias',
    'dashboard.greeting_afternoon': 'Buenas tardes',
    'dashboard.greeting_evening': 'Buenas noches',
    'dashboard.market_pulse': 'PULSO DEL MERCADO',
    'dashboard.my_portfolio': 'MI PORTAFOLIO',
    'dashboard.intelligence': 'INTELIGENCIA DEL DIA',
    'dashboard.global_markets': 'MERCADOS GLOBALES',
    'common.refresh': 'Actualizar',
    'common.loading': 'Cargando...',
    'common.subscribe': 'Suscribirse',
    'common.view_all': 'Ver Todo',
    'common.narrate': 'Narrar con JARVIS',
    'common.narrating': 'Narrando...',
    'common.search': 'Buscar activos, comandos o preguntar a JARVIS...',
    'alpha.title': 'Alpha',
    'alpha.subtitle': 'Radar',
    'alpha.description': 'Donde esta la ventaja ahora? Top oportunidades globales con score + probabilidad.',
    'alpha.scan': 'Escanear Alpha',
    'alpha.scanning': 'Escaneando...',
    'narrative.title': 'Narrativa del',
    'narrative.subtitle': 'Mercado',
    'narrative.description': 'JARVIS narra la historia del mercado en tiempo real.',
    'narrative.generate': 'Generar Narrativa',
    'narrative.generating': 'Generando...',
    'copy.title': 'Copy Trading', 'copy.subtitle': 'Inteligente', 'copy.desc': 'Traders filtrados por IA. Solo traders consistentes y de bajo riesgo. JARVIS se adapta a tu ADN.',
    'copy.ai_rating': 'Rating IA', 'copy.win_rate': 'Tasa Victoria', 'copy.pnl': 'P&L', 'copy.risk': 'Riesgo', 'copy.btn': 'Copiar',
    'liquidity.title': 'Mapa de', 'liquidity.subtitle': 'Liquidez', 'liquidity.desc': 'A donde fluye el dinero?',
    'liquidity.capital_flows': 'Flujos de Capital', 'liquidity.sector_flows': 'Flujos por Sector', 'liquidity.zones': 'Zonas de Liquidez',
    'brain.title': 'Aureos', 'brain.subtitle': 'Second Brain', 'brain.desc': 'JARVIS recuerda todo. Tu memoria completa de trading.',
    'brain.total_decisions': 'Total Decisiones', 'brain.win_rate': 'Tasa Victoria', 'brain.total_pnl': 'P&L Total', 'brain.score': 'Aureos Score',
    'brain.patterns': 'Patrones Detectados', 'brain.insights': 'Insights de JARVIS', 'brain.evolution': 'Evolucion Mensual', 'brain.dna_profile': 'Perfil ADN',
    'brain.no_insights': 'Ejecuta mas trades para que JARVIS aprenda tus patrones.',
    'brain.best_day': 'Mejor Dia', 'brain.worst_day': 'Peor Dia', 'brain.best_asset': 'Mejor Activo', 'brain.worst_asset': 'Peor Activo', 'brain.asset_perf': 'Rendimiento por Activo',
    'missions.title': 'Misiones', 'missions.subtitle': 'Diarias', 'missions.desc': 'Completa misiones para ganar Aureos Tokens',
    'missions.total_reward': 'Recompensa Total', 'missions.completed': 'completadas', 'missions.complete_btn': 'Completar',
    'journal.title': 'Diario de', 'journal.subtitle': 'Trades IA', 'journal.desc': 'JARVIS analiza cada trade con nota + insight',
    'journal.empty': 'Sin trades cerrados aun. Tu diario se construira automaticamente.',
    'corr.title': 'Matriz de', 'corr.subtitle': 'Correlacion', 'corr.desc': 'Correlaciones en tiempo real entre los principales activos',
    'calendar.title': 'Calendario', 'calendar.subtitle': 'Economico', 'calendar.desc': 'Eventos con analisis de impacto por JARVIS',
    'calendar.ai_impact': 'Analisis de Impacto JARVIS', 'calendar.previous': 'Anterior', 'calendar.forecast': 'Pronostico',
    'quiz.title': 'Quiz de', 'quiz.subtitle': 'Trading', 'quiz.desc': 'Pon a prueba tu conocimiento. Gana 1 AT por respuesta correcta.',
    'quiz.submit': 'Enviar Quiz', 'quiz.new': 'Nuevo Quiz', 'quiz.earned': 'AT ganados', 'quiz.correct': 'correctas',
    'referral.title': 'Programa de', 'referral.subtitle': 'Referidos', 'referral.desc': 'Invita amigos.',
    'referral.code': 'Tu Codigo de Referido', 'referral.referrals': 'Referidos', 'referral.tokens_earned': 'Tokens Ganados',
    'referral.how': 'Como funciona', 'referral.step1': 'Comparte tu codigo con amigos', 'referral.step2': 'Se registran con tu codigo',
    'referral.twitter': 'Compartir en Twitter', 'referral.whatsapp': 'Compartir en WhatsApp',
  },
  fr: {
    'nav.intelligence': 'Intelligence', 'nav.analysis': 'Analyse', 'nav.trading': 'Trading', 'nav.unfair_advantage': 'Avantage Injuste', 'nav.system': 'Systeme',
    'nav.command_center': 'Centre de Commande', 'nav.jarvis_hub': 'JARVIS Hub', 'nav.intel_terminal': 'Terminal Intel', 'nav.intel_mode': 'Mode Intel', 'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica', 'nav.deep_analysis': 'Analyse Profonde', 'nav.market_scanner': 'Scanner Marche', 'nav.signal_timeline': 'Chronologie Signaux', 'nav.capital_flow': 'Flux Capital',
    'nav.market_dna': 'ADN Marche', 'nav.sentiment': 'Sentiment', 'nav.weekly_digest': 'Resume Hebdo', 'nav.my_portfolio': 'Mon Portfolio', 'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading', 'nav.trade_simulator': 'Simulateur Trade', 'nav.decision_replay': 'Replay Decision', 'nav.trader_dna': 'ADN Trader', 'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Intel Global', 'nav.opp_scanner': 'Scanner Opp.', 'nav.top_traders': 'Top Traders', 'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score', 'nav.aureos_tokens': 'Aureos Tokens', 'nav.track_record': 'Track Record', 'nav.settings': 'Parametres', 'nav.alpha_radar': 'Alpha Radar', 'nav.market_narrative': 'Narratif',
    'dashboard.greeting_morning': 'Bonjour', 'dashboard.greeting_afternoon': 'Bon apres-midi', 'dashboard.greeting_evening': 'Bonsoir',
    'dashboard.market_pulse': 'POULS DU MARCHE', 'dashboard.my_portfolio': 'MON PORTFOLIO', 'dashboard.intelligence': 'INTELLIGENCE DU JOUR', 'dashboard.global_markets': 'MARCHES MONDIAUX',
    'common.refresh': 'Rafraichir', 'common.loading': 'Chargement...', 'common.subscribe': 'Souscrire', 'common.view_all': 'Voir Tout', 'common.narrate': 'Narrer avec JARVIS', 'common.narrating': 'Narration...',
    'common.search': 'Rechercher actifs, commandes ou demander a JARVIS...',
    'alpha.title': 'Alpha', 'alpha.subtitle': 'Radar', 'alpha.description': 'Ou est lavantage maintenant?', 'alpha.scan': 'Scanner Alpha', 'alpha.scanning': 'Scan en cours...',
    'narrative.title': 'Narratif du', 'narrative.subtitle': 'Marche', 'narrative.description': 'JARVIS raconte lhistoire du marche en temps reel.', 'narrative.generate': 'Generer Narratif', 'narrative.generating': 'Generation...',
  },
  de: {
    'nav.intelligence': 'Intelligenz', 'nav.analysis': 'Analyse', 'nav.trading': 'Trading', 'nav.unfair_advantage': 'Unfairer Vorteil', 'nav.system': 'System',
    'nav.command_center': 'Kommandozentrale', 'nav.jarvis_hub': 'JARVIS Hub', 'nav.intel_terminal': 'Intel Terminal', 'nav.intel_mode': 'Intel Modus', 'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica', 'nav.deep_analysis': 'Tiefenanalyse', 'nav.market_scanner': 'Marktscanner', 'nav.signal_timeline': 'Signal-Zeitleiste', 'nav.capital_flow': 'Kapitalfluss',
    'nav.market_dna': 'Markt-DNA', 'nav.sentiment': 'Stimmung', 'nav.weekly_digest': 'Wochenubersicht', 'nav.my_portfolio': 'Mein Portfolio', 'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading', 'nav.trade_simulator': 'Trade-Simulator', 'nav.decision_replay': 'Entscheidungs-Replay', 'nav.trader_dna': 'Trader-DNA', 'nav.marketplace': 'Marktplatz',
    'nav.global_intel': 'Globale Intel', 'nav.opp_scanner': 'Opp-Scanner', 'nav.top_traders': 'Top Trader', 'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score', 'nav.aureos_tokens': 'Aureos Tokens', 'nav.track_record': 'Track Record', 'nav.settings': 'Einstellungen', 'nav.alpha_radar': 'Alpha Radar', 'nav.market_narrative': 'Narrativ',
    'dashboard.greeting_morning': 'Guten Morgen', 'dashboard.greeting_afternoon': 'Guten Tag', 'dashboard.greeting_evening': 'Guten Abend',
    'dashboard.market_pulse': 'MARKTPULS', 'dashboard.my_portfolio': 'MEIN PORTFOLIO', 'dashboard.intelligence': 'INTELLIGENZ DES TAGES', 'dashboard.global_markets': 'GLOBALE MARKTE',
    'common.refresh': 'Aktualisieren', 'common.loading': 'Laden...', 'common.subscribe': 'Abonnieren', 'common.view_all': 'Alle ansehen', 'common.narrate': 'Mit JARVIS erzahlen', 'common.narrating': 'Erzahlen...',
    'common.search': 'Assets, Befehle suchen oder JARVIS fragen...',
    'alpha.title': 'Alpha', 'alpha.subtitle': 'Radar', 'alpha.description': 'Wo liegt der Vorteil jetzt?', 'alpha.scan': 'Alpha scannen', 'alpha.scanning': 'Scannen...',
    'narrative.title': 'Markt', 'narrative.subtitle': 'Narrativ', 'narrative.description': 'JARVIS erzahlt die Marktgeschichte in Echtzeit.', 'narrative.generate': 'Narrativ generieren', 'narrative.generating': 'Generieren...',
  },
  zh: {
    'nav.intelligence': 'Intelligence', 'nav.analysis': 'Analysis', 'nav.trading': 'Trading', 'nav.unfair_advantage': 'Unfair Advantage', 'nav.system': 'System',
    'nav.command_center': 'Command Center', 'nav.jarvis_hub': 'JARVIS Hub', 'nav.intel_terminal': 'Intel Terminal', 'nav.intel_mode': 'Intel Mode', 'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica', 'nav.deep_analysis': 'Deep Analysis', 'nav.market_scanner': 'Market Scanner', 'nav.signal_timeline': 'Signal Timeline', 'nav.capital_flow': 'Capital Flow',
    'nav.market_dna': 'Market DNA', 'nav.sentiment': 'Sentiment', 'nav.weekly_digest': 'Weekly Digest', 'nav.my_portfolio': 'My Portfolio', 'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading', 'nav.trade_simulator': 'Trade Simulator', 'nav.decision_replay': 'Decision Replay', 'nav.trader_dna': 'Trader DNA', 'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Global Intel', 'nav.opp_scanner': 'Opp Scanner', 'nav.top_traders': 'Top Traders', 'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score', 'nav.aureos_tokens': 'Aureos Tokens', 'nav.track_record': 'Track Record', 'nav.settings': 'Settings', 'nav.alpha_radar': 'Alpha Radar', 'nav.market_narrative': 'Narrative',
    'dashboard.greeting_morning': 'Good morning', 'dashboard.greeting_afternoon': 'Good afternoon', 'dashboard.greeting_evening': 'Good evening',
    'dashboard.market_pulse': 'MARKET PULSE', 'dashboard.my_portfolio': 'MY PORTFOLIO', 'dashboard.intelligence': 'INTELLIGENCE', 'dashboard.global_markets': 'GLOBAL MARKETS',
    'common.refresh': 'Refresh', 'common.loading': 'Loading...', 'common.subscribe': 'Subscribe', 'common.view_all': 'View All', 'common.narrate': 'Narrate with JARVIS', 'common.narrating': 'Narrating...',
    'common.search': 'Search assets, commands, or ask JARVIS...',
    'alpha.title': 'Alpha', 'alpha.subtitle': 'Radar', 'alpha.description': 'Where is the edge right now?', 'alpha.scan': 'Scan Alpha', 'alpha.scanning': 'Scanning...',
    'narrative.title': 'Market', 'narrative.subtitle': 'Narrative', 'narrative.description': 'JARVIS narrates the market story.', 'narrative.generate': 'Generate', 'narrative.generating': 'Generating...',
  },
  ja: {
    'nav.intelligence': 'Intelligence', 'nav.analysis': 'Analysis', 'nav.trading': 'Trading', 'nav.unfair_advantage': 'Unfair Advantage', 'nav.system': 'System',
    'nav.command_center': 'Command Center', 'nav.jarvis_hub': 'JARVIS Hub', 'nav.intel_terminal': 'Intel Terminal', 'nav.intel_mode': 'Intel Mode', 'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica', 'nav.deep_analysis': 'Deep Analysis', 'nav.market_scanner': 'Market Scanner', 'nav.signal_timeline': 'Signal Timeline', 'nav.capital_flow': 'Capital Flow',
    'nav.market_dna': 'Market DNA', 'nav.sentiment': 'Sentiment', 'nav.weekly_digest': 'Weekly Digest', 'nav.my_portfolio': 'My Portfolio', 'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading', 'nav.trade_simulator': 'Trade Simulator', 'nav.decision_replay': 'Decision Replay', 'nav.trader_dna': 'Trader DNA', 'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Global Intel', 'nav.opp_scanner': 'Opp Scanner', 'nav.top_traders': 'Top Traders', 'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score', 'nav.aureos_tokens': 'Aureos Tokens', 'nav.track_record': 'Track Record', 'nav.settings': 'Settings', 'nav.alpha_radar': 'Alpha Radar', 'nav.market_narrative': 'Narrative',
    'dashboard.greeting_morning': 'Good morning', 'dashboard.greeting_afternoon': 'Good afternoon', 'dashboard.greeting_evening': 'Good evening',
    'dashboard.market_pulse': 'MARKET PULSE', 'dashboard.my_portfolio': 'MY PORTFOLIO', 'dashboard.intelligence': 'INTELLIGENCE', 'dashboard.global_markets': 'GLOBAL MARKETS',
    'common.refresh': 'Refresh', 'common.loading': 'Loading...', 'common.subscribe': 'Subscribe', 'common.view_all': 'View All', 'common.narrate': 'Narrate with JARVIS', 'common.narrating': 'Narrating...',
    'common.search': 'Search assets, commands, or ask JARVIS...',
    'alpha.title': 'Alpha', 'alpha.subtitle': 'Radar', 'alpha.description': 'Where is the edge right now?', 'alpha.scan': 'Scan Alpha', 'alpha.scanning': 'Scanning...',
    'narrative.title': 'Market', 'narrative.subtitle': 'Narrative', 'narrative.description': 'JARVIS narrates the market story.', 'narrative.generate': 'Generate', 'narrative.generating': 'Generating...',
  },
  ko: {
    'nav.intelligence': 'Intelligence', 'nav.analysis': 'Analysis', 'nav.trading': 'Trading', 'nav.unfair_advantage': 'Unfair Advantage', 'nav.system': 'System',
    'nav.command_center': 'Command Center', 'nav.jarvis_hub': 'JARVIS Hub', 'nav.intel_terminal': 'Intel Terminal', 'nav.intel_mode': 'Intel Mode', 'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica', 'nav.deep_analysis': 'Deep Analysis', 'nav.market_scanner': 'Market Scanner', 'nav.signal_timeline': 'Signal Timeline', 'nav.capital_flow': 'Capital Flow',
    'nav.market_dna': 'Market DNA', 'nav.sentiment': 'Sentiment', 'nav.weekly_digest': 'Weekly Digest', 'nav.my_portfolio': 'My Portfolio', 'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading', 'nav.trade_simulator': 'Trade Simulator', 'nav.decision_replay': 'Decision Replay', 'nav.trader_dna': 'Trader DNA', 'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Global Intel', 'nav.opp_scanner': 'Opp Scanner', 'nav.top_traders': 'Top Traders', 'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score', 'nav.aureos_tokens': 'Aureos Tokens', 'nav.track_record': 'Track Record', 'nav.settings': 'Settings', 'nav.alpha_radar': 'Alpha Radar', 'nav.market_narrative': 'Narrative',
    'dashboard.greeting_morning': 'Good morning', 'dashboard.greeting_afternoon': 'Good afternoon', 'dashboard.greeting_evening': 'Good evening',
    'dashboard.market_pulse': 'MARKET PULSE', 'dashboard.my_portfolio': 'MY PORTFOLIO', 'dashboard.intelligence': 'INTELLIGENCE', 'dashboard.global_markets': 'GLOBAL MARKETS',
    'common.refresh': 'Refresh', 'common.loading': 'Loading...', 'common.subscribe': 'Subscribe', 'common.view_all': 'View All', 'common.narrate': 'Narrate with JARVIS', 'common.narrating': 'Narrating...',
    'common.search': 'Search assets, commands, or ask JARVIS...',
    'alpha.title': 'Alpha', 'alpha.subtitle': 'Radar', 'alpha.description': 'Where is the edge right now?', 'alpha.scan': 'Scan Alpha', 'alpha.scanning': 'Scanning...',
    'narrative.title': 'Market', 'narrative.subtitle': 'Narrative', 'narrative.description': 'JARVIS narrates the market story.', 'narrative.generate': 'Generate', 'narrative.generating': 'Generating...',
  },
  ar: {
    'nav.intelligence': 'Intelligence', 'nav.analysis': 'Analysis', 'nav.trading': 'Trading', 'nav.unfair_advantage': 'Unfair Advantage', 'nav.system': 'System',
    'nav.command_center': 'Command Center', 'nav.jarvis_hub': 'JARVIS Hub', 'nav.intel_terminal': 'Intel Terminal', 'nav.intel_mode': 'Intel Mode', 'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica', 'nav.deep_analysis': 'Deep Analysis', 'nav.market_scanner': 'Market Scanner', 'nav.signal_timeline': 'Signal Timeline', 'nav.capital_flow': 'Capital Flow',
    'nav.market_dna': 'Market DNA', 'nav.sentiment': 'Sentiment', 'nav.weekly_digest': 'Weekly Digest', 'nav.my_portfolio': 'My Portfolio', 'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading', 'nav.trade_simulator': 'Trade Simulator', 'nav.decision_replay': 'Decision Replay', 'nav.trader_dna': 'Trader DNA', 'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Global Intel', 'nav.opp_scanner': 'Opp Scanner', 'nav.top_traders': 'Top Traders', 'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score', 'nav.aureos_tokens': 'Aureos Tokens', 'nav.track_record': 'Track Record', 'nav.settings': 'Settings', 'nav.alpha_radar': 'Alpha Radar', 'nav.market_narrative': 'Narrative',
    'dashboard.greeting_morning': 'Good morning', 'dashboard.greeting_afternoon': 'Good afternoon', 'dashboard.greeting_evening': 'Good evening',
    'dashboard.market_pulse': 'MARKET PULSE', 'dashboard.my_portfolio': 'MY PORTFOLIO', 'dashboard.intelligence': 'INTELLIGENCE', 'dashboard.global_markets': 'GLOBAL MARKETS',
    'common.refresh': 'Refresh', 'common.loading': 'Loading...', 'common.subscribe': 'Subscribe', 'common.view_all': 'View All', 'common.narrate': 'Narrate with JARVIS', 'common.narrating': 'Narrating...',
    'common.search': 'Search assets, commands, or ask JARVIS...',
    'alpha.title': 'Alpha', 'alpha.subtitle': 'Radar', 'alpha.description': 'Where is the edge right now?', 'alpha.scan': 'Scan Alpha', 'alpha.scanning': 'Scanning...',
    'narrative.title': 'Market', 'narrative.subtitle': 'Narrative', 'narrative.description': 'JARVIS narrates the market story.', 'narrative.generate': 'Generate', 'narrative.generating': 'Generating...',
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('aureos_lang') || 'pt');

  const changeLang = useCallback((code) => {
    setLang(code);
    localStorage.setItem('aureos_lang', code);
  }, []);

  const t = useCallback((key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  }, [lang]);

  const langName = LANGUAGES.find(l => l.code === lang)?.label || 'English';

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t, langName, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};
