import React, { createContext, useContext, useState, useCallback } from 'react';

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be inside LanguageProvider');
  return ctx;
};

export const LANGUAGES = [
  { code: 'pt', label: 'Portugues', flag: 'BR' },
  { code: 'en', label: 'English', flag: 'US' },
  { code: 'es', label: 'Espanol', flag: 'ES' },
  { code: 'fr', label: 'Francais', flag: 'FR' },
  { code: 'de', label: 'Deutsch', flag: 'DE' },
  { code: 'zh', label: 'Chinese', flag: 'CN' },
  { code: 'ja', label: 'Japanese', flag: 'JP' },
  { code: 'ko', label: 'Korean', flag: 'KR' },
  { code: 'ar', label: 'Arabic', flag: 'SA' },
];

const translations = {
  pt: {
    'nav.intelligence': 'Inteligencia',
    'nav.analysis': 'Analise',
    'nav.trading': 'Trading',
    'nav.unfair_advantage': 'Vantagem Injusta',
    'nav.system': 'Sistema',
    'nav.command_center': 'Centro de Comando',
    'nav.jarvis_hub': 'JARVIS Hub',
    'nav.intel_terminal': 'Terminal Intel',
    'nav.intel_mode': 'Modo Intel',
    'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica',
    'nav.deep_analysis': 'Analise Profunda',
    'nav.market_scanner': 'Scanner de Mercado',
    'nav.signal_timeline': 'Timeline de Sinais',
    'nav.capital_flow': 'Fluxo de Capital',
    'nav.market_dna': 'DNA do Mercado',
    'nav.sentiment': 'Sentimento',
    'nav.weekly_digest': 'Resumo Semanal',
    'nav.my_portfolio': 'Meu Portfolio',
    'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading',
    'nav.trade_simulator': 'Simulador de Trade',
    'nav.decision_replay': 'Replay de Decisao',
    'nav.trader_dna': 'DNA do Trader',
    'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Intel Global',
    'nav.opp_scanner': 'Scanner de Opp.',
    'nav.top_traders': 'Top Traders',
    'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score',
    'nav.aureos_tokens': 'Aureos Tokens',
    'nav.track_record': 'Track Record',
    'nav.settings': 'Configuracoes',
    'nav.alpha_radar': 'Alpha Radar',
    'nav.market_narrative': 'Narrativa',
    'dashboard.greeting_morning': 'Bom dia',
    'dashboard.greeting_afternoon': 'Boa tarde',
    'dashboard.greeting_evening': 'Boa noite',
    'dashboard.market_pulse': 'PULSO DO MERCADO',
    'dashboard.my_portfolio': 'MEU PORTFOLIO',
    'dashboard.intelligence': 'INTELIGENCIA DO DIA',
    'dashboard.global_markets': 'MERCADOS GLOBAIS',
    'common.refresh': 'Atualizar',
    'common.loading': 'Carregando...',
    'common.subscribe': 'Assinar',
    'common.view_all': 'Ver Tudo',
    'common.narrate': 'Narrar com JARVIS',
    'common.narrating': 'Narrando...',
    'common.search': 'Buscar ativos, comandos ou pergunte ao JARVIS...',
    'alpha.title': 'Alpha',
    'alpha.subtitle': 'Radar',
    'alpha.description': 'Onde esta a vantagem agora? Top oportunidades globais com score + probabilidade.',
    'alpha.scan': 'Escanear Alpha',
    'alpha.scanning': 'Escaneando...',
    'narrative.title': 'Narrativa do',
    'narrative.subtitle': 'Mercado',
    'narrative.description': 'JARVIS narra a historia do mercado em tempo real.',
    'narrative.generate': 'Gerar Narrativa',
    'narrative.generating': 'Gerando...',
  },
  en: {
    'nav.intelligence': 'Intelligence',
    'nav.analysis': 'Analysis',
    'nav.trading': 'Trading',
    'nav.unfair_advantage': 'Unfair Advantage',
    'nav.system': 'System',
    'nav.command_center': 'Command Center',
    'nav.jarvis_hub': 'JARVIS Hub',
    'nav.intel_terminal': 'Intel Terminal',
    'nav.intel_mode': 'Intel Mode',
    'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica',
    'nav.deep_analysis': 'Deep Analysis',
    'nav.market_scanner': 'Market Scanner',
    'nav.signal_timeline': 'Signal Timeline',
    'nav.capital_flow': 'Capital Flow',
    'nav.market_dna': 'Market DNA',
    'nav.sentiment': 'Sentiment',
    'nav.weekly_digest': 'Weekly Digest',
    'nav.my_portfolio': 'My Portfolio',
    'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading',
    'nav.trade_simulator': 'Trade Simulator',
    'nav.decision_replay': 'Decision Replay',
    'nav.trader_dna': 'Trader DNA',
    'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Global Intel',
    'nav.opp_scanner': 'Opp Scanner',
    'nav.top_traders': 'Top Traders',
    'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score',
    'nav.aureos_tokens': 'Aureos Tokens',
    'nav.track_record': 'Track Record',
    'nav.settings': 'Settings',
    'nav.alpha_radar': 'Alpha Radar',
    'nav.market_narrative': 'Narrative',
    'dashboard.greeting_morning': 'Good morning',
    'dashboard.greeting_afternoon': 'Good afternoon',
    'dashboard.greeting_evening': 'Good evening',
    'dashboard.market_pulse': 'MARKET PULSE',
    'dashboard.my_portfolio': 'MY PORTFOLIO',
    'dashboard.intelligence': 'INTELLIGENCE OF THE DAY',
    'dashboard.global_markets': 'GLOBAL MARKETS',
    'common.refresh': 'Refresh',
    'common.loading': 'Loading...',
    'common.subscribe': 'Subscribe',
    'common.view_all': 'View All',
    'common.narrate': 'Narrate with JARVIS',
    'common.narrating': 'Narrating...',
    'common.search': 'Search assets, commands, or ask JARVIS...',
    'alpha.title': 'Alpha',
    'alpha.subtitle': 'Radar',
    'alpha.description': 'Where is the edge right now? Top global opportunities with score + probability.',
    'alpha.scan': 'Scan for Alpha',
    'alpha.scanning': 'Scanning...',
    'narrative.title': 'Market',
    'narrative.subtitle': 'Narrative',
    'narrative.description': 'JARVIS narrates the market story in real time.',
    'narrative.generate': 'Generate Narrative',
    'narrative.generating': 'Generating...',
  },
  es: {
    'nav.intelligence': 'Inteligencia',
    'nav.analysis': 'Analisis',
    'nav.trading': 'Trading',
    'nav.unfair_advantage': 'Ventaja Injusta',
    'nav.system': 'Sistema',
    'nav.command_center': 'Centro de Comando',
    'nav.jarvis_hub': 'JARVIS Hub',
    'nav.intel_terminal': 'Terminal Intel',
    'nav.intel_mode': 'Modo Intel',
    'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica',
    'nav.deep_analysis': 'Analisis Profundo',
    'nav.market_scanner': 'Escaner de Mercado',
    'nav.signal_timeline': 'Linea de Senales',
    'nav.capital_flow': 'Flujo de Capital',
    'nav.market_dna': 'ADN del Mercado',
    'nav.sentiment': 'Sentimiento',
    'nav.weekly_digest': 'Resumen Semanal',
    'nav.my_portfolio': 'Mi Portafolio',
    'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading',
    'nav.trade_simulator': 'Simulador de Trade',
    'nav.decision_replay': 'Replay de Decision',
    'nav.trader_dna': 'ADN del Trader',
    'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Intel Global',
    'nav.opp_scanner': 'Escaner de Opp.',
    'nav.top_traders': 'Top Traders',
    'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score',
    'nav.aureos_tokens': 'Aureos Tokens',
    'nav.track_record': 'Track Record',
    'nav.settings': 'Ajustes',
    'nav.alpha_radar': 'Alpha Radar',
    'nav.market_narrative': 'Narrativa',
    'dashboard.greeting_morning': 'Buenos dias',
    'dashboard.greeting_afternoon': 'Buenas tardes',
    'dashboard.greeting_evening': 'Buenas noches',
    'dashboard.market_pulse': 'PULSO DEL MERCADO',
    'dashboard.my_portfolio': 'MI PORTAFOLIO',
    'dashboard.intelligence': 'INTELIGENCIA DEL DIA',
    'dashboard.global_markets': 'MERCADOS GLOBALES',
    'common.refresh': 'Actualizar',
    'common.loading': 'Cargando...',
    'common.subscribe': 'Suscribirse',
    'common.view_all': 'Ver Todo',
    'common.narrate': 'Narrar con JARVIS',
    'common.narrating': 'Narrando...',
    'common.search': 'Buscar activos, comandos o preguntar a JARVIS...',
    'alpha.title': 'Alpha',
    'alpha.subtitle': 'Radar',
    'alpha.description': 'Donde esta la ventaja ahora? Top oportunidades globales con score + probabilidad.',
    'alpha.scan': 'Escanear Alpha',
    'alpha.scanning': 'Escaneando...',
    'narrative.title': 'Narrativa del',
    'narrative.subtitle': 'Mercado',
    'narrative.description': 'JARVIS narra la historia del mercado en tiempo real.',
    'narrative.generate': 'Generar Narrativa',
    'narrative.generating': 'Generando...',
  },
  fr: {
    'nav.intelligence': 'Intelligence', 'nav.analysis': 'Analyse', 'nav.trading': 'Trading', 'nav.unfair_advantage': 'Avantage Injuste', 'nav.system': 'Systeme',
    'nav.command_center': 'Centre de Commande', 'nav.jarvis_hub': 'JARVIS Hub', 'nav.intel_terminal': 'Terminal Intel', 'nav.intel_mode': 'Mode Intel', 'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica', 'nav.deep_analysis': 'Analyse Profonde', 'nav.market_scanner': 'Scanner Marche', 'nav.signal_timeline': 'Chronologie Signaux', 'nav.capital_flow': 'Flux Capital',
    'nav.market_dna': 'ADN Marche', 'nav.sentiment': 'Sentiment', 'nav.weekly_digest': 'Resume Hebdo', 'nav.my_portfolio': 'Mon Portfolio', 'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading', 'nav.trade_simulator': 'Simulateur Trade', 'nav.decision_replay': 'Replay Decision', 'nav.trader_dna': 'ADN Trader', 'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Intel Global', 'nav.opp_scanner': 'Scanner Opp.', 'nav.top_traders': 'Top Traders', 'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score', 'nav.aureos_tokens': 'Aureos Tokens', 'nav.track_record': 'Track Record', 'nav.settings': 'Parametres', 'nav.alpha_radar': 'Alpha Radar', 'nav.market_narrative': 'Narratif',
    'dashboard.greeting_morning': 'Bonjour', 'dashboard.greeting_afternoon': 'Bon apres-midi', 'dashboard.greeting_evening': 'Bonsoir',
    'dashboard.market_pulse': 'POULS DU MARCHE', 'dashboard.my_portfolio': 'MON PORTFOLIO', 'dashboard.intelligence': 'INTELLIGENCE DU JOUR', 'dashboard.global_markets': 'MARCHES MONDIAUX',
    'common.refresh': 'Rafraichir', 'common.loading': 'Chargement...', 'common.subscribe': 'Souscrire', 'common.view_all': 'Voir Tout', 'common.narrate': 'Narrer avec JARVIS', 'common.narrating': 'Narration...',
    'common.search': 'Rechercher actifs, commandes ou demander a JARVIS...',
    'alpha.title': 'Alpha', 'alpha.subtitle': 'Radar', 'alpha.description': 'Ou est lavantage maintenant?', 'alpha.scan': 'Scanner Alpha', 'alpha.scanning': 'Scan en cours...',
    'narrative.title': 'Narratif du', 'narrative.subtitle': 'Marche', 'narrative.description': 'JARVIS raconte lhistoire du marche en temps reel.', 'narrative.generate': 'Generer Narratif', 'narrative.generating': 'Generation...',
  },
  de: {
    'nav.intelligence': 'Intelligenz', 'nav.analysis': 'Analyse', 'nav.trading': 'Trading', 'nav.unfair_advantage': 'Unfairer Vorteil', 'nav.system': 'System',
    'nav.command_center': 'Kommandozentrale', 'nav.jarvis_hub': 'JARVIS Hub', 'nav.intel_terminal': 'Intel Terminal', 'nav.intel_mode': 'Intel Modus', 'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica', 'nav.deep_analysis': 'Tiefenanalyse', 'nav.market_scanner': 'Marktscanner', 'nav.signal_timeline': 'Signal-Zeitleiste', 'nav.capital_flow': 'Kapitalfluss',
    'nav.market_dna': 'Markt-DNA', 'nav.sentiment': 'Stimmung', 'nav.weekly_digest': 'Wochenubersicht', 'nav.my_portfolio': 'Mein Portfolio', 'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading', 'nav.trade_simulator': 'Trade-Simulator', 'nav.decision_replay': 'Entscheidungs-Replay', 'nav.trader_dna': 'Trader-DNA', 'nav.marketplace': 'Marktplatz',
    'nav.global_intel': 'Globale Intel', 'nav.opp_scanner': 'Opp-Scanner', 'nav.top_traders': 'Top Trader', 'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score', 'nav.aureos_tokens': 'Aureos Tokens', 'nav.track_record': 'Track Record', 'nav.settings': 'Einstellungen', 'nav.alpha_radar': 'Alpha Radar', 'nav.market_narrative': 'Narrativ',
    'dashboard.greeting_morning': 'Guten Morgen', 'dashboard.greeting_afternoon': 'Guten Tag', 'dashboard.greeting_evening': 'Guten Abend',
    'dashboard.market_pulse': 'MARKTPULS', 'dashboard.my_portfolio': 'MEIN PORTFOLIO', 'dashboard.intelligence': 'INTELLIGENZ DES TAGES', 'dashboard.global_markets': 'GLOBALE MARKTE',
    'common.refresh': 'Aktualisieren', 'common.loading': 'Laden...', 'common.subscribe': 'Abonnieren', 'common.view_all': 'Alle ansehen', 'common.narrate': 'Mit JARVIS erzahlen', 'common.narrating': 'Erzahlen...',
    'common.search': 'Assets, Befehle suchen oder JARVIS fragen...',
    'alpha.title': 'Alpha', 'alpha.subtitle': 'Radar', 'alpha.description': 'Wo liegt der Vorteil jetzt?', 'alpha.scan': 'Alpha scannen', 'alpha.scanning': 'Scannen...',
    'narrative.title': 'Markt', 'narrative.subtitle': 'Narrativ', 'narrative.description': 'JARVIS erzahlt die Marktgeschichte in Echtzeit.', 'narrative.generate': 'Narrativ generieren', 'narrative.generating': 'Generieren...',
  },
  zh: {
    'nav.intelligence': 'Intelligence', 'nav.analysis': 'Analysis', 'nav.trading': 'Trading', 'nav.unfair_advantage': 'Unfair Advantage', 'nav.system': 'System',
    'nav.command_center': 'Command Center', 'nav.jarvis_hub': 'JARVIS Hub', 'nav.intel_terminal': 'Intel Terminal', 'nav.intel_mode': 'Intel Mode', 'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica', 'nav.deep_analysis': 'Deep Analysis', 'nav.market_scanner': 'Market Scanner', 'nav.signal_timeline': 'Signal Timeline', 'nav.capital_flow': 'Capital Flow',
    'nav.market_dna': 'Market DNA', 'nav.sentiment': 'Sentiment', 'nav.weekly_digest': 'Weekly Digest', 'nav.my_portfolio': 'My Portfolio', 'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading', 'nav.trade_simulator': 'Trade Simulator', 'nav.decision_replay': 'Decision Replay', 'nav.trader_dna': 'Trader DNA', 'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Global Intel', 'nav.opp_scanner': 'Opp Scanner', 'nav.top_traders': 'Top Traders', 'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score', 'nav.aureos_tokens': 'Aureos Tokens', 'nav.track_record': 'Track Record', 'nav.settings': 'Settings', 'nav.alpha_radar': 'Alpha Radar', 'nav.market_narrative': 'Narrative',
    'dashboard.greeting_morning': 'Good morning', 'dashboard.greeting_afternoon': 'Good afternoon', 'dashboard.greeting_evening': 'Good evening',
    'dashboard.market_pulse': 'MARKET PULSE', 'dashboard.my_portfolio': 'MY PORTFOLIO', 'dashboard.intelligence': 'INTELLIGENCE', 'dashboard.global_markets': 'GLOBAL MARKETS',
    'common.refresh': 'Refresh', 'common.loading': 'Loading...', 'common.subscribe': 'Subscribe', 'common.view_all': 'View All', 'common.narrate': 'Narrate with JARVIS', 'common.narrating': 'Narrating...',
    'common.search': 'Search assets, commands, or ask JARVIS...',
    'alpha.title': 'Alpha', 'alpha.subtitle': 'Radar', 'alpha.description': 'Where is the edge right now?', 'alpha.scan': 'Scan Alpha', 'alpha.scanning': 'Scanning...',
    'narrative.title': 'Market', 'narrative.subtitle': 'Narrative', 'narrative.description': 'JARVIS narrates the market story.', 'narrative.generate': 'Generate', 'narrative.generating': 'Generating...',
  },
  ja: {
    'nav.intelligence': 'Intelligence', 'nav.analysis': 'Analysis', 'nav.trading': 'Trading', 'nav.unfair_advantage': 'Unfair Advantage', 'nav.system': 'System',
    'nav.command_center': 'Command Center', 'nav.jarvis_hub': 'JARVIS Hub', 'nav.intel_terminal': 'Intel Terminal', 'nav.intel_mode': 'Intel Mode', 'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica', 'nav.deep_analysis': 'Deep Analysis', 'nav.market_scanner': 'Market Scanner', 'nav.signal_timeline': 'Signal Timeline', 'nav.capital_flow': 'Capital Flow',
    'nav.market_dna': 'Market DNA', 'nav.sentiment': 'Sentiment', 'nav.weekly_digest': 'Weekly Digest', 'nav.my_portfolio': 'My Portfolio', 'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading', 'nav.trade_simulator': 'Trade Simulator', 'nav.decision_replay': 'Decision Replay', 'nav.trader_dna': 'Trader DNA', 'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Global Intel', 'nav.opp_scanner': 'Opp Scanner', 'nav.top_traders': 'Top Traders', 'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score', 'nav.aureos_tokens': 'Aureos Tokens', 'nav.track_record': 'Track Record', 'nav.settings': 'Settings', 'nav.alpha_radar': 'Alpha Radar', 'nav.market_narrative': 'Narrative',
    'dashboard.greeting_morning': 'Good morning', 'dashboard.greeting_afternoon': 'Good afternoon', 'dashboard.greeting_evening': 'Good evening',
    'dashboard.market_pulse': 'MARKET PULSE', 'dashboard.my_portfolio': 'MY PORTFOLIO', 'dashboard.intelligence': 'INTELLIGENCE', 'dashboard.global_markets': 'GLOBAL MARKETS',
    'common.refresh': 'Refresh', 'common.loading': 'Loading...', 'common.subscribe': 'Subscribe', 'common.view_all': 'View All', 'common.narrate': 'Narrate with JARVIS', 'common.narrating': 'Narrating...',
    'common.search': 'Search assets, commands, or ask JARVIS...',
    'alpha.title': 'Alpha', 'alpha.subtitle': 'Radar', 'alpha.description': 'Where is the edge right now?', 'alpha.scan': 'Scan Alpha', 'alpha.scanning': 'Scanning...',
    'narrative.title': 'Market', 'narrative.subtitle': 'Narrative', 'narrative.description': 'JARVIS narrates the market story.', 'narrative.generate': 'Generate', 'narrative.generating': 'Generating...',
  },
  ko: {
    'nav.intelligence': 'Intelligence', 'nav.analysis': 'Analysis', 'nav.trading': 'Trading', 'nav.unfair_advantage': 'Unfair Advantage', 'nav.system': 'System',
    'nav.command_center': 'Command Center', 'nav.jarvis_hub': 'JARVIS Hub', 'nav.intel_terminal': 'Intel Terminal', 'nav.intel_mode': 'Intel Mode', 'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica', 'nav.deep_analysis': 'Deep Analysis', 'nav.market_scanner': 'Market Scanner', 'nav.signal_timeline': 'Signal Timeline', 'nav.capital_flow': 'Capital Flow',
    'nav.market_dna': 'Market DNA', 'nav.sentiment': 'Sentiment', 'nav.weekly_digest': 'Weekly Digest', 'nav.my_portfolio': 'My Portfolio', 'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading', 'nav.trade_simulator': 'Trade Simulator', 'nav.decision_replay': 'Decision Replay', 'nav.trader_dna': 'Trader DNA', 'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Global Intel', 'nav.opp_scanner': 'Opp Scanner', 'nav.top_traders': 'Top Traders', 'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score', 'nav.aureos_tokens': 'Aureos Tokens', 'nav.track_record': 'Track Record', 'nav.settings': 'Settings', 'nav.alpha_radar': 'Alpha Radar', 'nav.market_narrative': 'Narrative',
    'dashboard.greeting_morning': 'Good morning', 'dashboard.greeting_afternoon': 'Good afternoon', 'dashboard.greeting_evening': 'Good evening',
    'dashboard.market_pulse': 'MARKET PULSE', 'dashboard.my_portfolio': 'MY PORTFOLIO', 'dashboard.intelligence': 'INTELLIGENCE', 'dashboard.global_markets': 'GLOBAL MARKETS',
    'common.refresh': 'Refresh', 'common.loading': 'Loading...', 'common.subscribe': 'Subscribe', 'common.view_all': 'View All', 'common.narrate': 'Narrate with JARVIS', 'common.narrating': 'Narrating...',
    'common.search': 'Search assets, commands, or ask JARVIS...',
    'alpha.title': 'Alpha', 'alpha.subtitle': 'Radar', 'alpha.description': 'Where is the edge right now?', 'alpha.scan': 'Scan Alpha', 'alpha.scanning': 'Scanning...',
    'narrative.title': 'Market', 'narrative.subtitle': 'Narrative', 'narrative.description': 'JARVIS narrates the market story.', 'narrative.generate': 'Generate', 'narrative.generating': 'Generating...',
  },
  ar: {
    'nav.intelligence': 'Intelligence', 'nav.analysis': 'Analysis', 'nav.trading': 'Trading', 'nav.unfair_advantage': 'Unfair Advantage', 'nav.system': 'System',
    'nav.command_center': 'Command Center', 'nav.jarvis_hub': 'JARVIS Hub', 'nav.intel_terminal': 'Intel Terminal', 'nav.intel_mode': 'Intel Mode', 'nav.jarvis_copilot': 'JARVIS Copilot',
    'nav.ai_quantica': 'AI Quantica', 'nav.deep_analysis': 'Deep Analysis', 'nav.market_scanner': 'Market Scanner', 'nav.signal_timeline': 'Signal Timeline', 'nav.capital_flow': 'Capital Flow',
    'nav.market_dna': 'Market DNA', 'nav.sentiment': 'Sentiment', 'nav.weekly_digest': 'Weekly Digest', 'nav.my_portfolio': 'My Portfolio', 'nav.watchlist': 'Watchlist',
    'nav.paper_trading': 'Paper Trading', 'nav.trade_simulator': 'Trade Simulator', 'nav.decision_replay': 'Decision Replay', 'nav.trader_dna': 'Trader DNA', 'nav.marketplace': 'Marketplace',
    'nav.global_intel': 'Global Intel', 'nav.opp_scanner': 'Opp Scanner', 'nav.top_traders': 'Top Traders', 'nav.jarvis_challenge': 'JARVIS Challenge',
    'nav.aureos_score': 'Aureos Score', 'nav.aureos_tokens': 'Aureos Tokens', 'nav.track_record': 'Track Record', 'nav.settings': 'Settings', 'nav.alpha_radar': 'Alpha Radar', 'nav.market_narrative': 'Narrative',
    'dashboard.greeting_morning': 'Good morning', 'dashboard.greeting_afternoon': 'Good afternoon', 'dashboard.greeting_evening': 'Good evening',
    'dashboard.market_pulse': 'MARKET PULSE', 'dashboard.my_portfolio': 'MY PORTFOLIO', 'dashboard.intelligence': 'INTELLIGENCE', 'dashboard.global_markets': 'GLOBAL MARKETS',
    'common.refresh': 'Refresh', 'common.loading': 'Loading...', 'common.subscribe': 'Subscribe', 'common.view_all': 'View All', 'common.narrate': 'Narrate with JARVIS', 'common.narrating': 'Narrating...',
    'common.search': 'Search assets, commands, or ask JARVIS...',
    'alpha.title': 'Alpha', 'alpha.subtitle': 'Radar', 'alpha.description': 'Where is the edge right now?', 'alpha.scan': 'Scan Alpha', 'alpha.scanning': 'Scanning...',
    'narrative.title': 'Market', 'narrative.subtitle': 'Narrative', 'narrative.description': 'JARVIS narrates the market story.', 'narrative.generate': 'Generate', 'narrative.generating': 'Generating...',
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('aureos_lang') || 'pt');

  const changeLang = useCallback((code) => {
    setLang(code);
    localStorage.setItem('aureos_lang', code);
  }, []);

  const t = useCallback((key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  }, [lang]);

  const langName = LANGUAGES.find(l => l.code === lang)?.label || 'English';

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t, langName, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};
